- modules/core/02-client/client/cli/tx.go
Add a upgraded client state json example into cli help command. Fix parsing plan height bug which attempted to use non-existent flag
closes: #87 
---
> add upgrade example and fix cli bug

- README.md
- docs/custom.md
- docs/integration.md
- docs/overview.md
- docs/relayer.md
A similar pr will need to be made on the SDK
closes: #89
closes: #76
---
> Fix links in documentation

- .mergify.yml
> Allow automerge with 1 approved review

- .github/workflows/test.yml
- Makefile
- modules/apps/transfer/keeper/encoding.go
norace flag is a sdk level item due to concurrency bugs, I dont these present in this repo. 
closes: #XXXX
---
> ci: remove extra race ci tests

- docs/overview.md
Update the ICS-24 link in the IBC overview document to latest one
---
> Update IBC overview document to latest ICS-24 link

- testing/README.md
- testing/app.go
- testing/chain.go
- testing/mock/mock.go
- testing/simapp/app.go
> ibc testing refactor part 4

- docs/architecture/README.md
- docs/architecture/adr-001-coin-source-tracing.md
- docs/architecture/adr-015-ibc-packet-receiver.md
- docs/architecture/adr-025-ibc-passive-channels.md
- docs/architecture/adr-026-ibc-client-recovery-mechanisms.md
- docs/architecture/adr-template.md
I changed ADR 25 to "deprecated" as well
closes: #86 
---
> add ADRs from SDK

- CONTRIBUTING.md
I copied over contributor doc from SDK and updated it to our needs. It is worthwhile to give a brief read since all contributors are likely to start by reading this document
closes: #111
---
>  contributing docs

- CHANGELOG.md
thanks for the suggestion @ebuchman 
closes: #188 
---
> Reference commit hash IBC was removed from the SDK in the changelog

- modules/core/03-connection/genesis.go
tested locally
closes: #XXXX
---
> export connection params

- CHANGELOG.md
- modules/core/03-connection/genesis.go
> prep changelog for rc0

- docs/migrations/ibc-migration-043.md
> fix migration doc link

- docs/ibc/integration.md
- modules/apps/transfer/spec/01_concepts.md
> Update outdated documentation

- docs/ibc/upgrades/genesis-restart.md
- docs/ibc/upgrades/quick-guide.md
> add genesis restart docs

- go.mod
- go.sum
> bump SDK dep to v0.43.0-rc1

- CHANGELOG.md
- docs/ibc/integration.md
- docs/ibc/upgrades/genesis-restart.md
- docs/ibc/upgrades/quick-guide.md
- docs/migrations/ibc-migration-043.md
- go.mod
- go.sum
- modules/apps/transfer/spec/01_concepts.md
> backport rc1 changes

- docs/client/config.json
- docs/client/swagger-ui/swagger.yaml
- scripts/protoc-swagger-gen.sh
> generate swagger files

- CHANGELOG.md
- modules/apps/transfer/keeper/keeper.go
- modules/apps/transfer/types/expected_keepers.go
> release backports

- go.mod
- go.sum
- modules/core/02-client/keeper/client_test.go
- testing/simapp/app.go
> bump to SDK v0.43.0-rc3

- .github/CODEOWNERS
the code owners file will only request review from the codeowners based on the codeowner file in the default branch (main). We already plan to integrate the interchain accounts module and add @seantking as a codeowner for it. This will allow sean to be requested for review by any changes to the interchain accounts module on any branch (I'm fairly certain)
As the [code owners file syntax](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-code-owners#codeowners-file-location) explains, this gives @seantking shared code ownership of only the interchain accounts module
closes: #XXXX
---
checked off. If any of the checklist items are not …
> add @seantking as codeowner to interchain accounts module

- CHANGELOG.md
- go.mod
- go.sum
- modules/core/02-client/keeper/client_test.go
- testing/simapp/app.go
> prepare changes for rc4 release

- modules/core/04-channel/keeper/packet.go
> module: improve 04-channel logging

- CHANGELOG.md
- go.mod
- go.sum
- modules/core/04-channel/keeper/packet.go
> backport fixes for v1.0.0 release

- CHANGELOG.md
> update main branch changelog for final release

- go.mod
- go.sum
- modules/core/02-client/keeper/client_test.go
- testing/sdk_test.go
bumps SDK version from v0.43 -> v0.44
closes: #XXXX
---
> bump SDK dependency

- .github/workflows/link-check.yml
- adding markdown link checker to CI workflows
closes: #253 
---
> adding markdown link checker to CI workflows

- modules/apps/29-fee/client/cli/cli.go
- modules/apps/29-fee/keeper/keeper.go
- modules/apps/29-fee/keeper/keeper_test.go
- modules/apps/29-fee/types/expected_keepers.go
- modules/apps/29-fee/types/keys.go
- modules/apps/29-fee/types/msgs.go
closes: https://github.com/cosmos/ibc-go/pull/376#discussion_r704261857
---
> fix: remove comments for imports

- modules/apps/27-interchain-accounts/keeper/relay.go
Thought to do this before I forget
closes: #XXXX
---
> ICA: Fix OnRecvPacket error string

- RELEASES.md
> Resize and center the decision tree picture

- CHANGELOG.md
- go.mod
- go.sum
Backport of #485 to cut v1.1.2
---
> backport #485 to v.1.1.x

- CHANGELOG.md
- go.mod
- go.sum
- testing/simapp/simd/cmd/root.go
> deps: bump cosmos-sdk `v0.44.3`

- modules/apps/27-interchain-accounts/keeper/keeper.go
> fix ica keeper comment typo

- CHANGELOG.md
> update changelog (forgot title for dependencies section)

- docs/.vuepress/config.js
> docs: add middleware child to navigation

- CHANGELOG.md
I think this link was ok before, but somehow started to fail now...
closes: #XXXX
---
> fix broken link

- .github/CODEOWNERS
Adding @damiannolan as code owner for ICA :partying_face: 
---
> ICA: Codeowner

- modules/apps/27-interchain-accounts/keeper/relay.go
- modules/apps/27-interchain-accounts/keeper/relay_test.go
This PR adds various `sdk.Msg` types to the existing relay tests and cleans up the structure.
This includes tx msgs from the following:
- x/staking
- x/gov/
- x/distribution
- IBC apps/transfer
closes: #510
---
> test: relay tests for TrySendTx/OnRecvPacket

- docs/README.md
add a brief IBC description that first-time readers will embrace " IBC is a protocol that allows blockchains to talk to each other."
So many links in the universe have links that go to this IBC docs home page, but then it's difficult to parse out a quick definition of IBC.
This PR adds a brief IBC description that first-time readers can embrace "IBC is a protocol that allows blockchains to talk to each other."
---
> docs: apply IBC capitalization standards and add simple desc

- docs/ibc/overview.md
Apply technical style standards, present tense, fix typos, and use consistent IBC language
We all know that IBC is how blockchains speak to each other. The world is watching, let's use our best editorial content quality standards for this essential content. 
closes: #XXXX
---
> docs: editorial love for IBC overview

- go.mod
- go.sum
> bump SDK version to v0.44.5

- docs/.vuepress/config.js
- docs/versions
This adds v2.0.0 to the version drop down menu in the ibc-go docs site.
closes: #XXXX
---
> docs: add v2.0.0 to docs site

- docs/.vuepress/config.js
- docs/versions
Co-authored-by: Carlos Rodriguez <crodveg@gmail.com>
Backport #593.
closes: #XXXX
---
> backport 593 to v2.0.x

- CHANGELOG.md
Changelog for ICA 
closes: #XXXX
---
> chore: add changelog for ICA

- docs/app_modules/interchain-accounts/integration.md
- Adding docs for Interchain Accounts on-chain params
closes: #XXXX
---
> docs: adding interchain accounts params docs

- CHANGELOG.md
- go.mod
- go.sum
- modules/core/keeper/msg_server.go
Backport #589 and #603.
closes: #XXXX
---
> backport #589 #603 to v2.0.x

- CHANGELOG.md
- go.mod
- go.sum
- modules/core/keeper/msg_server.go
Backport #589 and #603.
closes: #XXXX
---
> backport #589 #603 to v1.2.x

- docs/package-lock.json
- go.mod
- go.sum
A couple security vulnerabilities have been reported via go dependency bot. This updates the build fixing a couple reported issues. 
closes: #XXXX
---
> update go mod for security vulnerabilities

- docs/package-lock.json
ran `npm install` within `docs`. Prevents `make build-docs` from finishing without this change
closes: #XXXX
---
> backport v1.2.x: update docs package-lock.json

- docs/package-lock.json
ran `npm install` within `docs`. Prevents `make build-docs` from finishing without this change
closes: #XXXX
---
> backport v1.1.x: docs npm update

- docs/package-lock.json
ran `npm install` within `docs`. Prevents `make build-docs` from finishing without this change
closes: #XXXX
---
> backport v2.0.x: docs npm update

- docs/package-lock.json
- docs/package.json
Running `make build-docs` fails due to vue and vue-server-renderer version mismatch. Bumps vue version
closes: #XXXX
---
> chore: update vue dependency

- docs/package-lock.json
- docs/package.json
fixes reported security vulnerability (via dependabot)
closes: #XXXX
---
> bump glob-parent version in json package

- CHANGELOG.md
- docs/ibc/apps.md
- docs/ibc/middleware/develop.md
- docs/ibc/proto-docs.md
- docs/migrations/v2-to-v3.md
- modules/apps/27-interchain-accounts/controller/ibc_module.go
- modules/apps/27-interchain-accounts/controller/ibc_module_test.go
- modules/apps/27-interchain-accounts/host/ibc_module.go
- modules/apps/27-interchain-accounts/host/ibc_module_test.go
- modules/apps/27-interchain-accounts/host/keeper/handshake.go
- modules/apps/27-interchain-accounts/host/keeper/handshake_test.go
- modules/apps/27-interchain-accounts/host/keeper/keeper_test.go
- modules/apps/27-interchain-accounts/host/keeper/relay_test.go
- modules/apps/transfer/ibc_module.go
- modules/apps/transfer/ibc_module_test.go
- modules/apps/transfer/keeper/keeper_test.go
- modules/apps/transfer/transfer_test.go
- modules/core/04-channel/keeper/handshake.go
- modules/core/04-channel/keeper/handshake_test.go
- modules/core/04-channel/types/msgs.go
- modules/core/04-channel/types/tx.pb.go
- modules/core/05-port/types/module.go
- modules/core/keeper/msg_server.go
- proto/ibc/core/channel/v1/tx.proto
- testing/endpoint.go
- testing/mock/ibc_app.go
- testing/mock/ibc_module.go
- testing/values.go
Last pr to close #640 
ref: #640 
---
> Modify `OnChanOpenTry` to return application version

- .github/workflows/check-docs.yml
- Makefile
> chore: update make build-docs, add docs build checker

- modules/apps/27-interchain-accounts/controller/client/cli/query.go
- modules/apps/27-interchain-accounts/host/client/cli/query.go
- modules/apps/27-interchain-accounts/module.go
- modules/apps/transfer/client/cli/query.go
> register ICA query server, fix panics in params query cli

- CHANGELOG.md
- modules/core/04-channel/keeper/packet.go
- modules/core/04-channel/keeper/timeout.go
> improve 04-channel logging

- README.md
Adding Interchain Accounts to README.md supported applications
closes: #620
---
> chore: add interchain accounts to README.md

- proto/ibc/applications/interchain_accounts/controller/v1/controller.proto
- proto/ibc/applications/interchain_accounts/controller/v1/query.proto
- proto/ibc/applications/interchain_accounts/host/v1/host.proto
- proto/ibc/applications/interchain_accounts/host/v1/query.proto
Removes some unused proto imports identified from #717 
closes: #XXXX
---
> chore: removing unused proto imports in interchain-accounts

- LICENSE
> Update copyright date in license file

- docs/package-lock.json
- docs/package.json
Fixes the reported security vulnerability (insignificant to us) 
closes: #XXXX
---
> bump dependency in json docs lock file

- modules/apps/29-fee/ibc_module.go
> refactor: app version + add comment

- docs/package.json
This new version of `vuepress-theme-cosmos` has [bumped the dependency on markdown-it](https://github.com/cosmos/vuepress-theme-cosmos/pull/311/files), so the vulnerability should now be fixed and we don't need it to explicitly add it to our package.json.
closes: #XXXX
---
> deps: bump vuepress-theme-cosmos

- third_party/proto/buf.yaml
Fixes `proto-lint` failure. 
Confio's `ics23` proofs.proto was moved to the root of `third_party` in a previous PR. Buf.yaml was never updated to ignore it.
closes: #642 
---
> fix: resolve proto lint failure

- testing/simapp/app.go
Minor fix for app.go
closes: #772 
---
> fix: app.go

- modules/apps/27-interchain-accounts/host/keeper/relay.go
I noticed the code structure on the host chain relay.go didn't make sense while implementing #701. The entrypoint was at the bottom of the file. I also made `AuthenticateTx` private as it doesn't need to be public
No other code changed, just moved around
closes: #XXXX
---
> restructure host chain receive packet code logically and minimize API

- docs/app-modules/interchain-accounts/overview.md
Wording could maybe be improved, but I think the content is good enough
closes: #705 
---
> docs: add security model to ics27 docs

- modules/apps/27-interchain-accounts/controller/keeper/account_test.go
closes: https://github.com/cosmos/ibc-go/pull/814#issuecomment-1027916206
---
> test: Register using same owner address on multiple connections

- modules/apps/27-interchain-accounts/host/ibc_module.go
- Updating host submodule `OnRecvPacket` to return deterministic error acknowledgement 
closes: #XXXX
---
> fix: ica host OnRecvPacket error acknowledgement

- CHANGELOG.md
- modules/core/04-channel/types/codec.go
- modules/core/04-channel/types/codec_test.go
Required as part of https://github.com/cosmos/ibc-go/pull/749
closes: #XXXX
---
> feat: adding Pack/Unpack acknowledgement helper fns

- modules/apps/29-fee/ibc_module.go
Small fix: returning nil on OnRecvPacket for async WriteAck. We can write the test as part of my PR for updating WriteAck API. 
closes: #770 
---
> fix: return nil on OnRecvPacket for async pay

- testing/app.go
> Fix genesis setup

- modules/core/02-client/keeper/grpc_query_test.go
- modules/light-clients/07-tendermint/types/client_state.go
- modules/light-clients/07-tendermint/types/client_state_test.go
> fix: classify client states without consensus states as expired

- docs/ibc/relayer.md
> chore: fix broken link

- modules/apps/transfer/types/ack_test.go
While fixing the conflicts of [backport #992](https://github.com/cosmos/ibc-go/pull/992) I realized that the wrong package was being imported.
closes: #XXXX
---
> fix package import

- modules/apps/29-fee/client/cli/cli.go
- Adding missing queries to cmd builder
closes: #XXXX
---
> chore: adding missing queries to cmd builder

- CHANGELOG.md
- go.mod
- go.sum
This reverts the bump to SDK 0.45.
closes: #XXXX
---
> deps: revert bump to SDK 0.45.1

- docs/migrations/v2-to-v3.md
> Fix ICA migration docs for upgrade proposal

- docs/migrations/v2-to-v3.md
- modules/apps/27-interchain-accounts/module.go
- modules/apps/27-interchain-accounts/module_test.go
> fix: adjust InitModule to account for empty controller and host keepers

- modules/apps/transfer/keeper/relay.go
- modules/apps/transfer/keeper/relay_test.go
- modules/apps/transfer/types/expected_keepers.go
> backport GHSA-j658-c98j-fww4 to v1.3.x

- modules/apps/transfer/keeper/relay.go
- modules/apps/transfer/keeper/relay_test.go
- modules/apps/transfer/types/expected_keepers.go
> backport GHSA-j658-c98j-fww4 to v2.2.x

- modules/apps/transfer/keeper/relay.go
- modules/apps/transfer/keeper/relay_test.go
- modules/apps/transfer/types/expected_keepers.go
> backport GHSA-j658-c98j-fww4 to v3.0.x

- modules/apps/transfer/keeper/relay.go
- modules/apps/transfer/keeper/relay_test.go
- modules/apps/transfer/types/expected_keepers.go
> backport GHSA-j658-c98j-fww4 to v1.4.x

- docs/.vuepress/config.js
- docs/versions
> add versions for new releases

- docs/.vuepress/config.js
- docs/versions
> add version for v1.3

- docs/.vuepress/config.js
- docs/versions
> add versions to v1.4

- docs/.vuepress/config.js
- docs/versions
> add versions to v2.2

- docs/roadmap/roadmap.md
- Link checker reporting a dead link (404) for [milestones/14 ](https://github.com/cosmos/ibc-go/milestone/14)
closes: #XXXX
---
> fix: link checker reporting broken milestone link in roadmap.md

- modules/apps/29-fee/keeper/escrow.go
- modules/apps/29-fee/types/codec.go
> chore: ics29 housekeeping cleanup

- docs/ibc/apps.md
I noticed that 2 links at the bottom of the applications docs page were not correct.
closes: #XXXX
---
> docs: replace links in apps with correct ones

- modules/apps/27-interchain-accounts/controller/keeper/account.go
The godoc of `RegisterInterchainAccount` was still saying that the port identifier was constructed using as well the connection identifiers. I corrected that.
closes: #XXXX
---
> update godoc of `RegisterInterchainAccount`

- RELEASES.md
> Update supported release lines

- CHANGELOG.md
> add missing changelog entry for bump of sdk 0.45.3

- docs/.vuepress/config.js
> override default docsBranch

- CHANGELOG.md
- modules/apps/transfer/ibc_module.go
> feat: Add sender to fungible_token_packet events

- .github/workflows/check-docs.yml
- .github/workflows/codeql-analysis.yml
Two of our workflows were consistently failing due to an error in the yaml definition.
This PR fixes these issues.
Paths example from the [docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-paths) (it was not indented enough)
The autobuild action was also failing for the CodeQL action, I've replaced it with `make build` instead.
closes: #XXXX
---
> Fixing github action workflows

- .github/CODEOWNERS
Adds @chatton to the list of global code owners! 🎉 
closes: #XXXX
---
> add new team member to global code owners

- .github/CODEOWNERS
> add section for fee code owners

- .github/CODEOWNERS
I think the path to the proto files was wrong...
closes: #XXXX
---
> fix path to proto files in codeowners sections

- .github/workflows/test.yml
- Dockerfile
This PR adds a basic Dockerfile which contains the simd application. This can be used for dev/test environments.
closes: #XXXX
---
> Add simd Dockerfile

- docs/.vuepress/config.js
- docs/middleware/ics29-fee/overview.md
> docs: overview of fee middleware module

- docs/.vuepress/config.js
> add migration for base denoms with slashes to docs site

- docs/.vuepress/config.js
> add migration of v3 to v4 to docs site

- docs/.vuepress/config.js
> add new release lines to dropdown menu

- modules/apps/27-interchain-accounts/types/metadata.go
> fix typo in parameter name of `NewDefaultMetadata`

- docs/ibc/events.md
I realized that we were missing this, but when I went to comment on @seantking's [PR](https://github.com/cosmos/ibc-go/pull/1570) it had already been merged... When this gets merged, I will backport the changes to the already opened backport branches for #1570 manually.
closes: #XXXX
---
> docs: add upgrade client proposal event

- .github/mergify.yml
> chore: update mergify.yml with new release branches

- .github/CODEOWNERS
> chore: remove @fedekunze from CODEOWNERS

- modules/apps/transfer/keeper/MBT_README.md
Fixes the broken link that has been failing in CI.
closes: #XXXX
---
> fix broken link to apalache's docker documentation

- .github/ISSUE_TEMPLATE/release-tracker.md
Adds items to the checklist to update the version matrix after a release is published.
closes: #XXXX
---
> add item to update the version matrix after a release

- modules/core/24-host/channel_keys.go
> chore: add UpgradeErrorPath to 24-host

- modules/light-clients/06-solomachine/misbehaviour.go
> chore: remove GetHeight legacy method from 06-solomachine

- .github/mergify.yml
> chore: add backport task for v5.0.x

- .github/mergify.yml
> chore: add task for backport to v6.0.x

- modules/core/exported/client.go
- modules/core/genesis_test.go
> fix: exported client.go changes for 02-client-refactor

- docs/architecture/adr-027-ibc-wasm.md
> fix: update ADR status

- e2e/testsuite/testsuite.go
- modules/apps/transfer/keeper/mbt_relay_test.go
- modules/core/02-client/client/cli/tx.go
- modules/core/03-connection/client/utils/utils.go
- testing/simapp/state.go
- testing/simapp/utils.go
This PR removes the deprecated io/ioutil library from ibc-go, and replaces it with os.
---
> chore: don't use ioutil

- .github/workflows/release.yml
> chore: adding release task to release/2.4.x

- .github/workflows/release.yml
- Dockerfile
> chore: adding dockerfile and release task to release/2.1.x

- .github/workflows/release.yml
- Dockerfile
> chore: adding dockerfile and release task to release/3.0.x

- .github/workflows/release.yml
- Dockerfile
> chore: adding dockerfile and release task to release/2.3.x

- .github/workflows/release.yml
- Dockerfile
> chore: adding dockerfile and release task to release/3.1.x

- .github/workflows/release.yml
- Dockerfile
> chore: adding dockerfile and release task to release/2.2.x

- .github/workflows/e2e.yaml
Authentication is already done during the `docker-build` job and is not needed for running the tests. 
closes: #XXXX
---
> refactor: remove unnecessary authentication e2e tests

- e2e/testsuite/testsuite.go
Adding a missing import that was causing e2e build failures.
---
> Adding import for clienttypes

- .github/workflows/e2e-manual.yaml
This PR adds an additional step that displays the input values. An example can be found [here](https://github.com/cosmos/ibc-go/runs/7783804885?check_suite_focus=true)
---
> Add visibility into Manual E2E inputs specified

- modules/light-clients/07-tendermint/misbehaviour.go
> refactor: remove unused GetHeight fn

- .github/workflows/test.yml
> Adding build requirement for e2e

- CHANGELOG.md
> update changelog after v4.0.0 release

- RELEASES.md
- docs/.vuepress/config.js
- docs/versions
> chore: update releases.md and docs website

- docs/ibc/relayer.md
> fix broken link to tendermint 0.35 rpc

- testing/simapp/simd/cmd/genaccounts.go
There was a bug with trying to add a genesis account using the key name, so I bumped the code to be identical to the latest changes on the SDK
[ref](https://github.com/informalsystems/ibc-rs/issues/2581)
closes: #XXXX
---
> fix: update simd gen accounts cmd to perform same functionality as SDK

- CHANGELOG.md
- modules/apps/27-interchain-accounts/controller/keeper/keeper.go
- modules/apps/27-interchain-accounts/host/keeper/keeper.go
- modules/apps/27-interchain-accounts/types/expected_keepers.go
Add scoped keeper interface for interchain app
Part of: #2020
---
> Add scoped keeper interface for interchain app

- testing/simapp/app.go
- testing/simapp/upgrades/upgrades.go
> testing: add base upgrade handler

- .github/workflows/e2e-manual-icad.yaml
- e2e/scripts/test-matricies/main/test-matrix.json
- e2e/testsuite/testsuite.go
> Update icad manual e2e versions

- docs/package-lock.json
A flaw was found in the EventSource NPM Package. The description from the source states the following message: "Exposure of Sensitive Information to an Unauthorized Actor." This flaw allows an attacker to steal the user's credentials and then use the credentials to access the legitimate server. When fetching an url with a link to an external site (Redirect), the users Cookies & Autorisation headers are leaked to the third party application. According to the same-origin-policy, the header should be "sanitized".
**Proof of Concept**
Start a nodejs server (attacker):
```js
const express = require('express')
const app = express()
app.get('/', function (req, res) {
console.log(req.headers);
res.status(200).send()
})
app.listen(3000)
console.log('listening on port 3000');
```
**CVE-2022-1650** …
> CVE-2022-1650 Exposure of Sensitive Information to an Unauthorized Actor

- .github/workflows/e2e-fork.yml
- .github/workflows/e2e-upgrade.yaml
- .github/workflows/e2e.yaml
This PR adds a new CI task which runs every night at midnight and can be triggered through the UI or `gh cli`.
The upgrade tasks will no longer run against PRs.
closes: #2187
closes: #2182
---
> Don't run upgrade tests on PRs

- e2e/README.md
The existing steps about running tests locally can be used to provide custom images.
I created a sample repo which has CI tasks which run our tests as a starting point for anyone who wants to do this with Github Actions.
closes: #2027
---
> Update docs to include details about running our e2e tests

- .github/mergify.yml
- Added `v3.3.x` and `v4.1.x` to back port [#2228](https://github.com/cosmos/ibc-go/pull/2228).
- Removed `v5.1.x`.
closes: #XXXX
---
> chore: update mergify.yml to add v3.3.x and v4.1.x and remove v5.1.x

- e2e/scripts/test-matricies/icad/test-matrix.json
- e2e/tests/interchain_accounts/base_test.go
The following was produced by running
```bash
make compatibility-tests version=icad
```
Using the new test matrix added.
---
> Fixing semver version check in e2e

- docs/ibc/relayer.md
> fix broken link/update link

- CHANGELOG.md
- RELEASES.md
- docs/.vuepress/config.js
- docs/versions
> post release chores

- README.md
cc  @charleenfei 
closes: #XXXX
---
> docs: readme revamp - add releases and security sections

- .github/workflows/deploy-docs.yml
> docs: fix deploy docs workflow

- CHANGELOG.md
- docs/migrations/v4-to-v5.md
- modules/apps/27-interchain-accounts/controller/keeper/keeper.go
- modules/apps/27-interchain-accounts/host/keeper/keeper.go
- modules/apps/27-interchain-accounts/types/expected_keepers.go
> revert #2361 in release v5.0.x

- .github/PULL_REQUEST_TEMPLATE.md
- docs/DOCS_README.md
- docs/apps/transfer/metrics.md
- docs/ibc/apps.md
- docs/ibc/apps/apps.md
- docs/ibc/integration.md
- docs/ibc/overview.md
- docs/ibc/relayer.md
- docs/middleware/ics29-fee/fee-distribution.md
> chore: fix broken links

- .github/workflows/e2e-fork.yml
> fix: updating e2e fork workflow to accommodate intertx name change

- e2e/tests/interchain_accounts/base_test.go
- e2e/tests/interchain_accounts/groups_test.go
- e2e/tests/interchain_accounts/incentivized_test.go
I wonder how the e2e tests passed for #2607...
closes: #XXXX
---
> fix e2e ica tests

- modules/apps/27-interchain-accounts/controller/keeper/account.go
> remove duplicate import

- CHANGELOG.md
- modules/apps/transfer/keeper/msg_server.go
- modules/apps/transfer/keeper/msg_server_test.go
- modules/apps/transfer/types/expected_keepers.go
> add check send enabled

- .github/compatibility-test-matrices/release-v2.5.x/transfer.json
- .github/compatibility-test-matrices/release-v3.4.x/transfer.json
- .github/compatibility-test-matrices/release-v4.2.x/incentivized-transfer.json
- .github/compatibility-test-matrices/release-v4.2.x/transfer.json
- .github/compatibility-test-matrices/release-v5.0.x/client.json
- .github/compatibility-test-matrices/release-v5.0.x/connection.json
- .github/compatibility-test-matrices/release-v5.0.x/incentivized-transfer.json
- .github/compatibility-test-matrices/release-v5.0.x/transfer.json
- .github/compatibility-test-matrices/release-v5.1.x/incentivized-transfer.json
- .github/compatibility-test-matrices/release-v5.1.x/transfer.json
- .github/compatibility-test-matrices/release-v6.0.x/client.json
- .github/compatibility-test-matrices/release-v6.0.x/connection.json
- .github/compatibility-test-matrices/release-v6.0.x/incentivized-transfer.json
- .github/compatibility-test-matrices/release-v6.0.x/transfer.json
- .github/workflows/e2e-manual-simd.yaml
- CHANGELOG.md
- RELEASES.md
- docs/.vuepress/config.js
- docs/versions
> post v2.5.0, v3.4.0, v4.2.0 release chores

- e2e/tests/transfer/base_test.go
> e2e: fix memo test version declaration

- docs/apps/interchain-accounts/integration.md
- docs/middleware/ics29-fee/integration.md
Another small documentation fix.
closes: #XXXX
---
> docs: add missing set order functions for ICA

- modules/light-clients/06-solomachine/client_state_test.go
test: added test to verify signbytes marshal correctly for single signature solomachine
closes: #1914
---
> Ensure solomachine marshals nil and []byte in sign bytes the same

- docs/dev/project-structure.md
> docs: refactor contributing guidelines - add project structure

- .github/mergify.yml
It deletes the backport tasks for v5.0.x and v5.1.x, since those release lines are going to be discontinued.
closes: #XXXX
```bash
chore: add backport mergify task for v5.2.x
```
---
> chore: mergify backport task for v5.2.x

- .github/workflows/e2e-compatibility-workflow-call.yaml
closes: #XXXX
By explicitly checking out ibc-go, it means this workflow can be imported in other workflows, e.g.
```yaml
uses: cosmos/ibc-go/.github/workflows/e2e-compatibility-workflow-call.yaml@main
with:
test-file-directory: foo
test-suite: bar
```
And it will use the e2e tests in this repo. As opposed to looking for them in the repo the calling workflow is in.
```bash
e2e: enabling compatibility tests to be usable from other repositories' CI.
```
---
write a little note …
> Make compatibility tests explicitly check out ibc-go

- modules/light-clients/06-solomachine/errors.go
- modules/light-clients/06-solomachine/keys.go
- modules/light-clients/06-solomachine/module.go
closes: #2834
This issue seems trivial enough that it doesn't warrant a changelog entry, happy to add one if someone things otherwise!
N/A
---
> Renaming variable SubModuleName to ModuleName

- modules/light-clients/07-tendermint/errors.go
- modules/light-clients/07-tendermint/keys.go
- modules/light-clients/07-tendermint/module.go
closes: #2833
This issue seems trivial enough that it doesn't warrant a changelog entry, happy to add one if someone things otherwise! (same as #2851)
N/A
---
> Renaming variable SubmoduleName to ModuleName in 07-tendermint

- CHANGELOG.md
- modules/core/02-client/types/keys.go
> chore: follow up for #2510

- modules/apps/27-interchain-accounts/controller/keeper/events.go
- modules/apps/27-interchain-accounts/controller/keeper/msg_server_test.go
- modules/apps/27-interchain-accounts/host/keeper/events.go
- modules/apps/29-fee/keeper/events.go
- modules/apps/transfer/ibc_module.go
- modules/apps/transfer/keeper/msg_server.go
- modules/core/02-client/keeper/events.go
- modules/core/03-connection/keeper/events.go
- modules/core/04-channel/keeper/events.go
applied upgrading [docs](https://github.com/cosmos/cosmos-sdk/blob/main/UPGRADING.md#all) from sdk
```bash
```
---
> chore: remove duplicate event emissions 

- e2e/semverutil/semver.go
- e2e/semverutil/semver_test.go
- e2e/testconfig/testconfig.go
- e2e/tests/transfer/base_test.go
- modules/apps/27-interchain-accounts/controller/keeper/events.go
- modules/apps/27-interchain-accounts/controller/keeper/msg_server_test.go
- modules/apps/27-interchain-accounts/host/keeper/events.go
- modules/apps/29-fee/keeper/events.go
- modules/apps/transfer/ibc_module.go
- modules/apps/transfer/keeper/msg_server.go
- modules/core/02-client/keeper/events.go
- modules/core/03-connection/keeper/events.go
- modules/core/04-channel/keeper/events.go
> Dynamically determine gov genesis state

- modules/apps/transfer/keeper/msg_server.go
```bash
nit: fix typo in a comment
```
---
A small typo fix for a comment - most of the checklist items are not applicable.
> Fix typo in a comment

- .github/workflows/e2e-compatibility-workflow-call.yaml
closes: #XXXX
Workflow run [here](https://github.com/cosmos/ibc-go/actions/runs/3712162977)
N/A
---
> Skip e2e if test matrix does not exist

- .github/mergify.yml
closes: #XXXX
```bash
chore: add backports for v4.3.x and v6.1.x
```
---
> chore: add backports for v4.3.x and v6.1.x

- docs/ibc/light-clients/genesis.md
- Light client guide `ExportMetadata`
closes: #1857 
```bash
docs: adding export metadata docs for light client module genesis
```
---
> docs: adding export metadata docs for light client module genesis

- README.md
The icq and rate limiting links were pointing to outdated links (module repo has moved and rate limiting is no longer as a pr but implemented) so this updates them both.
```bash
docs: updating README.md
```
---
> Update the ecosystem links in the readme

- docs/dev/pull-requests.md
> docs: refactor contributing guidelines - add pull request guidelines

- Dockerfile
This PR temporarily adds all files to the simd docker container. This is being done as currently other branches depend on this Dockerfile but the requirements have diverged and so each branch will need its own Dockerfile.
This will be done in some follow up PRs.
> Temporarily update dockerfile to add all

- proto/buf.yaml
- Fix buf schema registry repository in buf.yaml
closes: #XXXX
```bash
chore: use correct BSR proto repo in buf.yaml
```
---
> chore: use correct BSR proto repo in buf.yaml

- .github/compatibility-test-matrices/release-v7.0.x/client-chain-a.json
- .github/compatibility-test-matrices/release-v7.0.x/client-chain-b.json
- .github/compatibility-test-matrices/release-v7.0.x/connection-chain-a.json
- .github/compatibility-test-matrices/release-v7.0.x/connection-chain-b.json
- .github/compatibility-test-matrices/release-v7.0.x/ica-chain-a.json
- .github/compatibility-test-matrices/release-v7.0.x/ica-chain-b.json
- .github/compatibility-test-matrices/release-v7.0.x/ica-gov-chain-a.json
- .github/compatibility-test-matrices/release-v7.0.x/ica-gov-chain-b.json
- .github/compatibility-test-matrices/release-v7.0.x/ica-groups-chain-a.json
- .github/compatibility-test-matrices/release-v7.0.x/ica-groups-chain-b.json
- .github/compatibility-test-matrices/release-v7.0.x/incentivized-ica-chain-a.json
- .github/compatibility-test-matrices/release-v7.0.x/incentivized-ica-chain-b.json
- .github/compatibility-test-matrices/release-v7.0.x/incentivized-transfer-chain-a.json
- .github/compatibility-test-matrices/release-v7.0.x/incentivized-transfer-chain-b.json
- .github/compatibility-test-matrices/release-v7.0.x/transfer-chain-a.json
- .github/compatibility-test-matrices/release-v7.0.x/transfer-chain-b.json
- .github/compatibility-test-matrices/unreleased/client.json
- .github/compatibility-test-matrices/unreleased/connection.json
- .github/mergify.yml
- .github/workflows/e2e-compatibility.yaml
> chore: add compatibility tests for v7.0.x and backport task

- .github/workflows/release.yml
- .github/workflows/test.yml
- Dockerfile
> Update Dockerfile for release/v2.5.x

- .github/workflows/release.yml
> Remove excess quotes from docker build arg

- .github/workflows/release.yml
- .github/workflows/test.yml
- Dockerfile
> Update Dockerfile for release/v2.4.x

- .github/workflows/release.yml
- .github/workflows/test.yml
- Dockerfile
ref: #3068
- This PR: updates Dockerfile for this release branch
- Adds basic test to ensure the image builds (note the ibc-go version specified here doesn't matter as we are just building the image)
- Pass a build arg when we release the image.
N/A
---
> Update Dockerfile for release/v6.1.x

- .github/workflows/e2e-test-workflow-call.yml
- .github/workflows/release.yml
- Dockerfile
Part of #3068
This PR undoes the recent temporary changes to the Dockerfile and allows us to add the ibc-go version as a label. This PR also separates the gorelease task from the publish docker image task as they are not related.
N/A
---
> Fix dockerfile on main

- .github/workflows/e2e-compatibility.yaml
> Ensure we never use the Dockerfile on main when working with other branches

- modules/core/03-connection/keeper/verify.go
closes: #3056 
```bash
chore: retrieve core IBC KVStore for localhost clients
```
---
> chore: retrieve core IBC KVStore for localhost clients

- .github/workflows/release.yml
- .github/workflows/test.yml
- Dockerfile
> Update Dockerfile for release/v3.3.x

- .github/workflows/release.yml
- .github/workflows/test.yml
- Dockerfile
> Update Dockerfile for release/v4.2.x

- .github/workflows/release.yml
- .github/workflows/test.yml
- Dockerfile
> Update Dockerfile for release/v4.1.x

- .github/compatibility-test-matrices/release-v7.0.x/transfer-authz-chain-a.json
- .github/workflows/e2e-compatibility.yaml
- .github/workflows/release.yml
> Add transfer authz tests to workflow

- modules/core/02-client/types/errors.go
- modules/light-clients/09-localhost/client_state.go
> chore: updating errors returns in 09-localhost

- .github/workflows/e2e-fork.yml
> fix docker build for forks

- docs/ibc/light-clients/localhost/client-state.md
> Adding documentation for disabling localhost client

- modules/core/02-client/types/client.pb.go
- modules/core/02-client/types/params.go
- proto/ibc/core/client/v1/client.proto
> chore: update AllowedClients godoc

- modules/core/02-client/types/client.pb.go
Sorry, forgot to rerun make proto-all before merging
closes: #XXXX
```bash
```
---
> chore: make proto-all on 09-localhost branch

- e2e/tests/interchain_accounts/localhost_test.go
- e2e/tests/transfer/localhost_test.go
- e2e/tests/upgrades/upgrade_test.go
- modules/core/02-client/abci.go
- modules/core/02-client/keeper/grpc_query_test.go
- modules/core/02-client/keeper/keeper.go
- modules/core/02-client/keeper/keeper_test.go
- modules/core/02-client/migrations/v7/localhost_test.go
- modules/core/02-client/types/keys.go
- modules/core/03-connection/genesis.go
- modules/core/03-connection/keeper/grpc_query_test.go
- modules/core/03-connection/keeper/keeper.go
- modules/core/03-connection/keeper/keeper_test.go
- modules/core/03-connection/keeper/verify.go
- modules/core/03-connection/migrations/v7/localhost.go
- modules/core/03-connection/types/keys.go
- modules/core/03-connection/types/msgs.go
- modules/core/03-connection/types/msgs_test.go
- modules/core/exported/client.go
- modules/core/exported/connection.go
- modules/light-clients/09-localhost/client_state_test.go
> chore: move localhost client and connection IDs to the exported package

- modules/core/03-connection/keeper/verify.go
> chore: rename getClientStateAndKVStore to getClientStateAndVerificationStore

- testing/simapp/app.go
- testing/simapp/upgrades/upgrades.go
> chore: update localhost upgrade handler to explicitly set allowed clients param

- docs/ibc/light-clients/localhost/client-state.md
This reverts commit 5fa3f331cb6e8f6cb162cbd42fa0a593bb7d4717.
closes: #XXXX
```bash
```
---
> Revert "Adding documentation for disabling localhost client (#3188)"

- modules/core/03-connection/genesis.go
- modules/core/03-connection/keeper/grpc_query_test.go
- modules/core/03-connection/keeper/keeper.go
- modules/core/03-connection/keeper/keeper_test.go
- modules/core/03-connection/migrations/v7/expected_keepers.go
- modules/core/03-connection/migrations/v7/localhost.go
> chore: moving set connection to create localhost sentinel connection

- docs/.vuepress/config.js
- docs/ibc/light-clients/client-state.md
- docs/ibc/troubleshooting.md
- modules/core/02-client/abci.go
- modules/core/02-client/keeper/client.go
- modules/core/02-client/keeper/grpc_query.go
- modules/core/02-client/keeper/keeper.go
- modules/core/02-client/keeper/proposal.go
- modules/core/03-connection/keeper/handshake.go
- modules/core/03-connection/keeper/handshake_test.go
- modules/core/03-connection/keeper/verify.go
- modules/core/03-connection/types/expected_keepers.go
- modules/core/04-channel/keeper/handshake.go
- modules/core/04-channel/keeper/handshake_test.go
- modules/core/04-channel/keeper/packet.go
- modules/core/04-channel/types/expected_keepers.go
- modules/core/exported/client.go
This PR directly replaces #3194
closes: #2537
N/A included in feature branch
---
> Allow disabling of client type via allowed_clients param

- docs/ibc/light-clients/localhost/client-state.md
- modules/light-clients/09-localhost/client_state.go
> chore: client state key nit

- modules/apps/29-fee/ibc_middleware.go
- modules/apps/29-fee/types/expected_keepers.go
closes: #XXXX
```bash
N/A
```
---
> code hygiene: ics-29 improvements

- .gitignore
> chore: add e2e directory to .gitignore for v7.0.x release branch

- .gitignore
> chore: add e2e to .gitignore for v7.1.x

- docs/ibc/events.md
> Fix module name in events doc

- e2e/Makefile
- e2e/README.md
- e2e/scripts/run-e2e.sh
This PR adds one more QOL improvement if `fzf` is installed. If no argument is supplied to `make e2e-test` and `fzf` is installed, you will get a dropdown list of all available tests to select from.
---
> E2E fzf Test Selection Autocompletion

- modules/apps/27-interchain-accounts/controller/ibc_middleware.go
- modules/apps/27-interchain-accounts/host/ibc_module.go
- modules/apps/29-fee/ibc_middleware.go
- modules/apps/transfer/ibc_module.go
- modules/core/05-port/types/module.go
- testing/mock/ibc_module.go
Adding new interface methods and no-op implementations for the apps. These will be fleshed out in a follow up.
---
> Add application interface methods and no-ops

- .github/workflows/e2e-compatibility-workflow-call.yaml
- .github/workflows/e2e-compatibility.yaml
- .github/workflows/e2e-test-workflow-call.yml
- .github/workflows/e2e.yaml
While preparing for the E2E deep dive, I wanted to add additional clarification to what each of the workflows are doing.
---
> Add more detailed explanations to  e2e workflows

- modules/core/04-channel/keeper/grpc_query.go
Addressing comment made here: https://github.com/cosmos/ibc-go/pull/3357#discussion_r1152041510
closes: #XXXX
```bash
nit: Adjust `NextSequenceReceive` to work with a potential `ORDERED_ALLOW_TIMEOUT` channel.
```
---
> nit: Adjust `NextSequenceReceive` to work with a potential `ORDERED_ALLOW_TIMEOUT` channel.

- e2e/tests/core/client_test.go
- e2e/testsuite/grpc_query.go
should help resolve the backwards compatibility issue pointed out in #3440
---
> Adding header interface for backwards compatibility

- .github/workflows/e2e-upgrade.yaml
> chore: update tags for v7.1 upgrade test

- modules/core/03-connection/types/version.go
> Use generic `Contains` function in `03-connection`

- docs/requirements/channel-upgradability-requirements.md
This PR adds sample flows for the different use cases of channel upgradability. 
closes: #XXXX
```bash
```
---
> usecase flows for channel upgradability

- go.mod
- go.sum
- testing/simapp/simd/cmd/root.go
- Removes the `simd testnet` cmd and the `cosmossdk.io/simapp` dependency
closes: #3545 
```bash
chore: remove simd testnet cmd and cosmossdk.io/simapp dependency
```
---
> chore: remove simd testnet cmd and cosmossdk.io/simapp dependency

- modules/core/24-host/channel_keys.go
closes: #3670
N/A feature branch
---
> 24-host packet keys for channel counterparty last sequence path

- modules/core/04-channel/keeper/keeper.go
- modules/core/24-host/channel_keys.go
> Getter and setter methods in the 04-channel keeper for channel counterparty last sequence

- testing/config.go
- testing/endpoint.go
closes: #3716 
```bash
```
---
> imp: update endpoint.ChanUpgradeInit to create upgrade proposal from endpoint config

- .github/compatibility-test-matrices/release-v6.2.x/transfer-authz-chain-a.json
- .github/compatibility-test-matrices/release-v6.2.x/transfer-authz-chain-b.json
> e2e: add missing authz tests for v6.2.x

- modules/core/04-channel/keeper/events.go
Adds the flush status to the events emitted.
closes: #XXXX
```bash
Add the FlushStatus to the events emitted.
```
---
> Add the FlushStatus to the events emitted.

- modules/core/24-host/channel_keys.go
- modules/core/24-host/packet_keys.go
This fella was probably missed in the PR that split the keys, moved in the correct spot.
closes: #XXXX
```bash
chore: move capability key to channel_keys
```
---
> Move KeyChannelCapabilityPrefix to channel_keys.

- proto/ibc/core/channel/v1/tx.proto
It really do be like that
closes: #XXXX
---
> nit: fix spacing in protobuf formatting

- testing/endpoint.go
closes: #3755 
```bash
Add endpoint.ChanUpgradeCancel.
```
---
> Add endpoint.ChanUpgradeCancel.

- e2e/testconfig/testconfig.go
- testing/simapp/simd/cmd/genaccounts.go
- testing/simapp/simd/cmd/genaccounts_test.go
- testing/simapp/simd/cmd/root.go
> Revert "Remove simd gen accounts command in favor of SDK command"

- .golangci.yml
Disable if-return linter config to allow explicit `nil` error returns such as:
```go
func foo() error {
if err := bar(); err != nil {
return err
}
return nil
}
```
---
> chore: adding exception to linter config for revive if-return

- modules/core/keeper/msg_server_test.go
Error receipts are now written on `AbortUpgrade` as #3649 is merged.
closes: #XXXX
---
> chore: address testcase todos in `TestChannelUpgradeTry`

- Dockerfile
corresponding PR as the one on `main`
---
> bump ubuntu image to update `libc` version

- RELEASES.md
> chore: update end-of-life dates

- go.mod
> retract previous v7 releases with ledger transaction signing bug

- modules/apps/27-interchain-accounts/controller/types/msgs_test.go
- modules/apps/27-interchain-accounts/types/codec_test.go
- testing/app.go
- testing/simapp/app.go
- testing/simapp/params/encoding.go
- testing/simapp/params/proto.go
- testing/simapp/simd/cmd/root.go
- testing/simapp/test_helpers.go
This PR changes Marshaler to Codec
> style: change marshaler to codec

- .github/workflows/e2e.yaml
- Add relayer output to e2e workflow yaml
closes: #XXXX
---
> fix: add relayer as an output in e2e workflow

- README.md
- docs/.vuepress/config.js
Change IBC/go contributors read me, and changed IBC/go docs vuepress.js old dead links to https://discord.gg/cosmosnetwork
---
Note: Ensuring that old discord links are up to date for security purposes. Many checklist items not relevant to such changes
> Discord Security Patch 

- .golangci.yml
this was removed from main in #3809, removing from 04-channel-upgrades to align linting.
(the larger linting changes can happen in a follow up maybe after the SDK 50 work)
---
> Remove depguard from golangci-lint

- modules/core/02-client/keeper/keeper_test.go
I believe this test was added because originally each submodule had their own custom testing pkg. When the custom testing pkg's were merged into one (now the ibc testing pkg), this test should have been deleted. It doesn't appear to be testing any functionality anymore. I think it was originally added to test the helper functions which I think so of which were removed. [Here](https://github.com/cosmos/cosmos-sdk/pull/5277/files#diff-88bc3fba8386309048a6f9227eed961c48a79438bb424645521ba77133ab51e0R156) is how it looked originally. 
This is causing testing failures in #3883 
closes: #XXXX
```bash
```
---
Before …
> chore: remove unnecessary test

- modules/core/04-channel/keeper/export_test.go
- modules/core/04-channel/keeper/upgrade.go
- modules/core/04-channel/keeper/upgrade_test.go
closes: #3764
This PR adds helpers to handle validation using the naming conventions outlined in the referenced issue.
---
> helper function for validating a counterparty upgrade against the selfupgrade

- .github/workflows/e2e.yaml
- .github/workflows/test.yml
Don't hardcode the arch when building e2es/tests.
closes: #XXXX
```bash
```
---
> Use native arch.

- docs/migrations/v7-to-v7_1.md
closes: https://github.com/cosmos/ibc-go/issues/3263
```bash
```
---
> chore: update links in migration docs

- modules/core/04-channel/keeper/keeper.go
Just a small code hygiene fix.
closes: #XXXX
```bash
```
---
> chore: replace with new errors package

- Makefile
- docs/dev/development-setup.md
- scripts/hooks/pre-commit.sh
closes: #3048
In order to configure the linter, everyone must run
```bash
make setup-pre-commit
```
This will create a symlink so that in the future we just need to modify the newly added script.
This script ensures we can't commit linted files that are out of sync with our CI. 
It will then only run the linter on any modified files.
N/A Dev improvement
---
> Create pre-commit hook to run golangci-lint

- .github/mergify.yml
Adding capability release branch to mergify backport actions
---
> chore: adding capability/release/v1.0.x backport action to mergify.yml

- Dockerfile
- e2e/go.mod
- e2e/go.sum
- go.mod
- go.sum
- modules/light-clients/08-wasm/go.mod
- modules/light-clients/08-wasm/go.sum
> bump wasmvm

- .github/workflows/wasm-client.yml
- .gitignore
On PR, if a wasm light client directory is modified, build and test it. Only run for amd64 since wasmvm does not support arm.
closes: #4027
```bash
```
---
> build and test wasm client on PR

- modules/light-clients/08-wasm/keeper/keeper.go
- testing/simapp/app.go
Passes through the authority address string properly to the NewKeeper for 08-wasm client.
closes: #3990 
```bash
```
---
> add `authority` parameter to 08-wasm `NewKeeper`

- testing/solomachine.go
fix needed for #3883, pulling out to reduce diffs 
```bash
```
---
> test: update solomachine event parsing

- modules/apps/29-fee/ibc_middleware.go
Adding comment for passthrough to underlying app in `OnChanUpgradeOpen` for `29-fee`, as no action is required by the fee module here.
---
> chore: add comment to `OnChanUpgradeOpen` for `29-fee`

- modules/core/04-channel/keeper/upgrade_test.go
Similar to #4076 
closes: #XXXX
```bash
```
---
> Add tests for WriteUpgradeOpenChannel.

- .github/workflows/callbacks.yml
Splitting to different mod => requires separate workflow.
cc @charleenfei 
closes: #XXXX
```bash
chore: add workflow file for callbacks module
```
---
> Add workflow file for callbacks module

- modules/core/04-channel/keeper/keeper.go
closes: #XXXX
```bash
chore: remove superfluous ignore directive.
```
---
> Remove superfluous ignore directive from HasInflightPackets.

- modules/core/04-channel/keeper/grpc_query.go
I added the check, but didn't change the tests to check for the error returned. There is another issue to change that in the existing tests.
ref: https://github.com/cosmos/ibc-go/issues/4140
```bash
```
---
> add check that channel exists in upgrade gRPCs

- modules/core/04-channel/keeper/upgrade.go
Some small improvements to error strings.
closes: #XXXX
```bash
```
---
> nit: error formatting improvements for channel upgrades

- modules/core/04-channel/keeper/upgrade_test.go
closes: #4225
N/A Feature Branch
---
> Add test for event emission ChanUpgradeTry

- modules/core/04-channel/keeper/packet.go
- modules/core/04-channel/keeper/timeout.go
Some places were missed in https://github.com/cosmos/ibc-go/pull/4155.
closes: #XXXX
```bash
```
---
> chore: use channel's `IsOpen` method

- go.work.example
When I added callbacks to go.work.example, I made a typo and wrote applications when I should have written apps.  This pr corrects that. 
```bash
fix: correct applications -> apps
```
---
> fix: correct applications -> apps

- e2e/dockerutil/dockerutil.go
- e2e/relayer/relayer.go
- e2e/tests/core/02-client/client_test.go
- e2e/tests/core/03-connection/connection_test.go
- e2e/tests/interchain_accounts/base_test.go
- e2e/tests/interchain_accounts/gov_test.go
- e2e/tests/interchain_accounts/groups_test.go
- e2e/tests/interchain_accounts/incentivized_test.go
- e2e/tests/interchain_accounts/intertx_incentivized_test.go
- e2e/tests/interchain_accounts/intertx_test.go
- e2e/tests/interchain_accounts/localhost_test.go
- e2e/tests/interchain_accounts/params_test.go
- e2e/tests/transfer/authz_test.go
- e2e/tests/transfer/incentivized_test.go
- e2e/tests/upgrades/upgrade_test.go
- e2e/testsuite/diagnostics/diagnostics.go
- e2e/testsuite/grpc_query.go
- e2e/testsuite/testsuite.go
- e2e/testvalues/values.go
- modules/apps/callbacks/callbacks_test.go
- modules/apps/callbacks/go.mod
- modules/apps/callbacks/ibc_middleware_test.go
- modules/apps/callbacks/types/events_test.go
Adds latest commits from main. In addition fixes github render issue when you squash merge updates to a feature branch (forgot to not squash when merging latest chanes)
closes: #XXXX
```bash
```
---
> deps: bump sdk v0.50 feature branch with changes from main

- modules/core/keeper/msg_server.go
> feat: add logging for noop messages

- modules/core/04-channel/keeper/upgrade_test.go
> chore: re-enable disabled testcase in `chanUpgradeTry`

- modules/apps/29-fee/ibc_middleware.go
- modules/apps/29-fee/ibc_middleware_test.go
> refactor: fee middleware onChanUpgradeInit callback

- modules/apps/29-fee/ibc_middleware.go
- modules/apps/29-fee/ibc_middleware_test.go
> refactor: fee middleware onChanUpgradeTry callback

- modules/apps/callbacks/go.mod
Cloning simapp caused some indirect imports to become direct. This need not be backported as I ran `go mod tidy` when switching from local pin to `v7.3.0-rc1`.
closes: #XXXX
```text
deps(callbacks): ran 'go mod tidy'
```
---
> deps(callbacks): ran 'go mod tidy'

- e2e/testsuite/grpc_query.go
> fix: e2e `TestClient_Update_Misbehaviour` test with v4

- modules/apps/callbacks/go.mod
- modules/apps/callbacks/go.sum
> deps: update ibc go dependency

- modules/core/02-client/client/cli/cli.go
- modules/core/02-client/client/cli/tx.go
> add cli for MsgIBCSoftwareUpgrade

- modules/light-clients/08-wasm/client/cli/cli.go
- modules/light-clients/08-wasm/client/cli/tx.go
closes: #4202 
```bash
```
---
> Add new cmd to store code via a gov proposal.

- .golangci.yml
Make the wasm clients linter exactly match main.
```bash
ci: make wasm clients linter exactly match main
```
---
> ci: update wasm clients linter

- e2e/tests/core/02-client/client_test.go
- e2e/tests/core/03-connection/connection_test.go
- e2e/tests/interchain_accounts/gov_test.go
- e2e/tests/interchain_accounts/params_test.go
- e2e/tests/transfer/base_test.go
- e2e/tests/upgrades/upgrade_test.go
- e2e/testsuite/grpc_query.go
- e2e/testsuite/tx.go
Rename the governance test functions to make them more explicit.
It currently sounds as if the v1beta proposal is the "standard" proposal.
---
> Rename test functions to make them more explicit

- modules/light-clients/08-wasm/module.go
- modules/light-clients/08-wasm/simulation/proposals.go
- modules/light-clients/08-wasm/simulation/proposals_test.go
> feat: add proposal simulator interface function and tests

- modules/apps/27-interchain-accounts/module.go
- modules/apps/29-fee/module.go
- modules/apps/transfer/module.go
- modules/core/module.go
Adds compiler assertions for the functions which implement module interfaces
closes: #XXXX
```bash
```
---
> chore: add module.go compiler assertions

- Dockerfile
> chore: bump ubuntu version

- .github/workflows/deploy-docs.yml
closes: #XXXX
```text
ci: fix deploy-docs action
```
---
> ci: fix deploy-docs action

- docs/ibc/upgrades/genesis-restart.md
- docs/ibc/upgrades/quick-guide.md
- docs/migrations/sdk-to-v1.md
- docs/migrations/v3-to-v4.md
> chore: fix links v4.5.x

- CHANGELOG.md
- go.mod
- go.sum
Not strictly necessary for v4.5, though.
closes: #XXXX
```text
```
---
> deps: bump SDK v0.45.16

- .github/compatibility-test-matrices/release-v4.5.x/incentivized-transfer-chain-a.json
- .github/compatibility-test-matrices/release-v4.5.x/incentivized-transfer-chain-b.json
- .github/compatibility-test-matrices/release-v4.5.x/transfer-chain-a.json
- .github/compatibility-test-matrices/release-v4.5.x/transfer-chain-b.json
- .github/compatibility-test-matrices/unreleased/client.json
- .github/compatibility-test-matrices/unreleased/connection.json
- .github/compatibility-test-matrices/unreleased/incentivized-transfer-1.json
- .github/compatibility-test-matrices/unreleased/incentivized-transfer-2.json
- .github/compatibility-test-matrices/unreleased/incentivized-transfer-3.json
- .github/compatibility-test-matrices/unreleased/transfer-1.json
- .github/compatibility-test-matrices/unreleased/transfer-2.json
- .github/compatibility-test-matrices/unreleased/transfer-3.json
- .github/mergify.yml
- .github/workflows/e2e-compatibility-unreleased.yaml
- .github/workflows/e2e-compatibility.yaml
> chore: mergify task and e2e tests for v4.5.x

- modules/light-clients/08-wasm/keeper/keeper.go
- modules/light-clients/08-wasm/keeper/keeper_test.go
- modules/light-clients/08-wasm/module.go
- modules/light-clients/08-wasm/types/update.go
> test: check nil vm and empty authority

- modules/light-clients/08-wasm/types/vm.go
closes: #3991 
```text
```
---
> docs: add extra documentation to `wasmCall` and `wasmQuery` functions

- modules/apps/29-fee/types/codec.go
godocs refer to transfer instead of 29-fee
closes: #XXXX
```text
docs(fee): fixed fee ModuleCdc's godocs
```
---
> docs(fee): fixed fee ModuleCdc's godocs

- modules/core/02-client/types/events.go
- modules/light-clients/08-wasm/keeper/events.go
- modules/light-clients/08-wasm/keeper/msg_server_test.go
- modules/light-clients/08-wasm/types/config.go
- modules/light-clients/08-wasm/types/events.go
> chore: add 08-wasm events

- e2e/go.mod
- e2e/go.sum
- go.mod
- go.sum
- modules/apps/callbacks/go.mod
- modules/apps/callbacks/go.sum
> deps: bump mod/capability to v1.0.0-rc6

- .github/workflows/e2e-upgrade.yaml
Seems like the way we were referencing these was off. Docs: https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow
closes: #XXXX
```text
chore: fix e2e-upgrade.yaml parsing issue
```
---
> Fix e2e-upgrade.yaml complaint.

- modules/light-clients/08-wasm/go.mod
fixes a couple of indirect imports to direct.
closes: #XXXX
```text
chore: run go mod tidy on 08-wasm go.mod
```
---
> Go mod tidy on 08-wasm

- modules/apps/27-interchain-accounts/controller/types/codec_test.go
- modules/apps/27-interchain-accounts/host/types/codec_test.go
- modules/apps/29-fee/types/codec_test.go
- modules/apps/transfer/types/codec_test.go
addresses the app part of the coedc tests
ref: #4747
```text
```
---
> Add codec registrations tests for apps

- modules/capability/keeper/keeper.go
this should save a tiny bit of gas afaik.
closes: #XXXX
```text
imp(statemachine)!: reduce gas consumption for capability IsInitialized call
```
---
> Save gas on capability IsInitialized call

- .github/workflows/build-wasm-simd-image-from-tag.yml
similar to workflow added for callbacks.
closes: #XXXX
```text
```
---
> Add workflow to build image for 08-wasm

- docs/docs/02-apps/02-interchain-accounts/05-messages.md
- docs/docs/05-migrations/04-v2-to-v3.md
- docs/versioned_docs/version-v4.4.x/02-apps/02-interchain-accounts/06-transactions.md
- docs/versioned_docs/version-v4.4.x/04-migrations/04-v2-to-v3.md
- docs/versioned_docs/version-v5.3.x/02-apps/02-interchain-accounts/06-transactions.md
- docs/versioned_docs/version-v5.3.x/04-migrations/04-v2-to-v3.md
- docs/versioned_docs/version-v6.2.x/02-apps/02-interchain-accounts/05-messages.md
- docs/versioned_docs/version-v6.2.x/04-migrations/04-v2-to-v3.md
- docs/versioned_docs/version-v7.3.x/02-apps/02-interchain-accounts/05-messages.md
- docs/versioned_docs/version-v7.3.x/05-migrations/04-v2-to-v3.md
> docs: fix broken SDK links

- modules/light-clients/08-wasm/keeper/keeper_test.go
- modules/light-clients/08-wasm/testing/simapp/export.go
- modules/light-clients/08-wasm/types/store.go
- modules/light-clients/08-wasm/types/types_test.go
- modules/light-clients/08-wasm/types/vm.go
uber nit raised in walkthrough of 08-wasm
closes: #XXXX
```text
nit: panic with errors
```
---
> Use an error when panicking.

- modules/light-clients/08-wasm/keeper/keeper.go
- modules/light-clients/08-wasm/types/expected_interfaces.go
- modules/light-clients/08-wasm/types/vm.go
closes: #4797 
```text
```
---
> imp: use interface instead of concrete type for wasmvm

- modules/light-clients/08-wasm/types/client_state.go
- modules/light-clients/08-wasm/types/contract_api.go
- modules/light-clients/08-wasm/types/proposal_handle.go
- modules/light-clients/08-wasm/types/update.go
- modules/light-clients/08-wasm/types/upgrade.go
- modules/light-clients/08-wasm/types/vm.go
Adding the `needs discussion` label to discuss if we don't see any possibility of using these fields the future so that we can safely remove them now.
closes: #4179 
```text
```
---
> imp: remove unused fields, functions of contract result

- Dockerfile
Should be able to clean this up now that branch has been synced.
closes: #4743 
```text
```
---
> Dont pull wasmvm static lib in simd dockerfile.

- .github/workflows/test.yml
Removes the wasm additions made in test.yaml, should be able to be removed now that dep has been removed, should require removal of wasmvm static linking in Dockerfile tho.
closes: #4778 
```text
```
---
> Remove wasm additions to main test workflow.

- modules/light-clients/08-wasm/testing/wasm_endpoint.go
- modules/light-clients/08-wasm/types/types_test.go
closes: #4849 
```text
```
---
> Store code before creating a wasm client.

- modules/light-clients/08-wasm/types/codec_test.go
closes: #4747 
```text
```
---
> Add test for types registered in 08-wasm.

- modules/light-clients/08-wasm/types/client_state_test.go
- modules/light-clients/08-wasm/types/types_test.go
removing a const that isn't required, also an import was apparently missing in that file.
closes: #XXXX
```text
```
---
> Remove codeHash const from types_test, use wasmtesting.

- modules/light-clients/08-wasm/types/export_test.go
- modules/light-clients/08-wasm/types/msgs.go
- modules/light-clients/08-wasm/types/msgs_test.go
and some tests for it. Also, address wasn't validated in ValidateBasic.
closes: #XXXX
```text
```
---
> Add checks in ValidateBasic for StoreCode

- modules/light-clients/08-wasm/types/export_test.go
- modules/light-clients/08-wasm/types/mock_engine_test.go
second part of #4873 cc @chatton 
closes: #XXXX
```text
```
---
> Add mapping for sudo payloads callbacks in mockVM

- modules/light-clients/08-wasm/types/client_state_test.go
This covers the case, unsure if people wanted a dedicated function tho
closes: #4838 
```text
```
---
> Add test case for invalid Initialize call due to unstored contract.

- modules/light-clients/08-wasm/types/export_test.go
These response types are useful when generating mock callbacks
closes: #XXXX
```text
imp(08-wasm): exported contract responses to tests
```
---
> imp(08-wasm): exported contract responses to tests

- modules/light-clients/08-wasm/types/misbehaviour_handle.go
closes: #4905 
```text
fix(08-wasm): removed panic in `CheckForMisbehaviour`
```
---
> fix(08-wasm): removed panic in `CheckForMisbehaviour`

- modules/light-clients/08-wasm/types/client_state_test.go
- modules/light-clients/08-wasm/types/types_test.go
follow up to #4902 
closes: #XXXX
```text
```
---
> Use the Response types in TestStatus.

- modules/light-clients/08-wasm/types/msgs.go
- modules/light-clients/08-wasm/types/msgs_test.go
https://github.com/cosmos/ibc-go/issues/4687 for 08-wasm.
closes: #XXXX
```text
```
---
> Remove GetSigners from StoreCode msg.

- modules/light-clients/08-wasm/types/client_state.go
- modules/light-clients/08-wasm/types/contract_api.go
- modules/light-clients/08-wasm/types/export_test.go
- modules/light-clients/08-wasm/types/genesis.go
- modules/light-clients/08-wasm/types/misbehaviour_handle.go
- modules/light-clients/08-wasm/types/mock_engine_test.go
- modules/light-clients/08-wasm/types/proposal_handle.go
- modules/light-clients/08-wasm/types/update.go
- modules/light-clients/08-wasm/types/upgrade.go
- modules/light-clients/08-wasm/types/vm.go
> chore: make wasm contract api exported

- docs/docusaurus.config.js
- docs/package-lock.json
- docs/package.json
addresses: #4932 
```text
docs: add google analytics 4 support
```
---
> docs: add google analytics 4 support

- docs/docusaurus.config.js
- docs/package-lock.json
- docs/package.json
adresses: #4932 
```text
docs: add microsoft clarity support
```
---
> docs: add microsoft clarity support

- modules/light-clients/08-wasm/types/upgrade_test.go
closes: #4832 
```text
```
---
> Add mock test for VerifyUpgradeAndUpdateState

- modules/light-clients/08-wasm/types/client_state_test.go
Adds tests for `VerifyNonMembership` using mock wasm vm. 
closes: #4827 
---
> test: adding `VerifyNonMembership` tests with mock wasm engine

- modules/light-clients/08-wasm/keeper/genesis.go
- modules/light-clients/08-wasm/keeper/genesis_test.go
- modules/light-clients/08-wasm/keeper/grpc_query.go
- modules/light-clients/08-wasm/keeper/keeper.go
- modules/light-clients/08-wasm/types/types_test.go
- modules/light-clients/08-wasm/types/wasm.go
- modules/light-clients/08-wasm/types/wasm_test.go
closes: https://github.com/cosmos/ibc-go/issues/4947
```text
imp(08-wasm): removed panic in `GetCodeHash` and `AddCodeHash`
```
---
> imp(08-wasm): removed panic in `GetCodeHash` and `AddCodeHash`

- modules/light-clients/08-wasm/testing/wasm_endpoint.go
- modules/light-clients/08-wasm/types/client_state_test.go
- modules/light-clients/08-wasm/types/misbehaviour_handle_test.go
- modules/light-clients/08-wasm/types/update_test.go
- modules/light-clients/08-wasm/types/upgrade_test.go
Adds this error which is re-used for the testing funcs.
closes: #XXXX
```text
chore: add ErrMockContract to testing.
```
---
> Add ErrMockContract.

- modules/light-clients/08-wasm/types/client_state_test.go
Appears this isn't tested for 07-tendermint and as such tests were not added for 08-wasm.
closes: #XXXX
```text
```
---
> Add test for GetTimestampAtHeight

- e2e/tests/transfer/base_test.go
- e2e/testvalues/values.go
> chore: remove redundant code asserting token metadata

- modules/light-clients/08-wasm/testing/mock_engine.go
- modules/light-clients/08-wasm/types/client_state_test.go
- modules/light-clients/08-wasm/types/genesis_test.go
- modules/light-clients/08-wasm/types/misbehaviour_handle_test.go
- modules/light-clients/08-wasm/types/types_test.go
- modules/light-clients/08-wasm/types/update_test.go
- modules/light-clients/08-wasm/types/upgrade_test.go
closes: #4929 
```text
chore: move mock engine into testing folder
```
---
> Move mock engine into testing.

- modules/apps/27-interchain-accounts/host/types/codec.go
checked other modules, host appears to be the only other one where this registration didn't happen.
closes: #XXXX
```text
chore: register message service descriptor for ica/host
```
---
> Register message service descriptor for host

- modules/light-clients/08-wasm/types/client_state_test.go
- modules/light-clients/08-wasm/types/errors.go
- modules/light-clients/08-wasm/types/export_test.go
- modules/light-clients/08-wasm/types/genesis_test.go
- modules/light-clients/08-wasm/types/misbehaviour_handle_test.go
- modules/light-clients/08-wasm/types/update_test.go
- modules/light-clients/08-wasm/types/upgrade_test.go
- modules/light-clients/08-wasm/types/vm.go
- modules/light-clients/08-wasm/types/vm_test.go
closes: #4931 
```text
```
---
> Add testing for wasmQuery/wasmCall.

- modules/light-clients/08-wasm/keeper/keeper.go
- modules/light-clients/08-wasm/types/proposal_handle.go
- modules/light-clients/08-wasm/types/store.go
- modules/light-clients/08-wasm/types/update_test.go
- modules/light-clients/08-wasm/types/vm.go
Ref: https://github.com/cosmos/ibc-go/pull/4934#discussion_r1375906537
closes: #XXXX
```text
chore: do not call Wrapf when not required.
```
---
> No formatting necessary.

- modules/capability/capability_test.go
- modules/capability/keeper/keeper_test.go
- modules/capability/module.go
- modules/capability/simulation/decoder_test.go
closes: #4655
```text
removing appmodulebasic and all nil/unneeded functions from capability
```
---
> removing AppModuleBasic from Capability

- modules/light-clients/08-wasm/keeper/genesis.go
- modules/light-clients/08-wasm/keeper/genesis_test.go
- modules/light-clients/08-wasm/keeper/snapshotter.go
- modules/light-clients/08-wasm/types/wasm.go
- modules/light-clients/08-wasm/types/wasm_test.go
> chore: adding type alias for code hash byte slices

- modules/light-clients/08-wasm/go.mod
- modules/light-clients/08-wasm/types/gas_register.go
- modules/light-clients/08-wasm/types/gas_register_custom.go
- modules/light-clients/08-wasm/types/vm.go
Our `gas_register.go` was created pre sdk 0.50 and is out of sync with wasmd's.
This PR does the following:
- Do a direct copy paste of [gas_register.go](https://github.com/CosmWasm/wasmd/blob/main/x/wasm/types/gas_register.go) and paste it into ibc-go.
- Pull the additional constructs we had been making use of into `gas_register_custom.go`. Note, these seem to be primarily functions that exist as keeper functions in wasmd but have been refactored slightly to remove the dependency on the keeper. E.g. [this](https://github.com/CosmWasm/wasmd/blob/e65480838a1ded147ef53d35fa3bd9709a61226f/x/wasm/keeper/keeper.go#L1100) keeper fn now looks like [this](https://github.com/cosmos/ibc-go/blob/28f9ad7ef224242b389414f56eca4b809a0a099b/modules/light-clients/08-wasm/types/gas_register_custom.go#L27). …
> Sync gas_register.go with wasmd main

- modules/light-clients/08-wasm/internal/ibcwasm/expected_interfaces.go
- modules/light-clients/08-wasm/keeper/keeper_test.go
- modules/light-clients/08-wasm/testing/mock_engine.go
- modules/light-clients/08-wasm/types/client_state_test.go
- modules/light-clients/08-wasm/types/migrate_contract_test.go
- modules/light-clients/08-wasm/types/types_test.go
- modules/light-clients/08-wasm/types/wasm.go
I kept [`checksum` in `MsgStoreCodeResponse`](https://github.com/cosmos/ibc-go/blob/147f0ca392831ee2cb46a1c6db9dabc3a9199b14/proto/ibc/lightclients/wasm/v1/tx.proto#L32) though. If someone feels strongly about it I can also rename it.
closes: #4852 
```text
```
---
> chore: rename code ID/checksum to code hash

- modules/core/02-client/keeper/client.go
```
client recovery failed: substitute client is not Expired, status is Active: client state is not active: failed waiting for condition after 300.000000 seconds
```
---
> fix: correct error formatting in client status check in client recovery

- .github/workflows/build-wasm-simd-image-from-tag.yml
- .github/workflows/wasm-client.yml
Takes care of #5114, #5115 and #5116 in a single PR.
closes: #XXXX
```text
deps: bump outdated actions for 08-wasm
```
---
> Bump all dependabot actions.

- modules/light-clients/08-wasm/testing/wasm_endpoint.go
- modules/light-clients/08-wasm/types/client_state_test.go
- modules/light-clients/08-wasm/types/consensus_state.go
- modules/light-clients/08-wasm/types/consensus_state_test.go
See [this comment](https://github.com/cosmos/ibc-go/pull/5154#discussion_r1401484789)
```text
nit(08-wasm): removed unused param from 'NewConsensusState'
```
---
> nit(08-wasm): removed unused param from 'NewConsensusState'

- modules/capability/module.go
- modules/core/04-channel/keeper/timeout.go
Someone (me 😄 ) snuck a dummy error through into the feature branch, this PR fixes it.
---
> Remove dummy error

- modules/core/04-channel/keeper/upgrade.go
> Remove incorrect godoc

- modules/core/04-channel/keeper/upgrade.go
> Return correct error

- modules/core/04-channel/keeper/upgrade.go
> Add comment about partially formed upgrade

- modules/core/04-channel/keeper/upgrade.go
> Add comment when setting the version to counterparty version

- modules/core/04-channel/keeper/upgrade.go
> Chore: replace `fmt.Sprintf` with `fmt.Errorf` in `upgrades.go`

- .github/workflows/e2e-fork.yml
- .github/workflows/e2e-upgrade.yaml
- .github/workflows/e2e.yaml
Pasted the incorrect string!
---
> fix: update incorrect test suite string in test exclusions

- docs/architecture/adr-003-ics27-acknowledgement.md
- docs/architecture/adr-009-v6-ics27-msgserver.md
- docs/dev/development-setup.md
- docs/docs/02-apps/02-interchain-accounts/09-active-channels.md
- docs/versioned_docs/version-v4.5.x/02-apps/02-interchain-accounts/03-active-channels.md
- docs/versioned_docs/version-v5.3.x/02-apps/02-interchain-accounts/03-active-channels.md
- docs/versioned_docs/version-v6.2.x/02-apps/02-interchain-accounts/08-active-channels.md
- docs/versioned_docs/version-v7.3.x/02-apps/02-interchain-accounts/09-active-channels.md
- docs/versioned_docs/version-v8.0.x/02-apps/02-interchain-accounts/09-active-channels.md
- modules/core/04-channel/types/acknowledgement.go
when reading the document, I found some spelling errors, mainly 
- determinstic
- programatically
I have done a search and replace in the whole repo~
```text
```
---
> docs: fix typos

- modules/core/02-client/types/params.go
- modules/core/02-client/types/params_test.go
Check if clients params are duplicates.
closes: #XXXX
```text
imp(statemachine)!: check if there are duplicate client types in allowed clients param
```
---
> imp: check if clients params are duplicates

- modules/light-clients/08-wasm/go.mod
- modules/light-clients/08-wasm/go.sum
- modules/light-clients/08-wasm/keeper/msg_server_test.go
- modules/light-clients/08-wasm/testing/mock/mock.go
- modules/light-clients/08-wasm/testing/utils.go
- modules/light-clients/08-wasm/testing/values.go
- modules/light-clients/08-wasm/types/client_state_test.go
> 08-wasm: pin ibc-go v7.3

- docs/docs/03-light-clients/04-wasm/03-integration.md
- docs/docs/03-light-clients/04-wasm/05-governance.md
closes: #5383 
```text
docs: added docs on 08-wasm options api
```
---
> docs: added docs on 08-wasm options api

- docs/architecture/README.md
original md link relative path is wrong
```text
```
---
> docs:fix link jump

- docs/docusaurus.config.js
- docs/package-lock.json
- docs/package.json
You can find the sitemap for the website in `https://ibc.cosmos.network/sitemap.xml` once this is merged.
closes: #5520 
```text
docs: added sitemap support to docs
```
---
> docs: added sitemap support to docs

- modules/apps/27-interchain-accounts/controller/keeper/handshake.go
- modules/apps/27-interchain-accounts/controller/keeper/handshake_test.go
closes: #5523
I also did a small refactor of the test to check for specific errors. Hopefully it doesn't bloat the PR too much!
---
> When a channel reopens the ordering and metadata must not change

- modules/light-clients/08-wasm/module.go
The tx CLI command for 08-wasm was missing. I will tag a v0.1.1 release together with the batch of ibc-go releases at the end of the month.
cc: @Farhad-Shabani
closes: #XXXX
```text
```
---
> fix: register wasm tx cli

- docs/docs/02-apps/02-interchain-accounts/08-client.md
I noticed we were missing CLI docs for `register`, so I added them and included information about the `--ordering` flag.
closes: #XXXX
```text
```
---
> docs: ICA register CLI

- modules/apps/27-interchain-accounts/host/keeper/handshake_test.go
> fix ICA host chan open try test

- docs/docs/02-apps/01-transfer/01-overview.md
- docs/versioned_docs/version-v8.0.x/02-apps/01-transfer/01-overview.md
closes: #5579 
```text
docs: added docs on denom metadata
```
---
> docs: added docs on denom metadata

- modules/core/02-client/keeper/client_test.go
- modules/core/02-client/types/msgs_test.go
- modules/core/genesis_test.go
- modules/core/keeper/msg_server_test.go
- modules/light-clients/07-tendermint/misbehaviour_handle_test.go
- modules/light-clients/07-tendermint/store_test.go
- modules/light-clients/07-tendermint/update_test.go
- testing/chain.go
- testing/coordinator.go
- testing/endpoint.go
> rename currentheader to proposedheader

- docs/docs/01-ibc/06-channel-upgrades.md
> Adding note about new channel states

- modules/core/04-channel/types/msgs_test.go
- modules/core/integration_test.go
I have submitted this PR to fix spelling errors in code comments.
> chore: Fixed typos in the 'modules' folder

- modules/apps/callbacks/testing/simapp/app.go
- modules/core/02-client/keeper/keeper.go
- modules/core/02-client/types/router.go
- modules/core/02-client/types/store.go
- modules/core/exported/client.go
- modules/core/keeper/keeper.go
- modules/light-clients/06-solomachine/internal/keeper/keeper.go
- modules/light-clients/06-solomachine/light_client_module.go
- modules/light-clients/07-tendermint/internal/keeper/keeper.go
- modules/light-clients/07-tendermint/light_client_module.go
- modules/light-clients/08-wasm/keeper/keeper.go
- modules/light-clients/08-wasm/keeper/options.go
- modules/light-clients/08-wasm/light_client_module.go
- modules/light-clients/08-wasm/testing/simapp/app.go
- modules/light-clients/09-localhost/internal/keeper/keeper.go
- modules/light-clients/09-localhost/light_client_module.go
- testing/simapp/app.go
Adds a nice slim interface with a single method `ClientStore` for light client modules to retrieve a prefixed client store.
---
> feat: add ClientStoreProvider interface for isolated prefix stores

- docs/docs/05-migrations/13-v8-to-v9.md
- modules/apps/27-interchain-accounts/controller/keeper/handshake.go
- modules/apps/27-interchain-accounts/types/metadata.go
- modules/core/03-connection/keeper/verify.go
- modules/core/03-connection/types/connection.go
- modules/core/04-channel/keeper/handshake.go
- modules/core/04-channel/keeper/timeout.go
- modules/core/04-channel/keeper/upgrade.go
> refactor!: remove unnecessary getters on counterparty connection type

- RELEASES.md
> fix: broken link

- .github/mergify.yml
> chore: add mergify backport for v8.2.x

- modules/core/02-client/types/store.go
> 02-client routing: function in store provider to return client store

- modules/core/02-client/keeper/grpc_query.go
- modules/core/02-client/keeper/grpc_query_test.go
Adds client status check to `VerifyMembership` rpc.
Adds tests.
closes: #5847 
---
> chore: add client status check to verify membership rpc

- modules/core/02-client/keeper/grpc_query.go
- modules/core/02-client/keeper/grpc_query_test.go
Deny `Localhost` and `Solomachine` clients from `VerifyMembership` rpc handler
closes: #5848
---
> imp: deny selected client types from VerifyMembership rpc

- modules/light-clients/06-solomachine/light_client_module.go
- modules/light-clients/06-solomachine/light_client_module_test.go
- modules/light-clients/07-tendermint/light_client_module.go
- modules/light-clients/07-tendermint/light_client_module_test.go
- modules/light-clients/08-wasm/light_client_module.go
- modules/light-clients/08-wasm/light_client_module_test.go
- modules/light-clients/09-localhost/light_client_module.go
> 02-client routing: remove client ID validation

- docs/docusaurus.config.js
- docs/package-lock.json
- docs/package.json
> docs: added feedback widget

- .github/CODEOWNERS
It's my pleasure to add @chatton as a full codeowner. His contributions speak for themselves :heart: 
```text
```
---
> add @chatton as full codeowner 

- README.md
- RELEASES.md
- modules/light-clients/08-wasm/CHANGELOG.md
> add changelog to `08-wasm/release/v0.1.x+ibc-go-v7.3.x-wasmvm-v1.5.x`

- README.md
- RELEASES.md
- SECURITY.md
- modules/light-clients/08-wasm/CHANGELOG.md
> add changelog `08-wasm/release/v0.1.x+ibc-go-v8.0.x-wasmvm-v1.5.x`

- modules/light-clients/08-wasm/CHANGELOG.md
> add changelog `08-wasm/release/v0.2.x+ibc-go-v8.2.x-wasmvm-v2.0.x`

- modules/core/02-client/keeper/consensus_host_test.go
- modules/core/02-client/keeper/keeper.go
- modules/core/03-connection/keeper/handshake_test.go
- modules/light-clients/08-wasm/types/consensus_host.go
> chore: rename client validator to consensus host

- modules/apps/27-interchain-accounts/host/ibc_module.go
- modules/apps/27-interchain-accounts/host/keeper/events.go
This is a backport of this specific addition [here](https://github.com/cosmos/ibc-go/pull/5687/files#diff-05ebdd6bdea34eaf6961a85c1652b125585063fe499f09158a374df7b7b24a85R122). I thought it would be good so that we can benefit of [this improvement](https://github.com/cosmos/ibc-go/pull/5541) in case the error on the host chain is that host functionality is disabled.
closes: #XXXX
---
> imp(release/v8.2.x): emit host disabled event 

- modules/apps/27-interchain-accounts/host/ibc_module.go
- modules/apps/27-interchain-accounts/host/keeper/events.go
Same reasoning as https://github.com/cosmos/ibc-go/pull/6142#issue-2237683282.
closes: #XXXX
---
> imp(release/v8.3.x): emit host disabled event

- modules/apps/27-interchain-accounts/host/ibc_module.go
- modules/apps/27-interchain-accounts/host/keeper/events.go
Same reasoning as https://github.com/cosmos/ibc-go/pull/6142#issue-2237683282
closes: #XXXX
---
> imp(release/v7.4.x): emit host disabled event

- modules/core/02-client/types/genesis.go
- modules/core/02-client/types/genesis_test.go
- modules/core/02-client/types/msgs.go
- modules/core/02-client/types/msgs_test.go
closes: #6061
There is another check in `ValidateBasic` of `MsgUpgradeClient`, but I left that one as is since 07-celestia doesn't implement the `VerifyUpgradeAndUpdateState` functionality (we need to discuss with Rollkit team if this needs to be implemented).
cc: @AdityaSripal 
---
> fix: remove check that client type returned by client state and consensus state match

- modules/light-clients/08-wasm/CHANGELOG.md
- modules/light-clients/08-wasm/go.mod
- modules/light-clients/08-wasm/go.sum
> deps: bump wasmvm v1.5.2

- CHANGELOG.md
- modules/apps/27-interchain-accounts/host/ibc_module.go
- modules/apps/27-interchain-accounts/host/keeper/events.go
> imp(release/v7.5.x): emit host disabled event

- modules/apps/27-interchain-accounts/host/keeper/msg_server.go
Found during e2e testing: `x/bank` module safe queries were missing from the list of module safe queries in the docker image for `release/v7.5.x`; adding the same workaround as for staking seems to fix the problem.
closes: #XXXX
---
> fix: workaround for bank module safe queries

- e2e/tests/transfer/localhost_test.go
- e2e/tests/transfer/upgrades_test.go
- e2e/testsuite/testsuite.go
- modules/apps/29-fee/keeper/events_test.go
- modules/apps/29-fee/transfer_test.go
- modules/apps/callbacks/callbacks_test.go
- modules/apps/transfer/ibc_module.go
- modules/apps/transfer/ibc_module_test.go
- modules/apps/transfer/keeper/mbt_relay_test.go
- modules/apps/transfer/keeper/msg_server.go
- modules/apps/transfer/keeper/msg_server_test.go
- modules/apps/transfer/types/keys.go
- testing/path.go
- testing/solomachine.go
The majority of the issues in the linked issue have already been resolved.
This PR just adds some additional docstrings and changes version variable names to be a bit more clear.
closes: #6109
---
> Adding additional comments and changing version variable names

- modules/apps/transfer/types/msgs.go
- modules/apps/transfer/types/msgs_test.go
> imp: check length tokens array against maximum allowed

- modules/apps/callbacks/types/types_test.go
> Remove unused chain variable in setup for CallbacksTypesTestSuite

- modules/apps/transfer/types/packet_test.go
> test: add ValidateBasic test for FungibleTokenPacketDataV2

- modules/apps/transfer/keeper/relay_test.go
- modules/apps/transfer/types/coin.go
> refactor: remove GetTransferCoin

- testing/chain.go
> chore:fix comment

- .github/CODEOWNERS
Welcome, @gjermundgaraba!
And thank you for all your work as part of the IBC team, @charleenfei!
closes: #XXXX
---
> codeowners: add Gjermund, remove Charly

- modules/apps/29-fee/ibc_middleware.go
- modules/apps/callbacks/ibc_middleware.go
> chore: fix typo

- modules/apps/transfer/types/denom_test.go
> chore: more `types.Denom` to `NewDenom`

- modules/light-clients/08-wasm/types/gas_register.go
> chore: fix typo 

- docs/docusaurus.config.js
- docs/package-lock.json
- docs/package.json
- package-lock.json
I've also bumped docusaurus
closes: #6499 
---
> docs: made v8 the landing version and bumped docusaurus to v3.4

- docs/src/css/custom.css
On the documentation homepage, there is 'IBC-Go Documentation' in blue text in light mode which receives a lot of dead clicks because users think that it is a hyperlink when it is not.
The text should not be the same color as a hyperlink - the text should be changed to black
as https://github.com/cosmos/ibc-go/issues/6503
Has check with dark-light mode
---
> imp: update style breadcumb for prevent conflict with link item

- .github/CODEOWNERS
> code owners: add Nikolas (@bznein) 🥳 

- docs/docs/00-intro.md
- docs/docs/01-ibc/06-channel-upgrades.md
- docs/docs/05-migrations/05-v3-to-v4.md
- docs/requirements/ics08-requirements.md
Fixed some small spelling errors in ./docs/
closes: #XXXX
---
> chore: fix spelling errors

- .github/mergify.yml
> chore: mergify for v7.6.x

- docs/architecture/adr-015-ibc-packet-receiver.md
> fix: ChennelChecker-> ChannelChecker

- modules/apps/transfer/keeper/forwarding.go
Reorder functions in `forwarding.go`
---
> chore: restructure functions with logical ordering

- e2e/testsuite/testsuite.go
I noticed the `GetAndFundTestUsers` function in interchain test has the following docstring
```golang
// GetAndFundTestUsers generates and funds chain users with the native chain denom.
// The caller should wait for some blocks to complete before the funds will be accessible.
```
This may help with some flakiness as there are some tests in which we don't explicitly wait before attempting to broadcast messages with a newly created wallet.
closes: #XXXX
---
> Wait for blocks after wallet creation

- modules/core/04-channel/types/tx.pb.go
- proto/ibc/core/channel/v1/tx.proto
> chore:fix comments

- docs/docs/01-ibc/13-best-practices.md
> docs: add best practices doc for identifying which channel to use

- modules/apps/transfer/keeper/relay_forwarding_test.go
This escaped me as I solved merge conflicts directly on github :( and now golanci-lint complains
closes: #XXXX
---
> (chore) fix linter issue.

- modules/apps/transfer/keeper/relay.go
https://github.com/cosmos/ibc-go/pull/6693#discussion_r1657247208
closes: #XXXX
---
> nit: prebuild the token array during send transfer

- e2e/relayer/relayer.go
> chore:fix var name

- docs/architecture/adr-009-v6-ics27-msgserver.md
- docs/architecture/adr-015-ibc-packet-receiver.md
- docs/architecture/adr-026-ibc-client-recovery-mechanisms.md
- docs/architecture/adr-027-ibc-wasm.md
- docs/architecture/adr.template.md
This PR corrects several grammatical errors in the documentation and comments, improving readability and clarity. These changes enhance the overall quality of the project’s written content.
> Docs improvements

- docs/docs/01-ibc/13-best-practices.md
- docs/docs/05-migrations/13-v8-to-v9.md
> doc: fix small spell check

- modules/apps/transfer/keeper/export_test.go
- modules/apps/transfer/keeper/forwarding.go
- modules/apps/transfer/keeper/relay.go
To unify a bit the terminology regarding the forwarded packet
closes: #XXXX
---
> nit: settle on forwarded packet terminology

- README.md
> fix: loc badge

- .github/workflows/e2e-fork.yml
- .github/workflows/e2e.yaml
Suggestion by @DimitrisJim to fix e2e fork workflows from actual forks.
---
> fix: add condition to e2e-fork workflow

- go.work.example
Adds `simapp` to example `go.work` file
---
> chore: update example go work file

- modules/core/02-client/keeper/keeper.go
> chore: remove UpdateLocalhostClient func from 02-client

- modules/light-clients/08-wasm/go.mod
I added this both to v7.3.x and v8.3.x compatible release lines. If it's enough with having only on the v8.3.x compatible release branch, I can close this PR.
closes: #XXXX
---
> chore(08-wasm v0.2.x): previous 08-wasm versions using `MerkletPath` with `[]string`

- modules/light-clients/08-wasm/go.mod
> chore(08-wasm v0.3.x): previous 08-wasm versions using `MerkletPath` with `[]string`

- e2e/tests/core/03-connection/connection_test.go
- e2e/tests/transfer/base_test.go
- e2e/tests/transfer/forwarding_test.go
- e2e/tests/transfer/incentivized_test.go
- e2e/tests/transfer/localhost_test.go
- e2e/tests/transfer/send_enabled_test.go
- e2e/tests/transfer/send_receive_test.go
- e2e/tests/transfer/upgradesv1_test.go
- e2e/tests/transfer/upgradesv2_test.go
- e2e/tests/upgrades/genesis_test.go
- e2e/tests/upgrades/upgrade_test.go
- e2e/testsuite/tx.go
- Adds an extra argument to `Transfer` to pass forwarding information.
- Uses `Transfer` instead of `GetTransferMessage` + `BroadcastMessages` where possible.
closes: #XXXX
---
> e2e: add `forwarding` to `Transfer` function of e2e test suite

- modules/core/03-connection/types/expected_keepers.go
> chore: rm ClientStore method from expected client keeper

- .github/mergify.yml
> chore: mergify task for v9.0.x backport

- docs/docusaurus.config.js
Adds syntax highlighting for golang and diff.
See: https://prismjs.com/#supported-languages
---
> imp: add syntax highlight for go and diff on doc site

- modules/apps/callbacks/forwarding_test.go
Tests on main are currently broken since my previous PR got merged in without changing the imports to v9
---
> (chore) update imports to v9

- docs/docs/05-migrations/13-v8-to-v9.md
> docs: add `forwarding` argument to `NewMsgTransfer`

- modules/core/02-client/migrations/v7/store.go
- modules/core/03-connection/keeper/keeper_test.go
- modules/core/03-connection/keeper/verify_test.go
fix some comments
closes: #XXXX
---
> chore: fix some comments

- .github/mergify.yml
> chore: mergify for v7.7.x and v8.4.x

- modules/apps/transfer/keeper/forwarding.go
I thought it was a bit confusing because on [call sites](https://github.com/cosmos/ibc-go/blob/f11ac7a9d4fbb0b29d2c21ca7ed89c6f8638ebf0/modules/apps/transfer/keeper/relay.go#L288-L308) the names were reversed.
closes: #XXXX
---
> nit: rename arguments of `acknowledgeForwardedPacket` for clarity

- CHANGELOG.md
- docs/docs/01-ibc/02-integration.md
- docs/docs/03-light-clients/04-wasm/03-integration.md
- modules/apps/callbacks/testing/simapp/app.go
- modules/core/02-client/keeper/keeper.go
- modules/light-clients/08-wasm/testing/simapp/app.go
- simapp/app.go
- testing/simapp/app.go
I'm not entirely sure if I need to change some other documentation files... @crodriguezvega can you help here? :)
closes: #6926
---
> chore(api!): Replace GetRouter with AddRoute in 02-client keeper.

- modules/apps/29-fee/ibc_middleware.go
- modules/apps/29-fee/ibc_middleware_test.go
- modules/apps/29-fee/types/encoding.go
> (chore) disallow unknown fields29 fee ack

- CHANGELOG.md
- modules/core/04-channel/keeper/upgrade.go
- modules/core/04-channel/keeper/upgrade_test.go
Changes for https://github.com/cosmos/ibc/pull/1127.
closes: #XXXX
---
> fix(state!): check upgrade compatibility in channel upgrade confirm

- modules/light-clients/08-wasm/CHANGELOG.md
- modules/light-clients/08-wasm/go.mod
- modules/light-clients/08-wasm/types/contract_api.go
Explicitly break the api of json encoded contract msgs
closes: #XXXX
---
> api!: rename path to merkle path for contract api json msgs

- .github/mergify.yml
Removing the backport task for all previous release lines since they are retracted.
closes: #XXXX
---
> megify(08-wasm): adding backport for latest release lines, removing for previous ones

- go.mod
I think with [this fix](https://github.com/cosmos/ibc-go/pull/6935) coming out in v8.4.0, we should retract previous versions.
closes: #XXXX
---
> release/v8.4.x: retract v8.2.x and v8.3.x

- docs/events/events.md
> docs(`update_client` event): remove header, add consensus heights

- CHANGELOG.md
- docs/architecture/adr-008-app-caller-cbs.md
- docs/docs/01-ibc/03-apps/02-ibcmodule.md
- docs/docs/04-middleware/02-callbacks/03-interfaces.md
- docs/docs/05-migrations/13-v8-to-v9.md
> Update changelog for unmarshal packet data interface change

- modules/apps/27-interchain-accounts/controller/ibc_middleware_test.go
- modules/apps/27-interchain-accounts/host/ibc_module_test.go
- modules/apps/29-fee/ibc_middleware.go
- modules/apps/callbacks/ibc_middleware.go
- modules/apps/transfer/ibc_module_test.go
- modules/core/05-port/types/ibc_legacy_module.go
- modules/core/keeper/msg_server.go
- modules/core/keeper/msg_server_test.go
> Use new port router for OnChanUpgradeTry

- modules/apps/27-interchain-accounts/controller/ibc_middleware_test.go
- modules/apps/27-interchain-accounts/host/ibc_module_test.go
- modules/apps/29-fee/ibc_middleware.go
- modules/apps/29-fee/ibc_middleware_test.go
- modules/apps/callbacks/ibc_middleware.go
- modules/apps/callbacks/ibc_middleware_test.go
- modules/core/05-port/types/ibc_legacy_module.go
- modules/core/keeper/msg_server.go
> refactor: implement OnChanCloseInit using new port router.

- modules/apps/27-interchain-accounts/controller/ibc_middleware.go
- modules/apps/29-fee/ibc_middleware.go
- modules/apps/29-fee/ibc_middleware_test.go
- modules/apps/callbacks/ibc_middleware.go
- modules/core/05-port/types/ibc_legacy_module.go
- modules/core/keeper/msg_server.go
> refactor: implement OnChanCloseConfirm using new port router

- modules/apps/transfer/internal/events/events.go
- modules/apps/transfer/types/packet_test.go
- modules/core/04-channel/keeper/events.go
> chore: fix some function names

- docs/architecture/README.md
- modules/apps/transfer/keeper/MBT_README.md
> chore: fix typos

- SECURITY.md
> Fix email link in SECURITY.md

- modules/core/packet-server/keeper/keeper.go
- modules/core/packet-server/types/keys.go
- modules/core/packet-server/types/merkle.go
> add submodule to logger

- .github/mergify.yml
> mergify for 08-wasm with v9.0.x

- modules/light-clients/08-wasm/testing/simapp/simd/cmd/root.go
- simapp/simd/cmd/root.go
> nit: remove useless code

- e2e/go.mod
- e2e/testsuite/testsuite.go
- go.mod
- go.sum
- modules/core/05-port/types/router.go
As recommended by @tac0turtle.
closes: #XXXX
---
> chore: remove exp pkg

- go.work.example
> chore: update go work example go toolchain

- RELEASES.md
> fix: update eol dates for callbacks and wasm

- .github/CODEOWNERS
I will show myself the way out 😄 The end of an era!
closes: #XXXX
---
> chore: remove myself as codeowner

- modules/core/04-channel/keeper/keeper.go
- modules/core/04-channel/keeper/keeper_test.go
- modules/core/packet-server/keeper/relay.go
- modules/core/packet-server/types/expected_keepers.go
should be final part of aliasing.
closes: #XXXX
---
> Add fallback function to grab counterparty for non-eureka channels

- modules/core/04-channel/v2/types/codec.go
- modules/core/04-channel/v2/types/tx.pb.go
- proto/ibc/core/channel/v2/tx.proto
> chore: add MsgTimeout skeleton

- modules/core/05-port/keeper/keeper.go
- modules/core/api/module.go
- testing/mock/v2/ibc_app.go
- testing/mock/v2/ibc_module.go
> chore: add OnRecvPacket to IBCModule V2 interface

- modules/core/04-channel/v2/keeper/keeper.go
- modules/core/04-channel/v2/keeper/relay.go
- modules/core/24-host/v2/packet_keys.go
Address a nit from a previous PR which I raised! 
- Use sequence uint64 in APIs before finally formatting as big endian bytes in host keys.
---
> refactor: host keys apis to use uint64 sequence and fmt big endian bytes internally

- modules/core/04-channel/v2/keeper/keeper.go
- modules/core/24-host/v2/packet_keys.go
> chore: cleanup ids in eureka branch

- .github/mergify.yml
Diagnosing mergify blocking CI runs here: https://github.com/cosmos/ibc-go/pull/7430/checks
---
> ci: mergify updates

- modules/core/04-channel/v2/types/tx.pb.go
- proto/ibc/core/channel/v2/tx.proto
> nit: reorder proto msgs

- go.mod
- go.sum
- testing/simapp/app.go
:scissors: :smile: 
closes: #XXXX
---
> chore: prune unnecessary cosmossdk.io/client/v2 dependency

- testing/simapp/app.go
Removes autocli references in testing structure. ICA depends on "cosmossdk.io/api", otherwise this would have removed it from the top level go.mod. Same changes in wasm/callabcks will remove that dep
closes: #XXXX
---
> chore: remove autocli references in testing structure

- modules/core/04-channel/v2/types/channel_test.go
> chore: add tests for Channel.Validate

- docs/versioned_docs/version-v7.8.x/03-light-clients/03-localhost/03-client-state.md
Hi there, the file is not exist. so I delete the path
> chore(docs): delete not exist file path

- e2e/go.mod
- e2e/go.sum
- go.mod
- go.sum
- modules/apps/callbacks/go.mod
- modules/apps/callbacks/go.sum
- modules/light-clients/08-wasm/go.mod
- modules/light-clients/08-wasm/go.sum
- simapp/go.mod
- simapp/go.sum
> chore: lockin cosmos-sdk v0.50.10

- docs/docusaurus.config.js
Docs land on v8 by default at the moment
---
> docs: land on v9 by default

- modules/core/04-channel/v2/types/commitment.go
- modules/core/04-channel/v2/types/commitment_test.go
- modules/core/24-host/v2/packet_key_test.go
closes: #7563 
It makes commit bytes with a fixed length (32 bytes) for better gas cost in Solidity. I also added some tests to document the output, as we are using those outputs for tests in the Solidity implementation as well to make sure they match.
---
> make packet commitments fixed length

- modules/core/04-channel/v2/keeper/events.go
- modules/core/04-channel/v2/keeper/packet.go
- modules/core/04-channel/v2/types/events.go
targets the send packet branch.
part-of: #7386
---
> chore: add events for recv packet.

- modules/apps/callbacks/types/types_test.go
- testing/coordinator.go
- testing/endpoint.go
fix some problematic comment
---
> chore: fix some problematic comment

- modules/core/04-channel/keeper/keeper_test.go
- modules/light-clients/08-wasm/internal/types/store.go
- modules/light-clients/08-wasm/keeper/keeper.go
fix some function names in comment
---
> chore: fix some function names in comment

- modules/apps/transfer/client/cli/tx.go
- modules/apps/transfer/keeper/msg_server.go
- modules/apps/transfer/types/transfer.pb.go
- modules/core/02-client/types/height.go
- modules/core/23-commitment/types/merkle_test.go
- proto/ibc/applications/transfer/v1/transfer.proto
> Clean up: linting, formatting, and spelling corrections

- internal/validate/validate_test.go
- modules/light-clients/09-localhost/light_client_module_test.go
> (chore) update tests in internal and 09-localhost tests to expect specific error

- modules/light-clients/06-solomachine/client_state_test.go
- modules/light-clients/06-solomachine/codec_test.go
- modules/light-clients/06-solomachine/consensus_state_test.go
- modules/light-clients/06-solomachine/header_test.go
- modules/light-clients/06-solomachine/light_client_module_test.go
- modules/light-clients/06-solomachine/misbehaviour_test.go
- modules/light-clients/06-solomachine/proof_test.go
> (chore) update tests in light-clients/06-solomachine to expect specific error

- modules/core/03-connection/types/keys_test.go
- modules/core/03-connection/types/version_test.go
> chores: fix final connection tests

- modules/apps/27-interchain-accounts/controller/keeper/handshake_test.go
- modules/apps/27-interchain-accounts/host/keeper/handshake_test.go
- modules/core/04-channel/types/query.go
> fix mispells in code

- modules/apps/29-fee/ibc_middleware_test.go
> chores: use error in test unmarshal

- modules/core/04-channel/v2/keeper/keeper.go
> fix: use unordered check

- CHANGELOG.md
> update changelog for v9.0.2

- modules/core/02-client/types/client_test.go
> fixed exp error in modules/02-client/types/client-test.go

- .github/mergify.yml
Adds backport tasks for wasm branches. Tags have been created.
closes: #XXXX
---
> chore: add backport tasks for new release branches

- modules/apps/27-interchain-accounts/genesis/types/genesis_test.go
> chore: fix test  TestValidateControllerGenesisState, use expected errors

- CHANGELOG.md
> chore: added changelog entry for vesting account balance transfer

- modules/apps/27-interchain-accounts/genesis/types/genesis_test.go
> chore: fix test TestValidateHostGenesisState, use expected errors

- modules/light-clients/09-localhost/light_client_module.go
> chore: use header service in localhost client

- .github/mergify.yml
> chore: fix mergify task for 08-wasm

- modules/light-clients/08-wasm/go.mod
- modules/light-clients/08-wasm/go.sum
Fixes: 
* https://github.com/CosmWasm/advisories/blob/main/CWAs/CWA-2024-007.md
* https://github.com/CosmWasm/advisories/blob/main/CWAs/CWA-2024-008.md
Note: this is consensus breaking change (hence the new branch with bumped minor version)
closes: #XXXX
---
> chore: bump wasmvm from 1.5.2 to 1.5.6

- .github/CODEOWNERS
> Axe myself from CODEOWNERS

- modules/apps/27-interchain-accounts/types/account_test.go
> chore: fix test TestGenesisAccountValidate, use expected errors

- modules/light-clients/08-wasm/CHANGELOG.md
> chore: update changelog for v0.5.0+ibc-go-v8.4-wasmvm-v2.1

- modules/light-clients/08-wasm/CHANGELOG.md
> chore: update changelog for v0.4.0+ibc-go-v7.4-wasmvm-v1.5

- .github/workflows/spell-checker.yml
> chore: fix spell-checker

- modules/apps/27-interchain-accounts/types/metadata_test.go
> chore: fix to use exp error in test TestValidateHostMetadata

- modules/light-clients/07-tendermint/client_state.go
was missed in other pr :)
closes: #XXXX
---
> Use wrap instead of wrapf

- modules/light-clients/07-tendermint/client_state_test.go
> chore : lint (unused field)

- .github/ISSUE_TEMPLATE/bug-report.md
> fix: typo bug-report.md

- docs/versioned_docs/version-v4.6.x/01-ibc/05-upgrades/00-intro.md
- docs/versioned_docs/version-v5.4.x/01-ibc/05-upgrades/00-intro.md
- docs/versioned_docs/version-v6.3.x/01-ibc/05-upgrades/00-intro.md
- docs/versioned_docs/version-v7.8.x/01-ibc/05-upgrades/00-intro.md
docs: fix typographical errors
> docs: fix typographical errors

- .github/workflows/e2e.yaml
- .github/workflows/spell-checker.yml
- modules/core/04-channel/keeper/upgrade_test.go
> chore: add hidden folders to codespell

- modules/core/04-channel/v2/keeper/events.go
- modules/core/04-channel/v2/types/events.go
- testing/events.go
> imp: updated events to remove channels

- .github/workflows/build-wasm-simd-image-from-tag.yml
Due to some strange error with QEMU and/or docker/buildx, our wasm simapp image builds have not been functional for some days. 
To bypass the issue, I've refactored the job to build in parallell on two different hosts, using native runners. This solves the problem, and speeds up the build significantly (from 20+ minutes down to 4: https://github.com/cosmos/ibc-go/actions/runs/12966311751) - at the cost of a slightly more complex CI job. For now, this is probably the best option.
---
> fix: build wasm image on native architecture

- go.mod
> chore: retract v8.5.3

- .github/mergify.yml
> chore: add mergify task for v10 release branch

- .github/workflows/test.yml
- e2e/go.mod
- e2e/go.sum
- modules/light-clients/08-wasm/go.mod
- modules/light-clients/08-wasm/go.sum
> deps: bump wasmvm to v2.2.2

- modules/apps/transfer/types/errors.go
- modules/apps/transfer/v2/ibc_module.go
- modules/apps/transfer/v2/ibc_module_test.go
- modules/core/02-client/migrations/v7/solomachine.pb.go
- modules/core/04-channel/v2/keeper/msg_server.go
- modules/core/04-channel/v2/keeper/msg_server_test.go
- modules/core/04-channel/v2/types/acknowledgement.go
- modules/core/04-channel/v2/types/packet.pb.go
- modules/light-clients/06-solomachine/solomachine.pb.go
- proto/ibc/core/channel/v2/packet.proto
> Use Constant Error Acknowledgment

- modules/apps/transfer/ibc_module.go
- modules/apps/transfer/internal/telemetry/telemetry.go
- modules/apps/transfer/v2/ibc_module.go
closes: #7707
closes: #7706
---
> chore: transfer telemetry and events in eureka

- modules/core/02-client/types/msgs_test.go
- modules/core/24-host/validate.go
> imp: allow 8 character client ids

- modules/apps/transfer/v2/ibc_module_test.go
> Assert sending ibc denom directly is not allowed

- .github/workflows/e2e-compatibility.yaml
> chore: add v10 to e2e compatbility workflows

- .github/workflows/build-simd-image-from-tag.yml
- .github/workflows/build-wasm-simd-image-from-tag.yml
- .github/workflows/callbacks.yml
- .github/workflows/check-docs.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/deploy-docs.yml
- .github/workflows/docker.yml
- .github/workflows/e2e-compatibility-workflow-call.yaml
- .github/workflows/e2e-compatibility.yaml
- .github/workflows/e2e-fork.yml
- .github/workflows/e2e-test-workflow-call.yml
- .github/workflows/e2e.yaml
- .github/workflows/e2emodule.yml
- .github/workflows/golangci-feature.yml
- .github/workflows/golangci.yml
- .github/workflows/link-check.yml
- .github/workflows/markdown-lint.yml
- .github/workflows/proto-breaking-check.yml
- .github/workflows/proto-registry.yml
- .github/workflows/release-wasm.yml
- .github/workflows/release.yml
- .github/workflows/spell-checker.yml
- .github/workflows/test.yml
- .github/workflows/wasm-client.yml
deprecates github actions runners in favor of depot.dev managed runners
---
> ci: move at the speed of light (deprecate github actions runners)

- e2e/go.mod
- e2e/go.sum
> deps: update interchaintest

- modules/apps/callbacks/go.mod
- modules/apps/callbacks/go.sum
> chore: add ibc-go beta tag to callbacks

- .github/workflows/callbacks.yml
- .github/workflows/test.yml
- .github/workflows/wasm-client.yml
> chore: update sonarqube gh action

- .github/workflows/e2e-compatibility.yaml
- e2e/tests/interchain_accounts/params_test.go
- e2e/tests/interchain_accounts/query_test.go
- e2e/testsuite/query/grpc_query.go
- e2e/testsuite/testsuite.go
- e2e/testsuite/tx.go
> test: fix ica compatibility tests

- e2e/go.mod
- modules/light-clients/08-wasm/go.mod
- modules/light-clients/08-wasm/go.sum
> chore: 08-wasm beta.0

- Makefile
- e2e/testsuite/query/queries.go
> fix: upgrades after moving ics20-2

- modules/apps/callbacks/go.mod
- modules/apps/callbacks/go.sum
> chore: callbacks beta.1

- .github/mergify.yml
> chore: add v7.9 and v8.6 to mergify

- .github/workflows/e2e-compatibility.yaml
- e2e/tests/interchain_accounts/base_test.go
> fix: ica gov e2e test

- e2e/tests/interchain_accounts/base_test.go
- e2e/tests/interchain_accounts/query_test.go
> fix: only run unordered tests on correct versions

- e2e/go.mod
- e2e/go.sum
> chore: update to latest interchaintest with latest ibc-go

- e2e/go.mod
- modules/apps/callbacks/go.mod
- modules/apps/callbacks/go.sum
- modules/light-clients/08-wasm/go.mod
- modules/light-clients/08-wasm/go.sum
> chore: set release versions for callbacks and light clients

- modules/apps/callbacks/go.mod
- modules/apps/callbacks/go.sum
- modules/light-clients/08-wasm/go.mod
- modules/light-clients/08-wasm/go.sum
> chore: update modules for rc1 release

- modules/apps/callbacks/go.mod
- modules/apps/callbacks/go.sum
- modules/light-clients/08-wasm/go.mod
- modules/light-clients/08-wasm/go.sum
> chore: bump modules to rc2

- modules/light-clients/08-wasm/go.mod
- modules/light-clients/08-wasm/go.sum
> chore: prep 08-wasm rc.3

- modules/core/02-client/types/msgs_test.go
- modules/core/24-host/validate.go
- modules/light-clients/07-tendermint/misbehaviour_test.go
> imp: allow 4 character client ids

- e2e/tests/core/02-client/client_test.go
- e2e/testsuite/tx.go
> fix: e2e scheduled ibc upgrade

- modules/apps/transfer/v2/ibc_module.go
- modules/apps/transfer/v2/ibc_module_test.go
- modules/core/02-client/types/keys.go
- modules/core/02-client/v2/types/msgs.go
- modules/core/02-client/v2/types/msgs_test.go
- modules/core/exported/client.go
closes: #8145 
I make the check both in 02-client MsgRegisterCounterparty and **also** in the transfer v2 callback in order to double check and provide defense-in-depth
---
> Enforce clientID format

- e2e/tests/upgrades/upgrade_test.go
- e2e/testvalues/values.go
> fix: upgrade tests after localhost name change

- modules/light-clients/08-wasm/go.mod
- modules/light-clients/08-wasm/go.sum
> chore: bump wasmd to ibc-go v10.0.0

- modules/core/02-client/keeper/keeper.go
- modules/core/02-client/types/keys.go
- modules/core/exported/client.go
> revert localhost-id change

- .github/mergify.yml
- .github/workflows/e2e-compatibility.yaml
- .github/workflows/e2e-manual-simd.yaml
- e2e/ci-e2e-config.yaml
- e2e/tests/core/02-client/client_test.go
- e2e/tests/interchain_accounts/base_test.go
- e2e/tests/interchain_accounts/localhost_test.go
- e2e/tests/interchain_accounts/params_test.go
- e2e/tests/interchain_accounts/query_test.go
- e2e/tests/transfer/base_test.go
> chore: update release branch mergify + some compat cleanups

- .github/workflows/e2e-manual-simd.yaml
- .github/workflows/e2e-upgrade.yaml
- RELEASES.md
- e2e/ci-e2e-config.yaml
- e2e/sample.config.extended.yaml
- e2e/tests/core/02-client/client_test.go
- e2e/tests/core/03-connection/connection_test.go
- e2e/tests/interchain_accounts/base_test.go
- e2e/tests/interchain_accounts/gov_test.go
- e2e/tests/interchain_accounts/groups_test.go
- e2e/tests/interchain_accounts/localhost_test.go
- e2e/tests/interchain_accounts/params_test.go
- e2e/tests/interchain_accounts/query_test.go
- e2e/tests/transfer/authz_test.go
- e2e/tests/transfer/base_test.go
- e2e/tests/transfer/localhost_test.go
- e2e/tests/transfer/send_enabled_test.go
- e2e/tests/transfer/send_receive_test.go
- e2e/tests/upgrades/genesis_test.go
- modules/core/04-channel/keeper/packet_test.go
> chore: update versions after release

- .github/workflows/proto-registry.yml
> chore: backport buf push changes to v10.1.x branch

- docs/docs/02-apps/02-interchain-accounts/01-overview.md
- adds warning that ICA is only usable with IBC Classic
---
> docs: add ICA warning

- docs/docs/02-apps/01-transfer/01-overview.md
- docs/docs/02-apps/01-transfer/02-state.md
- docs/docs/02-apps/01-transfer/03-state-transitions.md
- docs/docs/02-apps/01-transfer/04-messages.md
- docs/docs/02-apps/01-transfer/05-events.md
- docs/docs/02-apps/01-transfer/06-metrics.md
- docs/docs/02-apps/01-transfer/07-params.md
- docs/docs/02-apps/01-transfer/08-authorizations.md
- docs/docs/02-apps/01-transfer/09-client.md
- docs/docs/02-apps/01-transfer/10-IBCv2-transfer.md
updates transfer documentation for ibcv2
---
> docs: ibcv2 transfer docs update

- modules/core/02-client/v2/types/config_test.go
> fix(02-client): updates TestValidateConfig, use expected errors

- docs/docs/00-intro.md
- docs/docs/01-ibc/04-middleware/02-develop.md
- docs/docs/01-ibc/04-middleware/02-developIBCv2.md
- docs/versioned_docs/version-v7.8.x/01-ibc/04-middleware/01-develop.md
- docs/versioned_docs/version-v8.5.x/01-ibc/04-middleware/02-develop.md
update links in overview, add in the middleware deserilaisation parts
closes: #8094 
---
> docs:Final v10 docs update and middleware serialization

- CHANGELOG.md
> chore: update changelog for v10.1.1

- e2e/go.mod
- e2e/go.sum
- go.mod
- go.sum
- modules/light-clients/08-wasm/go.mod
- modules/light-clients/08-wasm/go.sum
- simapp/go.mod
- simapp/go.sum
> chore: bump go-ethereum to v1.15.8

- .github/mergify.yml
- .github/workflows/e2e-compatibility.yaml
- e2e/go.mod
> chore: prep v10.2.x mergify

- modules/light-clients/08-wasm/go.mod
- modules/light-clients/08-wasm/go.sum
> chore: point 08-wasm to ibc-go v10.2.0

- modules/light-clients/08-wasm/Dockerfile
Fixes the wasm docker image build error
---
> chore: bumped go version used by wasm dockerfile

- .github/workflows/docs-check.yml
- Makefile
- docs/.markdownlint-cli2.jsonc
- docs/.markdownlint.jsonc
- docs/README.md
The markdown lint config was mistakenly deleted in #8365, so adding it back, but only in the docs.
Also added a `lint-docs` make target to easily run it locally.
---
> chore: fix doc linting and add make target with docs

- .github/mergify.yml
- .github/workflows/e2e-compatibility.yaml
> chore: set up v10.3.x branch mergify and ci

- modules/apps/transfer/v2/ibc_module_test.go
> chore: lint

- .github/dependabot.yml
Two goals with this PR:
1. Fix the dependabot bumps so that they update dependencies of all the modules at the same time (currently we need to manually update the PR with `make tidy-all`
2. Reduce the number of PRs by grouping non-cosmos dependencies
---
> chore: group dependabot bumps

- .github/dependabot.yml
> chore: dependabot update allow all

- README.md
Adds a [DeepWiki](https://deepwiki.com/cosmos/ibc-go) badge for ibc-go, which also makes sure that the DeepWiki gets automatically refreshed.
---
> docs: add deepwiki badge to readme

- modules/apps/callbacks/types/callbacks.go
> chore: lint and pr link test

- testing/utils.go
> chore: fix import order in testing

- .github/mergify.yml
- .github/workflows/e2e-compatibility.yaml
Just stuff that needs to be done so we can eventually release v8.8.0
---
> chore: add v8.8.x backporting

- CHANGELOG.md
Co-authored-by: Gjermund Garaba <gjermund@garaba.net>
closes: #XXXX
---
> chore: set release for v10.3.0 in changelog

- .github/workflows/e2e.yaml
> chore: change e2e image name

- e2e/go.mod
- modules/light-clients/08-wasm/go.mod
- modules/light-clients/08-wasm/go.sum
Co-authored-by: Gjermund Garaba <gjermund@garaba.net>
closes: #XXXX
---
> chore: 08-wasm v10.3.0

- CHANGELOG.md
- e2e/go.mod
- modules/light-clients/08-wasm/go.mod
> chore: post v10.3.0 changelog cleanup

- .github/workflows/dependabot-tidy.yml
> chore: fix dependabot tidy workflow

- .github/workflows/dependabot-tidy.yml
> chore: last dependabot tidy fix

- .github/workflows/dependabot-tidy.yml
> chore: make dependabot push trigger workflows

- codecov.yml
> chore: set codecov to be informational in ci checks

- .github/workflows/docker.yml
> ci: add release branch docker tags
