cosmos/ibc-go

- CHANGELOG.md
- modules/light-clients/07-tendermint/types/client_state.go
- modules/light-clients/07-tendermint/types/client_state_test.go
matches [tendermint check](https://github.com/tendermint/tendermint/blob/3ed8f14bf973bb8cc3c262240a291f07d45b3f3f/types/block.go#L390)
closes: #96 
---
> Add max length chain-id check on tendermint client

- CHANGELOG.md
- modules/apps/transfer/client/cli/tx.go
- modules/apps/transfer/handler_test.go
- modules/apps/transfer/keeper/relay_test.go
- modules/apps/transfer/types/msgs.go
- modules/apps/transfer/types/msgs_test.go
- modules/apps/transfer/types/packet_test.go
- modules/core/02-client/client/cli/tx.go
- modules/core/02-client/keeper/client_test.go
- modules/core/02-client/types/msgs.go
- modules/core/02-client/types/msgs_test.go
- modules/core/03-connection/client/cli/tx.go
- modules/core/03-connection/types/msgs.go
- modules/core/03-connection/types/msgs_test.go
- modules/core/04-channel/client/cli/tx.go
- modules/core/04-channel/types/msgs.go
- modules/core/04-channel/types/msgs_test.go
- modules/core/keeper/msg_server_test.go
- testing/chain.go
- testing/coordinator.go
> Modify all message constructors to take in a string for address

- CHANGELOG.md
- docs/migrations/ibc-migration-043.md
- modules/core/04-channel/keeper/packet.go
- modules/core/04-channel/types/events.go
Encoding packet data in hex allows for more robust encoding/decoding for relayers. Proto-encoded packets were breaking with old bare string conversion. Raw binary can be passed through events using hex.
Tested live with go-relayer and two-chainz script
closes: #XXXX
---
> Hex Packet Data

- CHANGELOG.md
- modules/core/02-client/types/msgs.go
- modules/core/03-connection/types/events.go
- modules/core/03-connection/types/msgs.go
- modules/core/04-channel/types/events.go
- modules/core/04-channel/types/msgs.go
- modules/core/04-channel/types/msgs_test.go
- modules/core/keeper/msg_server.go
SDK has removed `Type()` `Route()` and `GetSignBytes()` from the Msg interface. Those functions are still needed for the transfer message which supports amino signing. They would be unused for all other message types.
I figure we might as well remove what we can before 1.0.0 since after that we would need to wait for a major version release to remove old APIs
closes: #159 
---
> remove Type(), Route(), GetSignBytes() (removed from sdk.Msg interface)

- CHANGELOG.md
- docs/migrations/ibc-migration-043.md
- modules/core/02-client/keeper/client.go
- modules/core/exported/client.go
- modules/core/keeper/msg_server.go
- modules/light-clients/06-solomachine/types/misbehaviour.go
- modules/light-clients/06-solomachine/types/misbehaviour_test.go
- modules/light-clients/07-tendermint/types/misbehaviour.go
- modules/light-clients/07-tendermint/types/misbehaviour_test.go
> remove misbehaviour GetHeight

- CHANGELOG.md
- docs/migrations/ibc-migration-043.md
- modules/core/04-channel/keeper/packet.go
- modules/core/04-channel/types/events.go
> emit hex encoded ack attribute in events

- CHANGELOG.md
- modules/core/02-client/genesis.go
- modules/core/03-connection/genesis.go
- modules/core/04-channel/genesis.go
> Missing NextClientSequence, NextConnectionSequence and NextChannelSequence in ExportGenesis

- modules/core/04-channel/keeper/packet.go
- modules/core/04-channel/keeper/timeout.go
- modules/light-clients/07-tendermint/types/client_state.go
addresses [comment](https://github.com/cosmos/ibc-go/pull/184#discussion_r641374753)
closes: #XXXX
---
> improve error messages

- CHANGELOG.md
- modules/light-clients/07-tendermint/types/genesis.go
- modules/light-clients/07-tendermint/types/genesis_test.go
- modules/light-clients/07-tendermint/types/store.go
> fix genesis exporting of tendermint metadata

- CHANGELOG.md
- modules/core/04-channel/keeper/packet.go
- modules/core/04-channel/keeper/packet_test.go
> disable defensive timestamp check for solo machines in SendPacket

- modules/apps/transfer/keeper/relay.go
- modules/core/02-client/keeper/client.go
- modules/core/02-client/keeper/proposal.go
- modules/core/02-client/types/metrics.go
- modules/core/keeper/msg_server.go
- modules/core/types/metrics.go
Move metric labels to types package and use correct Prometheus format (`s/-/_`).
closes: #222
**This should be included in the next SDK/Gaia point release.**
---
> fix: correct metric labels

- CHANGELOG.md
- docs/migrations/ibc-migration-v100.md
- modules/apps/transfer/module.go
- modules/core/05-port/types/module.go
- modules/core/keeper/msg_server.go
- testing/mock/mock.go
Closes #215 by removing `sdk.Result` from the IBC Module
-->
closes: #215 
---
> Remove sdk.Result from application callbacks #215

- CHANGELOG.md
> add missing changelog entries

- modules/core/keeper/msg_server.go
The events set in the cache context need to be set in the original context.
---
> Fix missing events in OnRecvPacket

- CHANGELOG.md
- docs/client/config.json
- docs/client/swagger-ui/swagger.yaml
- go.mod
- go.sum
- modules/core/04-channel/keeper/events.go
- modules/core/04-channel/keeper/packet.go
- modules/core/04-channel/keeper/packet_test.go
- modules/core/04-channel/keeper/timeout.go
- modules/core/04-channel/keeper/timeout_test.go
- modules/core/04-channel/types/errors.go
- modules/core/ante/ante.go
- modules/core/ante/ante_test.go
- modules/core/keeper/msg_server.go
- modules/core/keeper/msg_server_test.go
- scripts/protoc-swagger-gen.sh
- testing/mock/mock.go
- testing/values.go
> backport changes for rc2

- CHANGELOG.md
- modules/apps/transfer/keeper/keeper.go
- modules/apps/transfer/types/expected_keepers.go
> remove ChanCloseInit function from transfer keeper

- modules/apps/27-interchain-accounts/keeper/account.go
- modules/apps/27-interchain-accounts/keeper/account_test.go
- modules/apps/27-interchain-accounts/keeper/handshake.go
- modules/apps/27-interchain-accounts/keeper/handshake_test.go
- modules/apps/27-interchain-accounts/keeper/keeper.go
- modules/apps/27-interchain-accounts/keeper/relay.go
- modules/core/04-channel/types/errors.go
Added `OnChanOpenInit` and `InitIntechainAccount` tests and improved associated code. Code aligns with currently proposed specification
closes: #XXXX
---
> Add interchain account OnChanOpenInit and InitInterchainAccount tests

- modules/apps/27-interchain-accounts/keeper/handshake_test.go
Adding test for `OnChanOpenConfirm` as part of the handshake tests. There is not a whole lot to test here. 
ref: https://github.com/cosmos/ibc-go/issues/279
---
> test: adding test for OnChanOpenConfirm

- modules/apps/27-interchain-accounts/keeper/handshake.go
- modules/apps/27-interchain-accounts/types/keys.go
At present, the hermes relayer is hardcoded to use `ibcaccount` when listening for packets for interchain accounts. For now lets leave it at `ibcaccount` & I'll make a PR to `ibc-rs` to request an update to `interchain-accounts` sometime next week. 
I have also fixed a small bug in the `OnChanOpenInit` function whereby we were overwriting the `channelID` with an empty string when checking for an active channel.  
closes: #317 
---
> fix: updating port-id & fixing OnChanOpenInit bug

- modules/apps/27-interchain-accounts/keeper/handshake.go
- modules/apps/27-interchain-accounts/keeper/handshake_test.go
Small PR to add check that active channel is set correctly. 
closes: #314 
---
> test: check active channel is correct

- modules/apps/27-interchain-accounts/keeper/keeper.go
- testing/simapp/app.go
Removed `memKey` from ICA keeper.
closes: #336
---
> Removed memkey from ICA keeper

- docs/ibc/integration.md
- go.mod
- go.sum
- modules/apps/transfer/module.go
- modules/core/04-channel/keeper/events.go
- modules/core/04-channel/keeper/packet.go
> backport changes for v1.0.1

- modules/apps/27-interchain-accounts/keeper/account.go
- modules/apps/27-interchain-accounts/keeper/grpc_query.go
- modules/apps/27-interchain-accounts/keeper/handshake.go
- modules/apps/27-interchain-accounts/keeper/keeper.go
- modules/apps/27-interchain-accounts/keeper/keeper_test.go
- modules/apps/27-interchain-accounts/keeper/relay.go
Another small PR, more housekeeping for interchain-accounts branch.
closes: #315
---
> move Get/SetInterchainAccount to keeper.go, add tests

- modules/apps/27-interchain-accounts/client/cli/query.go
- modules/apps/27-interchain-accounts/genesis.go
- modules/apps/27-interchain-accounts/keeper/account.go
- modules/apps/27-interchain-accounts/keeper/keeper.go
Some more interchain-accounts code cleanup / housekeeping
- Adding `ica` alias to CLI
- Updating usage of BindPort / ClaimCapability funcs
closes: #281 #289
---
> chore: interchain accounts cleanup, cli alias

- modules/apps/27-interchain-accounts/genesis.go
- modules/apps/27-interchain-accounts/module.go
- Updating interchain accounts pkg naming
closes: #363
---
> chore: updating interchain accounts pkg naming

- CHANGELOG.md
- modules/core/02-client/client/cli/cli.go
- modules/core/02-client/client/cli/query.go
- Adding client status cli query for existing grpc endpoint
closes: #369 
---
> adding client status cli query

- go.mod
- go.sum
- modules/core/02-client/keeper/client_test.go
- testing/sdk_test.go
* update SDK dependency and fix changes
Removes tests from sdk_test.go which are no longer needed to upstream changes in the SDK
Fixes client_test.go due to inclusion of the fee in tx events
* bump SDK version to v0.44.0
closes: #XXXX
---
> backport bump SDK dependency (#367)

- modules/apps/27-interchain-accounts/keeper/grpc_query.go
- modules/apps/27-interchain-accounts/keeper/grpc_query_test.go
- modules/apps/27-interchain-accounts/keeper/keeper_test.go
Removing legacy testing approach for #279 
- adding strings.TrimSpace() 
- updating grpc query tests
- removing queryClient on KeeperTestSuite
closes: #XXXX
---
> test: updating ica grpc query tests

- modules/apps/27-interchain-accounts/keeper/handshake_test.go
- modules/apps/27-interchain-accounts/keeper/keeper_test.go
- modules/apps/27-interchain-accounts/keeper/relay.go
- modules/apps/27-interchain-accounts/keeper/relay_test.go
- modules/apps/27-interchain-accounts/types/keys.go
- testing/app.go
Adding tests for `relay.go`
partially closes: #279 
---
> ICA: Adding tests for relay.go

- CHANGELOG.md
- modules/core/05-port/keeper/keeper.go
- modules/core/05-port/keeper/keeper_test.go
Making `IsBound` 05-port keeper fn public. 
closes: #288 
---
> refactor: making IsBound a public function

- modules/apps/27-interchain-accounts/keeper/relay.go
- modules/apps/27-interchain-accounts/keeper/relay_test.go
Adding tests for `OnRecvPacket` for 27-interchain-accounts. Also some minor cleanup for `TrySendTx`
partially closes: #279 
---
> test: adding tests for OnRecvPacket

- modules/apps/27-interchain-accounts/keeper/account.go
- modules/apps/27-interchain-accounts/keeper/account_test.go
- modules/apps/27-interchain-accounts/types/account.go
- modules/apps/27-interchain-accounts/types/account_test.go
- modules/apps/27-interchain-accounts/types/codec.go
- modules/apps/27-interchain-accounts/types/expected_keepers.go
- modules/apps/27-interchain-accounts/types/keys.go
- modules/apps/27-interchain-accounts/types/keys_test.go
- modules/apps/27-interchain-accounts/types/querier.go
Additional code coverage for #279 and minor cleanup including:
- Types pkg tests
- Make InterchainAccountPretty private/unexposed
- Removed `types/querier.go` (unused) 
- Enabled previously commented out test: InitInterchainAccount (IsBound)
closes: #XXXX
---
> chore: code coverage and minor cleanup

- modules/apps/27-interchain-accounts/ibc_module.go
- modules/apps/27-interchain-accounts/module.go
- testing/simapp/app.go
Follows format outlined in #307. No changes made outside of moving the functions into a new file and renaming AppModule -> IBCModule and am -> im
closes: #XXXX
---
> Split ICA module.go into module.go and ibc_module.go

- docs/ibc/proto-docs.md
- modules/apps/27-interchain-accounts/ibc_module.go
- modules/apps/27-interchain-accounts/keeper/keeper.go
- modules/apps/27-interchain-accounts/keeper/relay.go
- modules/apps/27-interchain-accounts/keeper/relay_test.go
- modules/apps/27-interchain-accounts/types/packet.go
- modules/apps/27-interchain-accounts/types/types.pb.go
- proto/ibc/applications/interchain_accounts/v1/types.proto
Doing this issue in two steps. This pr does name changes and trivially remove the TxRaw type. The next pr will modify the data type in packet data to be repeated any's thus removing TxBody type
partially closes: #449
---
> Rename IBCAccountPacketData, Remove TxRaw 

- modules/apps/27-interchain-accounts/keeper/keeper.go
- modules/apps/27-interchain-accounts/keeper/relay.go
- modules/apps/27-interchain-accounts/keeper/relay_test.go
Further simplification will be done after #456 
closes: #452 
---
> Rename DeserializeTx, enforce []sdk.Msg usage in SerializeCosmosTx

- modules/apps/27-interchain-accounts/keeper/relay.go
> Remove computeVirtualTxHash

- CHANGELOG.md
- modules/core/02-client/client/cli/tx.go
> update-client should expect 2 args

- testing/mock/ibc_module.go
- testing/mock/mock.go
- testing/simapp/app.go
Assistance for middleware work
- Split the test/mock AppModule to AppModule/IBCModule
closes: #XXXX
---
> chore: split testing/mock ibcmodule 

- CHANGELOG.md
- modules/core/02-client/keeper/keeper.go
- modules/core/02-client/keeper/keeper_test.go
- modules/core/03-connection/keeper/handshake.go
- modules/core/03-connection/keeper/verify_test.go
- modules/core/03-connection/types/expected_keepers.go
GetSelfConsensusState refactored to return an error instead of bool.
closes: #42 
---
> refactor: GetSelfConsensusState return error instead of bool

- modules/apps/29-fee/keeper/genesis_test.go
- modules/apps/29-fee/keeper/grpc_query_test.go
- modules/apps/29-fee/types/genesis.go
- modules/apps/29-fee/types/genesis_test.go
- modules/apps/29-fee/types/msgs.go
- modules/core/04-channel/types/packet.go
Adding genesis validation + tests for ics29-fee
closes: #264
---
> feat: adding genesis validation + tests

- modules/apps/27-interchain-accounts/controller/ibc_module.go
- modules/apps/27-interchain-accounts/controller/ibc_module_test.go
- modules/apps/27-interchain-accounts/controller/keeper/account.go
- modules/apps/27-interchain-accounts/controller/keeper/account_test.go
- modules/apps/27-interchain-accounts/controller/keeper/genesis.go
- modules/apps/27-interchain-accounts/controller/keeper/genesis_test.go
- modules/apps/27-interchain-accounts/controller/keeper/handshake.go
- modules/apps/27-interchain-accounts/controller/keeper/handshake_test.go
- modules/apps/27-interchain-accounts/controller/keeper/keeper.go
- modules/apps/27-interchain-accounts/controller/keeper/keeper_test.go
- modules/apps/27-interchain-accounts/controller/keeper/relay.go
- modules/apps/27-interchain-accounts/controller/keeper/relay_test.go
- modules/apps/27-interchain-accounts/host/ibc_module.go
- modules/apps/27-interchain-accounts/host/ibc_module_test.go
- modules/apps/27-interchain-accounts/host/keeper/account.go
- modules/apps/27-interchain-accounts/host/keeper/account_test.go
- modules/apps/27-interchain-accounts/host/keeper/genesis.go
- modules/apps/27-interchain-accounts/host/keeper/genesis_test.go
- modules/apps/27-interchain-accounts/host/keeper/handshake.go
- modules/apps/27-interchain-accounts/host/keeper/handshake_test.go
- modules/apps/27-interchain-accounts/host/keeper/keeper.go
- modules/apps/27-interchain-accounts/host/keeper/keeper_test.go
- modules/apps/27-interchain-accounts/host/keeper/relay.go
- modules/apps/27-interchain-accounts/host/keeper/relay_test.go
changes imports of `27-interchain-accounts/types` within the controller/host submodules to be aliased as `icatypes`. This allows the submodule to use `types` when importing its own types package
closes: #XXXX
---
> Rename imports within host/controller

- modules/apps/27-interchain-accounts/controller/ibc_module.go
- modules/apps/27-interchain-accounts/controller/ibc_module_test.go
- modules/apps/27-interchain-accounts/controller/keeper/params.go
- modules/apps/27-interchain-accounts/controller/types/errors.go
- modules/apps/27-interchain-accounts/host/ibc_module.go
- modules/apps/27-interchain-accounts/host/ibc_module_test.go
- modules/apps/27-interchain-accounts/host/keeper/params.go
- modules/apps/27-interchain-accounts/host/types/errors.go
> Disable usage of controller and host submodules based on on-chain params

- CHANGELOG.md
- modules/apps/transfer/client/cli/tx.go
In the IBC transfer cli command use the local clock time as reference time to calculate the timeout timestamp on the counter party chain if it is later than the consensus state timestamp of the counter party chain, otherwise still use consensus state timestamp as reference.
closes: #508
---
> use local clock time as reference time for timeout timestamp if later than consensus state timestamp

- modules/apps/27-interchain-accounts/controller/ibc_module_test.go
> tests: controller submodule tests for OnRecv, OnTimeout, and OnAck

- CHANGELOG.md
- modules/core/keeper/msg_server.go
We are emitting the incorrect module name during the `OnChanOpenInit` step. 
This PR updates the event to use the channel module name.. 
closes: #601 
---
> fix: emit channel event instead of connection

- CHANGELOG.md
Fixing the changelog after @crodriguezvega pointed out that I had put both the fix for #603 & the ICA v1 feature in the wrong section. I've moved them to the `Unreleased` part of the changelog. 
---
> fix: move changelog entries to unreleased section

- modules/apps/27-interchain-accounts/controller/keeper/keeper.go
- testing/simapp/app.go
> remove unnecessary AccountKeeper field in controller submodule 

- modules/apps/27-interchain-accounts/controller/keeper/account.go
- modules/apps/27-interchain-accounts/host/keeper/relay.go
Fixes an issue whereby events would be swallowed into the void due to ignoring of `sdk.Result` fields and more specifically the creation of a new `EventManager` instance within the [`sdk.Msg` router execution](https://github.com/cosmos/cosmos-sdk/blob/v0.44.5/baseapp/msg_service_router.go#L110).
We should also be aware that a new `EventManager` instance is created upon every call to [`ctx.CacheContext`](https://github.com/cosmos/cosmos-sdk/blob/v0.44.5/types/context.go#L258)
Shout out @colin-axner for helping identify the cause of the issue.
I tested the following changes using hermes and the interchain-accounts auth module. Channel handshakes are now correctly picked up by hermes channel workers and completed. 
closes: #XXXX
---
Before we can merge this PR, please make sure that all the …
> fix: correctly propagate sdk.Result events to the current ctx

- CHANGELOG.md
- go.mod
- go.sum
- modules/core/keeper/msg_server.go
Backport #589 and #603.
closes: #XXXX
---
> backport #589 #603 to v1.1.x

- CHANGELOG.md
- modules/apps/27-interchain-accounts/controller/keeper/handshake.go
- modules/apps/27-interchain-accounts/host/keeper/handshake.go
- modules/apps/27-interchain-accounts/types/expected_keepers.go
- modules/core/04-channel/keeper/handshake.go
- modules/core/04-channel/keeper/keeper.go
- modules/core/04-channel/keeper/timeout.go
In order complete 640, `ChanOpenTry` needs to remove setting of the channel. This will occur after the application callback in the message server. `CounterpartyHops` takes in the channel as an argument, but this is unnecessary. In general the `CounterpartyHops` function was unnecessary, so I removed it and replaced it with direct calls to the counterparty connection ID. 
ICS27 needs access to both connection IDs and it was using `CounterpartyHops` so I added a function which returns the connection ID and connection state associated with a channel. I'm surprised we didn't have this function before
ref: #640 
---
write a …
> remove CounterpartyHops function, add GetChannelConnection

- CHANGELOG.md
- docs/migrations/v2-to-v3.md
- modules/apps/27-interchain-accounts/controller/keeper/handshake.go
- modules/apps/27-interchain-accounts/controller/keeper/handshake_test.go
- modules/apps/27-interchain-accounts/host/keeper/handshake.go
- modules/apps/27-interchain-accounts/host/keeper/handshake_test.go
- modules/apps/27-interchain-accounts/types/expected_keepers.go
- modules/core/04-channel/keeper/handshake.go
- modules/core/04-channel/keeper/keeper.go
- modules/core/04-channel/keeper/timeout.go
- modules/core/keeper/msg_server.go
> reorganize channel handshake handler

- CHANGELOG.md
- docs/migrations/v2-to-v3.md
- modules/apps/27-interchain-accounts/controller/keeper/grpc_query.go
- modules/apps/transfer/keeper/keeper.go
- modules/apps/transfer/keeper/relay.go
- modules/apps/transfer/types/expected_keepers.go
- testing/simapp/app.go
Creates ics4Wrapper which allows middleware applications to only implement SendPacket to connect ics20 as an application in its middleware stack
closes: #XXXX
---
> allow ics20 to connect to middleware

- modules/apps/27-interchain-accounts/types/codec.go
The following PR registers the `InterchainAccount` type as an implementation of  the `x/auth` module's `GenesisAccount` interface. The `InterchainAccount` type should be registered as both the `AccountI` and `GenesisAccount` interfaces. 
See: https://github.com/cosmos/cosmos-sdk/blob/v0.44.5/x/auth/types/codec.go#L24-L38
- adding GenesisAccount interface registration for InterchainAccount implementation
closes: #673
---
> fix: register InterchainAccount as GenesisAccount

- docs/architecture/README.md
- docs/architecture/adr-002-go-module-versioning.md
- docs/architecture/adr-002-go-package-versioning.md
Covers the thought process for deciding not to support importing multiple ibc-go versions
content comes from previous comments from myself and @damiannolan 
closes: #632 
---
> ADR 002: importing multiple ibc-go versions

- CHANGELOG.md
- modules/core/keeper/msg_server.go
> simplify connection handshake error messages

- docs/.vuepress/config.js
- docs/app_modules/interchain-accounts/ica_auth.md
- modules/apps/27-interchain-accounts/controller/keeper/relay.go
- modules/apps/27-interchain-accounts/controller/keeper/relay_test.go
- modules/apps/27-interchain-accounts/types/errors.go
> refactor: allow ICA authentication module provided timeout timestamp values

- .github/workflows/release.yml
- .goreleaser.yml
Github action to build the simd binary and attach it to a release. This workflow triggers once the tag is pushed. We can continue cutting the release using Github's UI and the artifacts will be attached a few minutes later after the release is published.
closes: #482
---
> add goreleaser github action to attach simd binary to releases

- modules/apps/27-interchain-accounts/controller/keeper/relay.go
- modules/apps/27-interchain-accounts/controller/keeper/relay_test.go
- Updating `SendTx` to use `GetOpenActiveChannel()` which checks channel state
- Adding test to ensure optimistic packet sends are disallowed through ics27
closes: #784 
---
> test: ensure ics27 optimistic packet sends are disallowed

- CHANGELOG.md
- docs/migrations/v3-to-v4.md
- modules/core/04-channel/keeper/packet.go
- modules/core/04-channel/keeper/packet_test.go
- modules/core/05-port/types/module.go
- modules/core/keeper/msg_server.go
- testing/endpoint.go
- testing/mock/ack.go
Updating WriteAcknowledgement API to take `exported.Acknowledgement` type instead of `[ ] bytes` 
closes: #854 
---
> refactor: WriteAcknowledgement API

- CHANGELOG.md
- modules/apps/transfer/keeper/relay_test.go
- modules/apps/transfer/transfer_test.go
- testing/events.go
> chore: add ParsePacketFromEvents testing helper function

- modules/apps/29-fee/keeper/escrow.go
- modules/apps/29-fee/keeper/genesis.go
- modules/apps/29-fee/module.go
> nit: ics29 comments

- testing/mock/mock.go
This contains two fixes:
- the capability being claimed by the scoped keeper was incorrect (mock.ModuleName -> port ID)
- the mock module wasn't accounting for non empty genesis state in capabilities (after genesis export, capability will create the bound ports so rebinding doesn't need to happen)
closes: #XXXX
---
> fix: correctly claim capability for mock module, handle genesis exports

- modules/apps/29-fee/fee_test.go
- modules/apps/29-fee/ibc_module_test.go
- testing/simapp/app.go
- testing/values.go
Will make follow pr's with the rest of the tests (divided in bite sized chunks)
ref: #891 
---
> refactor: ics29 OnChanOpenInit callback tests now use mock module

- modules/apps/29-fee/fee_test.go
- modules/apps/29-fee/ibc_module_test.go
- modules/apps/29-fee/keeper/keeper_test.go
> chore: remove unnecessary testing functions from ics29

- .github/mergify.yml
> add backport actions for v1.3.x and v2.1.x

- modules/apps/transfer/ibc_module.go
- modules/core/04-channel/keeper/keeper.go
I was playing with the linter for CI reasons and thought I may as well fix the following lint errors that popped up. 
closes: #XXXX
---
> chore: fix mispelled words

- modules/apps/29-fee/keeper/keeper.go
- modules/apps/29-fee/types/keys.go
- modules/apps/29-fee/types/keys_test.go
> chore: add ParseKeyFeesInEscrow function

- scripts/protocgen.sh
This has really been annoying me lately. Every time we run 
`make proto-all` or specifically `make proto-gen` 
The `go.mod` file gets screwed up and requires another `make install` before it's usable (I know we'll be running make install most of the time anyway but it bothers me nonetheless). I'm not entirely sure what the root cause is but removing the go mod tidy here relieves us of this problem. 
closes: #XXXX
---
> fix: remove go mod tidy from proto-gen script

- modules/apps/29-fee/types/fee_test.go
- modules/apps/29-fee/types/msgs_test.go
- Updates ics29 `types` tests to use `types_test` pkg
- Update `types` tests to remove unnecessary vars and follow ibc-go test standard
closes: #980 
---
> test: cleanup ics29 types tests

- modules/apps/29-fee/client/cli/cli.go
- modules/apps/29-fee/client/cli/query.go
- Adding CLI query for `TotalRecvFees` rpc
ref: #871 
---
> feat: cli for query total recv fees

- modules/apps/29-fee/client/cli/query.go
- Adding CLI for query total ack fees
- Adding CLI for query total timeout fees
ref: #871 
---
> feat: CLIs for total ack and timeout queries

- modules/apps/29-fee/keeper/keeper.go
- modules/apps/29-fee/types/keys.go
- modules/apps/29-fee/types/keys_test.go
> add ParseKeyForwardRelayerAddress function + test

- docs/migrations/v2-to-v3.md
> small fixes for v2 to v3 migration

- CHANGELOG.md
- modules/core/04-channel/keeper/packet.go
Fixes incorrect param in logging on packet acknowledgement.
closes: #994 
Minor, no functional change.
> call packet.GetSequence() rather than passing the func as argument

- CHANGELOG.md
- go.mod
- go.sum
@colin-axner and I decided to to v1.3.0 with SDK 0.44, so this PR reverts back the bump to SDK 0.45.
closes: #XXXX
---
> deps: revert bump to SDK 0.45.1

- CHANGELOG.md
- docs/migrations/v2-to-v3.md
- modules/apps/27-interchain-accounts/controller/ibc_module.go
- modules/apps/27-interchain-accounts/controller/ibc_module_test.go
- modules/apps/27-interchain-accounts/host/ibc_module.go
- modules/apps/transfer/ibc_module.go
- modules/apps/transfer/ibc_module_test.go
- modules/core/05-port/types/module.go
- modules/core/keeper/msg_server.go
- testing/mock/ibc_app.go
- testing/mock/ibc_module.go
I add counterpartyChannelID as a param to IBCModule.OnChanOpenAck to support ibc module that use counterpartyChannelID in their OnChanOpenAck logic.
closes: #1075
---
> Add counterpartyChannelID param to IBCModule.OnChanOpenAck

- CHANGELOG.md
- modules/core/02-client/client/cli/tx.go
- modules/core/02-client/keeper/client.go
- modules/core/02-client/keeper/client_test.go
- modules/core/02-client/types/msgs.go
- modules/core/exported/client.go
- modules/core/keeper/msg_server.go
Removes `GetClientID()` from `Misbehaviour` interface. Client ID is already supplied in `MsgSubmitMisbehaviour`.
Closes: #874
---
> chore: Remove GetClientID() From Misbehaviour Interface

- modules/light-clients/09-localhost/types/client_state.go
Adds 668 functions to the localhost client and refactors `CheckHeaderAndUpdateState()` to use added fns. 
closes: #877 
---
> chore: add 668 functions to localhost client

- testing/coordinator.go
- testing/endpoint.go
- testing/path.go
fixes unhandled errors in the ibctesting package
---
> fix: handle testing update client errors

- modules/light-clients/06-solomachine/types/misbehaviour.go
- modules/light-clients/06-solomachine/types/update.go
- modules/light-clients/06-solomachine/types/update_test.go
- Adding `CheckForMisbehaviour` to 06-solomachine
- Adding `UpdateStateOnMisbehaviour` to 06-solomachine
ref: #878 
---
> chore: 06-solomachine adding CheckForMisbehaviour and UpdateStateOnMisbehaviour

- modules/light-clients/07-tendermint/types/update.go
- modules/light-clients/07-tendermint/types/upgrade_test.go
- Adds `UpdateStateOnMisbehaviour` to `07-tendermint` client
ref: #879 PR4
---
> chore: adding UpdateStateOnMisbehaviour to 07-tendermint

- modules/apps/27-interchain-accounts/controller/keeper/params.go
> fix typos in the controller params

- docs/.vuepress/config.js
- docs/versions
> add versions to v2.1

- CHANGELOG.md
- modules/core/02-client/legacy/v100/solomachine.go
- modules/core/exported/client.go
- modules/light-clients/06-solomachine/types/consensus_state.go
- modules/light-clients/06-solomachine/types/consensus_state_test.go
> refactor: removing GetRoot from ConsensusState interface

- CHANGELOG.md
- modules/core/02-client/keeper/proposal.go
- modules/light-clients/06-solomachine/types/proposal_handle.go
- modules/light-clients/06-solomachine/types/proposal_handle_test.go
- modules/light-clients/07-tendermint/types/proposal_handle.go
- modules/light-clients/07-tendermint/types/proposal_handle_test.go
- Set ClientState in store within `CheckSubstituteAndUpdateState`
closes: #599 
---
> chore: CheckSubstituteAndUpdateState stores client state in lightclients impl

- modules/light-clients/07-tendermint/types/proposal_handle.go
- modules/light-clients/07-tendermint/types/store.go
- modules/light-clients/07-tendermint/types/update.go
- modules/light-clients/07-tendermint/types/update_test.go
- modules/light-clients/07-tendermint/types/upgrade.go
- Set `ClientState` and `ConsensusState` in store within `07-tendermint` `UpdateState`
- Updating tests to assert against stored values in favour of return values
closes: #1190 
---
> chore: 07-tendermint set client/consensus states in UpdateState

- modules/light-clients/07-tendermint/types/client_state.go
- modules/light-clients/07-tendermint/types/misbehaviour_handle.go
- modules/light-clients/07-tendermint/types/proposal_handle.go
- modules/light-clients/07-tendermint/types/store.go
- modules/light-clients/07-tendermint/types/store_test.go
- modules/light-clients/07-tendermint/types/update.go
- modules/light-clients/07-tendermint/types/upgrade.go
- Updates the `07-tendermint` helper `GetConsensusState` to return `(*ConsensusState, bool)` in favour of `(*ConsensusState, error)`
closes: #1140 
---
> chore: update 07-tendermint GetConsensusState to return bool over error

- CHANGELOG.md
- modules/core/02-client/legacy/v100/solomachine.go
- modules/core/exported/client.go
- modules/light-clients/06-solomachine/types/update.go
- modules/light-clients/09-localhost/types/client_state.go
> feat: adding UpdateStateOnMisbehaviour to ClientState interface

- CHANGELOG.md
- modules/core/02-client/keeper/client.go
- modules/core/02-client/keeper/events.go
- modules/core/02-client/legacy/v100/solomachine.go
- modules/core/exported/client.go
- modules/light-clients/06-solomachine/types/update.go
- modules/light-clients/06-solomachine/types/update_test.go
- modules/light-clients/07-tendermint/types/update.go
- modules/light-clients/07-tendermint/types/update_test.go
closes: #668
closes: #284 
---
> Replace CheckHeaderAndUpdateState with new ClientState functions

- modules/apps/29-fee/ibc_module_test.go
- modules/apps/29-fee/keeper/escrow.go
- modules/apps/29-fee/keeper/msg_server_test.go
- modules/apps/29-fee/keeper/relay.go
- modules/apps/29-fee/types/genesis_test.go
- modules/apps/29-fee/types/keys.go
> nit: packetID var name

- CHANGELOG.md
- modules/apps/29-fee/client/cli/cli.go
- modules/apps/29-fee/client/cli/query.go
Adding CLI for getting all incentivized packets by packet-id and all packets. 
closes: #871 
How to test:
```
1. Setup two chains & create a fee enabled transfer channel. 
simd tx ibc-fee pay-packet-fee transfer channel-0 1 --recv-fee 1000stake --ack-fee 1000stake --timeout-fee 1000stake --from $DEMOWALLET_1 --home ./data/test-1 --keyring-backend test --chain-id test-1 --node tcp://localhost:16657
simd tx ibc-fee pay-packet-fee transfer channel-0 2 --recv-fee 1000stake --ack-fee 1000stake --timeout-fee 1000stake --from $DEMOWALLET_1 --home ./data/test-1 --keyring-backend test --chain-id test-1 --node tcp://localhost:16657
simd query ibc-fee packet-by-id transfer channel-0 1 --node tcp://localhost:16657
simd query ibc-fee packets --node tcp://localhost:16657
```
---
Before we can merge …
> ics29: feat: CLI query commands for packets

- CHANGELOG.md
> add changelog entry for fee middleware PR (#276)

- CHANGELOG.md
- modules/apps/transfer/keeper/genesis.go
- modules/apps/transfer/keeper/keeper.go
- modules/apps/transfer/keeper/keeper_test.go
> deprecate GetTransferAccount

- modules/apps/29-fee/keeper/escrow.go
Reduces the complexity contained in `DistributePacketFees` and `DistributePacketFeesOnAcknowledgement` in anticipation of #1251 
closes: #XXXX
---
> isolate packet fee distribution for on acknowledgement and on timeout into separate functions

- modules/apps/29-fee/ibc_module.go
- modules/apps/29-fee/keeper/escrow.go
- modules/apps/29-fee/keeper/escrow_test.go
- modules/apps/29-fee/keeper/genesis_test.go
- modules/apps/29-fee/keeper/grpc_query_test.go
- modules/apps/29-fee/keeper/keeper_test.go
- modules/apps/29-fee/keeper/msg_server_test.go
> ics29: gracefully handle escrow out of balance edge case during fee distribution

- docs/apps/interchain-accounts/transactions.md
> chore: fix dead links from sdk default branch change

- CHANGELOG.md
- modules/apps/29-fee/types/keys.go
I propose to change the version string so that it follows the same pattern that we use in [transfer](https://github.com/cosmos/ibc-go/blob/main/modules/apps/transfer/types/keys.go#L16).
closes: #XXXX
---
> change fee version string to make it consistent with transfer version

- modules/apps/29-fee/client/cli/query.go
I added the query flags to the CLI to query the counterparty address so that flag `--node` works.
closes: #XXXX
---
> add query flags to command for querying counterparty address

- modules/apps/29-fee/client/cli/query.go
Just to make it consistent with other queries that validate the packet ID (and thus return an error if sequence is 0).
closes: #XXXX
---
> add validation of packet ID in CLI to query packet

- CHANGELOG.md
- modules/apps/29-fee/keeper/keeper.go
- modules/apps/29-fee/types/keys.go
- modules/apps/29-fee/types/keys_test.go
- Rename `KeyForwardRelayerAddress` to `KeyRelayerAddressForAsyncAck`
- Rename `ParseKeyForwardRelayerAddress` to `ParseKeyRelayerAddressForAsyncAck`
closes: #1324 
---
> chore: renaming KeyForwardRelayerAddress to KeyRelayerAddressForAsyncAck

- CHANGELOG.md
- docs/client/swagger-ui/swagger.yaml
- docs/ibc/proto-docs.md
- docs/migrations/v3-to-v4.md
- modules/apps/transfer/client/cli/query.go
- modules/apps/transfer/keeper/grpc_query.go
- modules/apps/transfer/keeper/grpc_query_test.go
- modules/apps/transfer/types/query.pb.go
- proto/ibc/applications/transfer/v1/query.proto
I change the `TraceDenom` gRPC so that it takes in either an `ibc denom` or a `hash` instead of only accept `hash` as input
closes: #101
---
> chore: improve DenomTrace grpc

- docs/.vuepress/config.js
- modules/apps/29-fee/keeper/escrow.go
- modules/apps/29-fee/keeper/events.go
- modules/apps/29-fee/keeper/events_test.go
> refactor: emit cumulative fees when incentivizing a packet multiple times

- docs/client/config.json
- docs/client/swagger-ui/swagger.yaml
> add swagger for interchain accounts

- modules/apps/27-interchain-accounts/controller/ibc_middleware.go
I think this error represent ICA controller error, not ICA-auth
---
> fix: ica controller middleware error typo

- docs/ibc/overview.md
> fix(typo): IBC Overview Docs

- Makefile
When trying to backport #1416 to release/v1.5.x I run into problems with `make proto-gen`. I think the fixes in #213 will solve the problems and let me regenerate the proto files.
closes: #XXXX
---
> backport update Makefile with buf fixes (#213)

- docs/migrations/support-slashed-denoms.md
Adds a migration guide for chain developers that are upgrading from a version that does not support slashed denominations to a version that does. Only necessary if the chain has malformed trace information in its state, but recommended to run for all upgrading chains regardless.
closes: #XXXX
---
> Add slash migration guide

- modules/apps/29-fee/keeper/events.go
- modules/apps/29-fee/keeper/msg_server.go
- modules/apps/29-fee/types/events.go
- Emit event for `RegisterPayee`
- Emit event for `RegisterCounterpartyPayee`
closes: #1566 
---
> chore: ics29 fee payee event emission

- docs/.vuepress/config.js
- docs/middleware/ics29-fee/integration.md
- About middleware application stacks
- How to configure an application stack composed of `transfer` and `29-fee` 
- How to configure an application stack composed of `27-interchain-accounts` and `29-fee` with associated auth module.
ref: #1408 
---
> docs: ics29 middleware usage for app devs

- modules/apps/29-fee/keeper/events.go
Most, if not all events include the module name. Updating `incentivized_ibc_packet` event to include module name
closes: #XXXX
---
> chore: add module name to incentivized packet events

- docs/.vuepress/config.js
- docs/middleware/ics29-fee/end-users.md
> docs: adding End Users section to ics29 docs

- docs/middleware/ics29-fee/fee-distribution.md
- docs/middleware/ics29-fee/msgs.md
Addresses @AdityaSripal nits
---
> docs: nits

- modules/light-clients/07-tendermint/types/client_state.go
- modules/light-clients/07-tendermint/types/client_state_test.go
> feat: VerifyNonMembership 07-tendermint implementation

- modules/core/02-client/legacy/v100/solomachine.go
- modules/core/exported/client.go
- modules/light-clients/06-solomachine/types/client_state.go
- Adding generic proof verification methods to `exported.ClientState` interface
ref: #1145 
---
> chore: add generic proof verification methods to ClientState interface

- docs/ibc/middleware/develop.md
Adds links to the implementation of fee middleware to show examples of how to implement the callbacks and functions.
closes: #699
---
> docs: add links in middleware docs to fee middleware implementation

- CHANGELOG.md
- modules/core/02-client/types/proposal.go
- modules/core/02-client/types/proposal_test.go
> Check that client state is zeroed out for ibc client upgrade proposals

- CHANGELOG.md
- modules/core/02-client/keeper/client_test.go
- modules/light-clients/07-tendermint/types/upgrade.go
> Zero out client state before upgrading client proof

- modules/core/23-commitment/types/merkle.go
Fix typo in godoc of `types.MerkleProof.VerifyMembership()`
---------------------------------------------------------------------------------------------------------
> (core/23-commitment/types) doc: fix typo

- e2e/Makefile
- e2e/scripts/run-e2e.sh
> Build local image to run tests with `make e2e-test`

- modules/core/03-connection/keeper/handshake_test.go
> Remove leftover crossing hello tests in connection handshake

- .github/workflows/e2e-fork.yml
- .github/workflows/e2e.yaml
We will run the e2e-fork tasks, which don't involve pushing to a docker registry for dependabot PRs.
the issue can be seen in [this PR](https://github.com/cosmos/ibc-go/pull/1743)
closes: #1744
---
> Run the e2e-fork task for dependabot PRs

- .github/workflows/e2e-fork.yml
- .github/workflows/e2e.yaml
Adding the ability to trigger e2e workflows manually via `workflow_dispatch` will make debugging issues easier.
---
> Adding manual triggering of e2e via workflow dispatch

- RELEASES.md
Version matrix golang/ibc-go/SDK/tendermint
closes: #1041
---
> add version matrix

- modules/core/24-host/channel_keys.go
- Adding channel upgrade restore path and key funcs to `24-host`
closes: #1601
---
> chore: adding channel upgrade restore path and key funcs to 24-host

- CHANGELOG.md
- docs/ibc/proposals.md
- modules/core/02-client/keeper/client_test.go
- modules/core/02-client/keeper/keeper_test.go
- modules/core/02-client/types/codec_test.go
- modules/core/02-client/types/genesis_test.go
- modules/core/02-client/types/msgs_test.go
- modules/core/03-connection/types/msgs_test.go
- modules/core/genesis_test.go
- modules/core/keeper/msg_server_test.go
- modules/light-clients/07-tendermint/types/client_state.go
- modules/light-clients/07-tendermint/types/client_state_test.go
- modules/light-clients/07-tendermint/types/misbehaviour_handle_test.go
- modules/light-clients/07-tendermint/types/proposal_handle_test.go
- modules/light-clients/07-tendermint/types/update_test.go
- modules/light-clients/07-tendermint/types/upgrade.go
- modules/light-clients/07-tendermint/types/upgrade_test.go
- testing/config.go
- testing/endpoint.go
reverts cosmos/ibc-go#1768 as release v5.0.0 work is still pending
> revert:  "chore: remove refs to AllowUpdateToExpired/Frozen client booleans"

- CHANGELOG.md
- modules/core/02-client/types/codec_test.go
- modules/core/02-client/types/msgs_test.go
- modules/light-clients/06-solomachine/header_test.go
- modules/light-clients/06-solomachine/update_test.go
- testing/solomachine.go
> Add test for new diversifier for solomachine

- Makefile
As noted in #1798, the `proto-update-deps` `make` target is broken on macOS. The culprit is a `sed` command that works slightly different in its freebsd implementation. 
This PR replaces the `sed` command in the makefile target with a `perl` oneliner that is arguably easier to read and it works on both macOS and GNU systems. 
This only fixes part of the problem described in #1798 though. 
---
> fix: proto-update-deps target on macOS

- CHANGELOG.md
- This [PR](https://github.com/cosmos/ibc-go/pull/1861) was not fully correct, as it missed adding the releases that were made recently. This PR is not adding those.
- Adds also an entry for the bump to SDK 0.46.
closes: #XXXX
---
> chore: add latest releases and changelog entry for bump of SDK 0.46

- docs/architecture/adr-002-go-module-versioning.md
- docs/migrations/v5-to-v6.md
- docs/roadmap/roadmap.md
> fix: documenation for client refactor

- modules/core/02-client/keeper/events.go
- modules/core/02-client/keeper/proposal.go
- modules/core/02-client/legacy/v100/solomachine.go
- modules/core/exported/client.go
- modules/light-clients/06-solomachine/proposal_handle.go
- modules/light-clients/06-solomachine/proposal_handle_test.go
- modules/light-clients/07-tendermint/proposal_handle.go
- modules/light-clients/07-tendermint/proposal_handle_test.go
> fix: complete changes for CheckSubstituteAndUpdateState

- CHANGELOG.md
Fixing the changelog and adding 02-client refactor work to the end of each section with two spaces between to make things easier when cutting a release later. 
closes: #XXXX
---
> 02-client refactor: fix changelog

- CHANGELOG.md
- modules/apps/27-interchain-accounts/types/packet.go
- modules/apps/27-interchain-accounts/types/packet_test.go
- Use explicit `len()` check of interchain account packet data 
closes: #XXXX
---
> fix(ics27): check packet data length explicitly over nil check

- .golangci.yml
- Makefile
- e2e/testsuite/testsuite.go
- modules/apps/transfer/types/msgs.go
- modules/apps/transfer/types/trace.go
- modules/core/02-client/types/msgs.go
- modules/core/03-connection/keeper/handshake.go
- modules/core/03-connection/types/msgs.go
- modules/core/04-channel/keeper/handshake.go
- modules/core/04-channel/types/msgs.go
- modules/core/24-host/doc.go
- modules/core/keeper/msg_server_test.go
- modules/light-clients/06-solomachine/types/proof.go
- modules/light-clients/07-tendermint/types/proposal_handle.go
- modules/light-clients/07-tendermint/types/upgrade.go
- testing/simapp/export.go
- Includes changes to `Makefile` from #1892 
- Removes `gofmt` from `golang-ci-lint` in favour of `gofumpt`
To run locally:
Ensure you have `gofumpt` installed and run the specified `make` target below:
```
go install mvdan.cc/gofumpt@latest
make format
```
closes: #XXXX
---
> fix: make format and golangci-lint errors

- modules/core/02-client/keeper/client.go
- modules/core/02-client/keeper/proposal.go
- modules/core/02-client/types/errors.go
- modules/core/03-connection/keeper/keeper.go
- modules/core/03-connection/keeper/verify.go
- modules/core/04-channel/keeper/packet.go
> fix: revert unnecessary change in 02-client-refactor branch

- modules/light-clients/06-solomachine/update.go
- Updating `06-solomachine` to use `setClientState` helper in update funcs
closes: #1887 
---
> chore: use solomachine `setClientState` helper on updates

- CHANGELOG.md
- modules/core/02-client/legacy/v100/store.go
- modules/light-clients/07-tendermint/store.go
- modules/light-clients/07-tendermint/update.go
- modules/light-clients/07-tendermint/update_test.go
- Removing error return from `IterateConsensusStateAscending` 
- Updating legacy code
- Updating tests
closes: #1886 
---
> chore: remove error return in IterateConsensusStateAscending

- modules/light-clients/06-solomachine/client_state.go
- modules/light-clients/06-solomachine/client_state_test.go
- Removing solomachine consensus state nil check as it is an invalid state and should panic
- Removing test cases
closes: #1888 
---
> chore: removing solomachine consensus state nil check

- .github/workflows/release.yml
> chore: adding dockerfile and release task to release/3.2.x

- CHANGELOG.md
- modules/light-clients/06-solomachine/client_state.go
> refactor: panic on ZeroCustomFields for solo machine implementation

- e2e/fee_middleware_test.go
- e2e/testsuite/testsuite.go
Adds a timeout function which returns a default timeout value to be used when sending a packet you don't want to timeout.
closes: #XXXX
---
> E2E: Add timeout height helper function 

- e2e/testsuite/grpc_query.go
- e2e/testsuite/testsuite.go
> feat: add channel query client to e2e test suite

- .github/workflows/e2e-fork.yml
- .github/workflows/e2e-manual.yaml
- .github/workflows/e2e.yaml
- e2e/README.md
- e2e/scripts/run-e2e.sh
- e2e/testconfig/testconfig.go
Initially we used two registries to store images, `ghcr.io/cosmos/ibc-go-simd` for tags, e.g. `v2.0.0` and `ghcr.io/cosmos/ibc-go-simd-e2e` which stored images for `prs`. I think this actually makes things more convoluted and it would be simpler and easier to maintain to just store the images in a single registry.
All images will go [here](https://github.com/cosmos/ibc-go/pkgs/container/ibc-go-simd/versions) after this PR is merged.
---
> Use single registry for all images

- e2e/fee_middleware_test.go
- e2e/testvalues/values.go
> feat(test): adding test to verify invalid recipient address over incentivized channel

- .github/workflows/e2e-manual.yaml
- e2e/testsuite/testsuite.go
- e2e/transfer_test.go
> feat(test): add successful e2e transfer test

- .github/workflows/build-simd-image-from-tag.yml
- e2e/README.md
I ran into a permissions error during the e2e tests which seems to have been a result of the original images not being built on a github runner. (they had been built on my local machine). The errors only occurred when using images that were not built on a github host.
See [this failure](https://github.com/cosmos/ibc-go/runs/7807503289?check_suite_focus=true) as a reference. 
See [this passing test](https://github.com/cosmos/ibc-go/runs/7808214404?check_suite_focus=true) which uses an image built by this workflow.
The test failures no longer occurred when the same image is built using this action instead.
Note: this workflow can be run with 
```bash
gh workflow run "Build Simd Image" --ref "cian/build-image-from-tag" -f tag=v3.0.0
```
---
Before we can merge this PR, please make sure that …
> Add manually triggerable Action to build simd Docker image

- e2e/testsuite/grpc_query.go
- e2e/testsuite/testsuite.go
Will use this functionality in addressing #1965 
---
> e2e: add 02-client query client

- .github/workflows/e2e-manual.yaml
- e2e/transfer_test.go
> test: e2e test for timeout of ics20 packet

- e2e/fee_middleware_test.go
- e2e/interchain_accounts_test.go
- e2e/testsuite/grpc_query.go
Moves duplicate fee queries to `E2ETestSuite`.
- https://github.com/cosmos/ibc-go/pull/2023#discussion_r947917429
closes: #XXXX
---
> chore: moving reusable fee queries to E2ETestSuite

- .github/workflows/e2e-manual-icad.yaml
- e2e/interchain_accounts_test.go
Passing test [here](https://github.com/cosmos/ibc-go/runs/7901882397?check_suite_focus=true)
Note: the incentived channel test is expected to fail as this particular test is is using ibc-go `v3.2.0`
---
> chore: explicitly set channel version for non-incentivized ica tests

- e2e/interchain_accounts_test.go
This test is largely the same as the one added in [this pr](https://github.com/cosmos/ibc-go/pull/2023) the main difference is that the assertion on the chainB wallet is now expecting it to have the starting amount (as there are insufficient funds in the ICA account)
closes: #2048 
---
> E2E: Interchain Account failed bank transfer over incentivised channel

- README.md
We were unintentionally referencing the cosmos-sdk CI tests in our status badge. This pr updates the status badge to point at `ibc-go` and also adds an `e2e` status badge. 
This also updates the `tokei` badge, which currently seems to be broken saying 0 lines of code.
The new badges will appear as 
---
> Fixing CI status badges in README.md

- e2e/testsuite/grpc_query.go
- e2e/testsuite/testsuite.go
See #2071 for passing test usage
closes: #2113
---
> feat: add gov proposal execution for e2e testsuite

- CHANGELOG.md
- modules/apps/29-fee/keeper/msg_server_test.go
- testing/chain.go
See https://github.com/cosmos/interchain-accounts-demo/issues/129 
Adding mock module account in chain setup was assuming that the `NewTestChain` func was using a SimApp() which custom apps do not. Proper way to fund mock module at chain startup for us would be via modifying the default genesis (though we would need to modify the existing SetupChainWithGenesis to not assume the default auth/bank genesis is empty. 
I decided to take the easier route of just fixing the one test case using the mock module balance
closes: #XXXX
---
> fix: partial revert of #1942

- docs/package-lock.json
Terser insecure use of regular expressions before v4.8.1 and v5.14.2 leads to ReDoS The package terser before 4.8.1, from 5.0.0 and before 5.14.2 are vulnerable to Regular Expression Denial of Service (ReDoS) due to insecure usage of regular expressions.
Denial of Service (DoS) describes a family of attacks, all aimed at making a system inaccessible to its original and legitimate users. There are many types of DoS attacks, ranging from trying to clog the network pipes to the system by generating a large volume of traffic from many machines (a Distributed Denial of Service - DDoS - attack) to sending crafted requests that cause a system to crash or take a disproportional amount of time to process.
The Regular expression Denial of Service (ReDoS) is a type of Denial of Service attack. …
> Terser insecure use of regular expressions before v4.8.1 and v5.14.2 leads to ReDoS

- modules/apps/27-interchain-accounts/controller/keeper/msg_server_test.go
- Cleanup import aliases in ICS27 `msg_server_test.go`
closes: #XXXX
---
> chore: remove duplicate imports

- docs/apps/transfer/params.md
> chore: fix broken link to bank module spec

- modules/apps/27-interchain-accounts/controller/keeper/msg_server.go
- modules/apps/27-interchain-accounts/controller/keeper/msg_server_test.go
- modules/apps/27-interchain-accounts/module.go
- Adding `msgServer` struct to ics27 controller submodule
closes: #2229 
---
> chore: adding msgServer struct to ics27 controller

- modules/apps/27-interchain-accounts/controller/ibc_middleware.go
- modules/apps/27-interchain-accounts/controller/ibc_middleware_test.go
Add call to underlying app in `OnChanCloseConfirm` and adding relevant unit tests.
closes: #2237
---
> Adding call to underlying app to OnChanCloseConfirm

- testing/simapp/app.go
Follow up from this [comment](https://github.com/cosmos/ibc-go/pull/2220#issuecomment-1240852684).
closes: #XXXX
---
> add ica module to simulation manager

- .github/workflows/test.yml
When the e2e tests were introduced, the e2e tests were excluded from the unit tests in an incorrect fashion, which resulted in each task running *all* tests as opposed to splitting up the tests into 4 sections.
The workflow will be skipped on this PR as no go files are changed. See the [this workflow](https://github.com/cosmos/ibc-go/actions/runs/3046209446/jobs/4908745499) which ran with the changes to see the run times.
closes: #2167
---
> Fix error in Code Coverage workflow

- docs/migrations/v4-to-v5.md
- Adding API breaking change to migration docs for ICS27 `host` submodule `NewKeeper` function.
closes: #XXXX
---
> docs: updating migration docs with additional ics27 host parameter

- .github/workflows/build-simd-image-from-tag.yml
`/` is not a valid docker tag character, this PR replaces any `/` values in git tags with `-` for docker tags to ensure they are valid.
[this task](https://github.com/cosmos/ibc-go/actions/runs/3099571378/jobs/5018864254) builds an image for `release/v5.0.x`, the resulting tag is [release-v5.0.x](https://github.com/cosmos/ibc-go/pkgs/container/ibc-go-simd/42640680?tag=release-v5.0.x)
---
> Replace invalid docker tag characters

- docs/apps/interchain-accounts/parameters.md
Follow up from #2290 
closes: #XXXX
---
> docs: update default value for `allow_messages` after #2290

- modules/apps/27-interchain-accounts/client/cli/cli.go
- modules/apps/27-interchain-accounts/controller/client/cli/cli.go
- modules/apps/27-interchain-accounts/host/client/cli/cli.go
I couldn't resist doing these small changes to make the text look more consistent with the other CLIs that we have...
closes: #XXXX
---
> nit: update short description of ICA CLI commands

- docs/middleware/ics29-fee/integration.md
- docs/migrations/v3-to-v4.md
> docs: add ics29 integration for sdk module

- CHANGELOG.md
- modules/apps/29-fee/keeper/keeper.go
- testing/simapp/app.go
> chore: remove unnecessary code

- modules/core/migrations/v7/migrations.go
- modules/core/migrations/v7/migrations_test.go
- Updating future migration code to use correct package versioning
closes: #XXXX
---
> chore: updating 09-localhost migration code to v7

- modules/core/03-connection/keeper/handshake.go
I think we don't need a changelog for this, right?
closes: #45
---
> code hygiene: move call to `addConnectionToClient` up

- CHANGELOG.md
- modules/apps/27-interchain-accounts/controller/ibc_middleware_test.go
- modules/apps/27-interchain-accounts/controller/keeper/account.go
- modules/apps/27-interchain-accounts/controller/keeper/handshake.go
- modules/apps/27-interchain-accounts/controller/keeper/handshake_test.go
- modules/apps/27-interchain-accounts/controller/keeper/keeper_test.go
- modules/apps/27-interchain-accounts/controller/keeper/migrations.go
- modules/apps/27-interchain-accounts/controller/keeper/migrations_test.go
- modules/apps/27-interchain-accounts/controller/migrations/v6/migrations_test.go
- modules/apps/27-interchain-accounts/genesis/types/genesis.go
- modules/apps/27-interchain-accounts/genesis/types/genesis_test.go
- modules/apps/27-interchain-accounts/host/client/cli/query.go
- modules/apps/27-interchain-accounts/host/ibc_module_test.go
- modules/apps/27-interchain-accounts/host/keeper/genesis.go
- modules/apps/27-interchain-accounts/host/keeper/genesis_test.go
- modules/apps/27-interchain-accounts/host/keeper/handshake.go
- modules/apps/27-interchain-accounts/host/keeper/keeper_test.go
- modules/apps/27-interchain-accounts/module.go
- modules/apps/27-interchain-accounts/module_test.go
- modules/apps/27-interchain-accounts/simulation/decoder_test.go
- modules/apps/27-interchain-accounts/simulation/genesis.go
- modules/apps/27-interchain-accounts/simulation/genesis_test.go
- modules/apps/27-interchain-accounts/types/keys.go
- modules/apps/27-interchain-accounts/types/port.go
- modules/apps/27-interchain-accounts/types/port_test.go
- modules/apps/29-fee/ica_test.go
Renamed icatypes.PortPrefix to icatypes.ControllerPortPrefix & icatypes.PortID to icatypes.HostPortID
closes: #2433
---
> Renamed icatypes.PortPrefix to icatypes.ControllerPortPrefix 

- docs/migrations/v2-to-v3.md
- Updates the cosmos sdk `v0.44` doc link (discontinued) to point to `v0.45`
closes: #XXXX
---
> chore: fixing dead link to sdk v0.44 docs

- CHANGELOG.md
- modules/apps/27-interchain-accounts/host/keeper/handshake.go
- modules/apps/27-interchain-accounts/host/keeper/handshake_test.go
This Pr removes requirement for the port prefix to be "ica-controller"
This removes the "ica-controller" port prefix requirement from the icahost keeper. [The related issue](https://github.com/cosmos/ibc-go/issues/2580)
closes: #2580
---
there doesn't appear to be any docs on the needed port prefix of the ica controller
not needed in this case
> remove port prefix requirement

- README.md
> chore: small README nits for readability and usability

- modules/apps/27-interchain-accounts/controller/keeper/msg_server.go
> Removing stale comment

- CHANGELOG.md
- modules/core/04-channel/keeper/handshake_test.go
- modules/core/04-channel/keeper/packet_test.go
> removed unused variables

- .github/compatibility-test-matrices/release-v2.5.x/transfer-memo.json
- .github/compatibility-test-matrices/release-v2.5.x/transfer-params.json
- .github/compatibility-test-matrices/release-v2.5.x/transfer.json
- .github/compatibility-test-matrices/release-v3.4.x/transfer-memo.json
- .github/compatibility-test-matrices/release-v3.4.x/transfer-params.json
- .github/compatibility-test-matrices/release-v3.4.x/transfer.json
- .github/compatibility-test-matrices/release-v4.2.x/incentivized-transfer.json
- .github/compatibility-test-matrices/release-v4.2.x/transfer-memo.json
- .github/compatibility-test-matrices/release-v4.2.x/transfer-params.json
- .github/compatibility-test-matrices/release-v4.2.x/transfer.json
- .github/compatibility-test-matrices/release-v5.0.x/client.json
- .github/compatibility-test-matrices/release-v5.0.x/connection.json
- .github/compatibility-test-matrices/release-v5.0.x/incentivized-transfer.json
- .github/compatibility-test-matrices/release-v5.0.x/transfer-params.json
- .github/compatibility-test-matrices/release-v5.0.x/transfer.json
- .github/compatibility-test-matrices/release-v5.1.x/transfer-memo.json
- .github/compatibility-test-matrices/release-v5.1.x/transfer-params.json
- .github/compatibility-test-matrices/release-v6.0.x/client.json
- .github/compatibility-test-matrices/release-v6.0.x/connection.json
- .github/compatibility-test-matrices/release-v6.0.x/incentivized-transfer.json
- .github/compatibility-test-matrices/release-v6.0.x/transfer-memo.json
- .github/compatibility-test-matrices/release-v6.0.x/transfer-params.json
- .github/compatibility-test-matrices/release-v6.0.x/transfer.json
- .github/workflows/e2e-compatibility.yaml
- .github/workflows/e2e-manual-simd.yaml
- CHANGELOG.md
- RELEASES.md
- docs/.vuepress/config.js
- docs/versions
I have also splitted the transfer tests because we were hitting the 256 job limit of GitHub.
closes: #XXXX
---
> post v5.1.0 release chores

- CHANGELOG.md
- modules/light-clients/06-solomachine/misbehaviour.go
- modules/light-clients/06-solomachine/misbehaviour_test.go
closes: #2013
fix(statemachine)!: (06-solomachine) [#2744] `Misbehaviour.ValidateBasic()` now only enforces that signature data does not match when the signature paths are different.
---
> Compare signature data in misbehaviours only if path differs

- modules/core/02-client/keeper/client_test.go
- modules/core/02-client/keeper/keeper_test.go
- modules/core/02-client/legacy/v100/store.go
- modules/core/02-client/types/genesis_test.go
- modules/core/02-client/types/msgs_test.go
- modules/core/types/codec.go
- modules/light-clients/07-tendermint/misbehaviour_handle_test.go
- testing/solomachine.go
Change import aliases
closes: #1880
---
> Change smtypes and solomachinetypes alias to solomachine

- docs/apps/interchain-accounts/integration.md
- docs/middleware/ics29-fee/integration.md
- docs/migrations/v3-to-v4.md
It looks like the change of ICA controller from `IBCModule` in v3 to `Middleware` in v4 was not documented in the migration docs or in the documentation.
closes: #XXXX
---
> docs: fix migration/docs for ICA controller middleware

- .github/PULL_REQUEST_TEMPLATE.md
closes: #XXXX
The included link only worked locally, but not on actual PRs.
```bash
chore: fix bad link in PR template
```
see the [guidelines](../CONTRIBUTING.md#commit-messages) for commit messages. (view raw markdown for examples)
---
> Fixing dead link in PR template

- modules/core/04-channel/types/msgs.go
- modules/core/04-channel/types/msgs_test.go
- modules/light-clients/06-solomachine/solomachine_test.go
- testing/solomachine.go
- Allow zero-height in channel handshake msgs
- `MsgChannelOpenTry`
- `MsgChannelOpenAck`
- `MsgChannelOpenConfirm`
- `MsgChannelCloseConfirm`
- Adding mock channel handshake to `06-solomachine`
closes: #2749 #2750
```bash
```
see the [guidelines](../CONTRIBUTING.md#commit-messages) for commit messages. (view raw markdown for examples)
---
> chore: solomachine mock channel handshake, allow zero-height in channel handshake msgs

- .github/workflows/e2e-manual-icad.yaml
- v0.1.7 bumps ibc-go to v3.4.0 (from v3.3.0).
- v0.2.5 bumps ibc-go to v4.2.0 (from v4.0.0-rc2).
- v0.3.4 is deleted since it uses the same version as v0.3.5.
- v0.4.1 bumps ibc-go to v6.0.0-rc1 (from v6.0.0-alpha1).
closes: #XXXX
```bash
e2e: update icad tags for manual e2e workflow
```
---
> e2e: update icad tags for manual e2e workflow

- modules/core/02-client/types/keys.go
- modules/core/02-client/types/keys_test.go
Rejects non-ASCII plus whitespaces and slashes to get it much closer to the specifications per
https://github.com/cosmos/ibc/tree/main/spec/core/ics-024-host-requirements#paths-identifiers-separators
while here added test vectors that were previously failing. However, we still need much better specifications for how long of values are accepted.
Fixes #2269
> modules/core/02-client/types: fix clientID validation regex to conform closer to spec

- CHANGELOG.md
- modules/core/02-client/keeper/keeper.go
- modules/core/02-client/keeper/keeper_test.go
- modules/core/03-connection/keeper/keeper.go
- modules/core/03-connection/types/expected_keepers.go
- modules/core/24-host/keys.go
After discussion with @chatton, we decided every key/value set in our stores should have a corresponding `Iterate` function. That is `IterateClientStates`, `IterateConsensusStates`, etc. These should take in a prefix to determine the starting point of the iteration (allows to limit unnecessary iterations) and a callback which can accrue the desired values and exit iteration early based on optimizations. This PR renames `IterateClients` to `IterateClientStates` and adds the prefix necessary for optimized iteration
closes: #2844 
```bash
feat(api)!: rename `IterateClients` to `IterateClientStates`. The function now takes a prefix argument which may be used for prefix iteration over the client store.
feat: add `PrefixedClientStorePath` and `PrefixedClientStoreKey` functions to 24-host
``` …
> refactor: rename IterateClients to IterateClientStates, add a prefix

- README.md
- docs/.vuepress/config.js
- docs/ibc/apps/ibcmodule.md
> Change ibcprotocol.org to ibcprotocol.dev

- README.md
responding to some external feedback on making it easier to find the IDA IBC tutorials/information
```bash
chore: update README to include link to IDA docs
```
---
> chore: update README to include link to IDA

- docs/apps/interchain-accounts/legacy/integration.md
- docs/ibc/light-clients/solomachine/solomachine.md
> Fixing markdown link

- docs/ibc/integration.md
Update documentation to use diff ticks to make it very clear what lines of code need to be added. 
Skipping changelog
closes: #XXXX
```bash
```
---
> chore: use diffs to make registration more clear

- docs/ibc/light-clients/client-state.md
- docs/migrations/v6-to-v7.md
- modules/core/02-client/keeper/client.go
- modules/core/02-client/keeper/client_test.go
- modules/core/exported/client.go
- modules/light-clients/06-solomachine/client_state.go
- modules/light-clients/06-solomachine/client_state_test.go
- modules/light-clients/07-tendermint/client_state.go
- modules/light-clients/07-tendermint/client_state_test.go
- Removes setting of client and consensus state from `02-client`.
- The `06-solomachine` client module now sets the initial `ClientState` via the `Initialize` method.
- The `07-tendermint` client module now sets the initial `ClientState`, `ConsensusState` and metadata via the `Initialize` method.
- Updates godocs, v7 migration doc and light client guide to reflect the changes
closes: #2900
```bash
chore: require light clients to set the initial client state and consensus state via the client state `Initialize` method
```
---
checked off. If any of the …
> refactor: require light clients to set initial client and consensus state

- modules/light-clients/07-tendermint/update.go
- modules/light-clients/07-tendermint/update_test.go
- Moving call to consensus state pruning function above duplicate header check
- Adding test case
closes: #1207 
```bash
chore: prune expired `07-tendermint` consensus states on duplicate header updates
```
---
> chore: prune expired consensus states on duplicate header updates

- docs/architecture/adr-006-02-client-refactor.md
- docs/architecture/adr-007-solomachine-signbytes.md
- modules/light-clients/06-solomachine/client_state.go
closes: #XXXX
```bash
chore: updating adr version numbers and removing unnecessary comment in solomachine
```
---
> chore: adr version number updates and housekeeping

- docs/ibc/light-clients/proofs.md
closes: #1853 
```bash
docs: existence and non-existence proofs
```
---
> docs: existence and non-existence proofs

- modules/apps/transfer/types/transfer_authorization.go
- modules/apps/transfer/types/transfer_authorization_test.go
closes: #3012
```bash
chore: TransferAuthorization ValidateBasic now returns an error when there is a duplicate channel id
```
---
> Update TransferAuthorization ValidateBasic to return an error when there is a duplicate channel id

- docs/dev/development-setup.md
> docs: refactor contributing guidelines - add development setup

- modules/light-clients/07-tendermint/store.go
- An iterator is reassigned in `07-tendermint` while `defer iterator.Close()` is called on both. The reassignment would mean that the first iterator is not closed cleanly using `defer`.
closes: #XXXX
```bash
fix: correctly close iterator in `07-tendermint` 
```
---
> fix: correctly close iterator in `07-tendermint` 

- .golangci.yml
- docs/migrations/v6-to-v7.md
- modules/apps/27-interchain-accounts/controller/ibc_middleware_test.go
- modules/apps/27-interchain-accounts/controller/keeper/handshake_test.go
- modules/apps/27-interchain-accounts/controller/keeper/relay_test.go
- modules/apps/27-interchain-accounts/host/ibc_module_test.go
- modules/apps/27-interchain-accounts/host/keeper/handshake_test.go
- modules/core/04-channel/keeper/handshake_test.go
- modules/core/04-channel/keeper/packet.go
- modules/core/04-channel/keeper/packet_test.go
- modules/core/04-channel/keeper/timeout_test.go
- modules/core/ante/ante_test.go
- modules/core/keeper/msg_server_test.go
- testing/endpoint.go
closes: #2670 
```bash
fix(statemachine)!: change check to disallow optimistic sends
```
---
> fix: change check to disallow optimistic sends

- docs/dev/release-management.md
> docs: refactor contributing guidelines - add release management

- docs/DOCS_GUIDELINES.MD
Based off [Cosmos-SDK's](https://github.com/cosmos/cosmos-sdk/blob/main/docs/DOC_WRITING_GUIDELINES.md).
closes: #XXXX
---
> docs: refactor contributing guidelines - add docs guidelines

- .github/workflows/release.yml
- .github/workflows/test.yml
- Dockerfile
This PR updates the Dockerfile for 4.3.x to include a build argument which will be used to specify the ibc-go version.
If this PR is approved and everything works correctly, we can apply these changes to all of our release branches.
---
> Update Dockerfile for 4.3.x

- CHANGELOG.md
- modules/apps/29-fee/keeper/keeper.go
- modules/apps/transfer/keeper/keeper.go
- modules/core/02-client/keeper/keeper.go
- modules/core/02-client/migrations/v7/store.go
- modules/core/03-connection/keeper/keeper.go
- modules/core/04-channel/keeper/keeper.go
- modules/core/04-channel/keeper/keeper_test.go
- modules/light-clients/07-tendermint/store.go
This PR adds the `HasChannel` and `HasConnection` methods to reduce the amount of gas spent when checking Channel or Connection existence.
```bash
chore: Add `HasConnection` and `HasChannel` methods.
```
---
> imp(channel, connection): add Has function for ConnectionEnd and Channel

- modules/core/02-client/abci.go
- modules/core/02-client/genesis.go
- modules/core/02-client/keeper/grpc_query_test.go
- modules/core/02-client/keeper/keeper.go
- modules/core/02-client/keeper/keeper_test.go
- modules/core/02-client/keeper/migrations.go
- modules/core/02-client/migrations/v7/expected_keepers.go
- modules/core/02-client/migrations/v7/localhost.go
- modules/core/02-client/migrations/v7/localhost_test.go
- modules/core/03-connection/keeper/keeper.go
- modules/core/module.go
- modules/light-clients/09-localhost/client_state.go
- testing/simapp/app.go
- adding localhost AppModuleBasic to app.go
- adding localhost client to InitGenesis
- fixing localhost update client
closes: #3058 
```bash
chore: adding 09-localhost to client InitGenesis
```
---
> chore: adding 09-localhost to client InitGenesis

- modules/light-clients/09-localhost/client_state.go
- modules/light-clients/09-localhost/client_state_test.go
- modules/light-clients/09-localhost/localhost_test.go
- testing/simapp/app.go
- Adds unit testing for 09-localhost client
- Fix verify membership/non-membership key paths to omit prefix
closes: #XXXX
```bash
chore: adding initial localhost client testing
```
---
> chore: adding initial localhost client testing

- e2e/go.mod
- go.mod
- modules/light-clients/06-solomachine/keys.go
- modules/light-clients/07-tendermint/keys.go
- Set the light client module names 
closes: #XXXX
**NA**
---
> chore: set light client module names

- go.mod
- modules/core/02-client/keeper/client.go
- modules/core/02-client/keeper/client_test.go
- modules/core/02-client/types/params.go
- This PR prevents creation of `09-localhost` clients in `02-client`
ref: #3034 
```bash
chore: disallow localhost client creation in 02-client
```
---
> chore: disallow localhost client creation in 02-client

- .golangci.yml
> chore: silence deprecation warnings on golangci lint

- modules/core/02-client/keeper/keeper.go
Since connection handshakes are disabled for localhost connections, validate self client does not need to change (only used for connection handshakes)
closes: #XXXX
```bash
```
---
> revert: validate self client requires no changes for localhost

- modules/core/03-connection/types/msgs.go
- modules/core/03-connection/types/msgs_test.go
Adds basic checks to clientID on `MsgConnectionOpenInit` and `MsgConnectionOpenTry` basic validation.
closes: #3167 
**NA**
---
> chore: disallow multiple localhost connections

- testing/simapp/app.go
Removes params subspaces for sdk modules which have now migrated to self managed module params.
closes: #3141
```bash
chore: removing legacy params subspaces for sdk modules
```
---
> chore: removing legacy params subspaces for sdk modules

- internal/errors/errors.go
part of: #2896
This PR duplicates the errors found [here](https://github.com/cosmos/cosmos-sdk/blob/main/types/errors/errors.go) and uses the `ibc` as the module name. They will be used in a follow up PR.
N/A
---
> Add IBC module level errors

- Makefile
- scripts/linting/lint-changed-go-files.sh
- scripts/linting/lint-changed-md-files.sh
I found running the existing `make lint-fix` and `make docs-lint` take some time to run as they are currently formatting all files in the repo. This PR adds an additional command which formats only the relevant files changed.
closes: N/A
N/A
---
> Add scripts to run linting on only modified files

- scripts/linting/lint-changed-go-files.sh
There was an issue where when linting a single file, types defined in other files do not resolve correctly and linting fails. This PR makes the script lint the directory the file is in (the go package) so all types are resolved correctly.
closes: N/A
N/A
---
> Fix linting for packages

- modules/light-clients/09-localhost/client_state.go
- Replace the `store.Get` usage in [verifyNonMembership](https://github.com/cosmos/ibc-go/blob/40ca344b124a87eb6238f4162caf96d280b1135a/modules/light-clients/09-localhost/client_state.go#L130-L134) with `store.Has`
- Document in [verifyMembership](https://github.com/cosmos/ibc-go/blob/40ca344b124a87eb6238f4162caf96d280b1135a/modules/light-clients/09-localhost/client_state.go#L76) and [verifyNonMembership](https://github.com/cosmos/ibc-go/blob/40ca344b124a87eb6238f4162caf96d280b1135a/modules/light-clients/09-localhost/client_state.go#L111) that the store passed is the ibc store. 
- In `verifyMembership` and  `verifyNonMembership` use `_` as variable name for unused parameters.
- In [GetTimestampAtHeight](https://github.com/cosmos/ibc-go/blob/40ca344b124a87eb6238f4162caf96d280b1135a/modules/ …
> chore: localhost godocs and nits

- e2e/tests/interchain_accounts/localhost_test.go
- e2e/tests/transfer/localhost_test.go
- modules/core/04-channel/types/msgs.go
- modules/core/04-channel/types/msgs_test.go
- modules/light-clients/09-localhost/client_state.go
- modules/light-clients/09-localhost/client_state_test.go
- modules/light-clients/09-localhost/keys.go
- modules/light-clients/09-localhost/module.go
- Creates a sentinel proof used for localhost channels. 
- Re-add validation of proof lengths in 04-channel msg validate basic methods
closes: #3194 
**NA**
---
> chore: use sentinel proofs for localhost channels

- docs/migrations/v7-to-v7_1.md
- modules/core/04-channel/keeper/events.go
> chore: use single connection id attribute in channel events

- .github/workflows/e2e-compatibility-workflow-call.yaml
- .github/workflows/e2e-fork.yml
- .github/workflows/e2e-test-workflow-call.yml
- e2e/Makefile
- e2e/README.md
- e2e/scripts/run-e2e.sh
This PR fixes two small things with the e2e running script.
1. You now only need to provide a single argument to `make e2e-test` 
e.g.
```bash
make e2e-test test=TestMaxExpectedTimePerBlockParam
```
The entrypoint will be automatically be determined using `jq`. If `jq` is not present it will require the entrypoint to be specified as usual.
2. The logs now display as the test is running, instead of after the test finishes. This is achieved by providing a single file name rather than `./...` to `go test`.
closes: #3255
---
> Update make e2e test so that you only need the test name

- e2e/testsuite/diagnostics/diagnostics.go
As discussed with @colin-axner , we can add additional diagnostics (output of `docker inspect <containerID>`) to the collected diagnostics. This allows us to further debug docker specific issues such as ports/volumes etc.
Here is the sample output of the file that gets created
```json
{
"Id": "9482d26e7767ef39d0a41cccf37dc6def2092c9ee6827ac070b00ee3ec61b91a",
"Created": "2023-03-14T12:15:51.897440552Z",
"Path": "simd",
"Args": [
"start",
"--home",
"/var/cosmos-chain/simapp-a",
"--x-crisis-skip-assert-invariants"
],
"State": {
"Status": "running",
"Running": true,
"Paused": false,
"Restarting": false,
"OOMKilled": false,
"Dead": false,
"Pid": 56421,
"ExitCode": 0,
"Error": "",
"StartedAt": "2023-03-14T12:15:52.917082178Z",
"FinishedAt": "0001-01-01T00:00:00Z"
},
"Image": …
```
> Write docker inspect output to diagnostics

- .github/PULL_REQUEST_TEMPLATE.md
- docs/dev/project-structure.md
- docs/ibc/integration.md
> chore: fix dead links

- CHANGELOG.md
- docs/migrations/v6-to-v7.md
- testing/README.md
- testing/app.go
I think it makes sense to avoid API breaking change in our rc to final release. If we want to break API, we can do that in v8
closes: #XXXX
```bash
```
---
> fix: remove api break from SDK v0.47 bump

- .github/workflows/e2e-fork.yml
- .github/workflows/e2e.yaml
part of: #3329
This PR makes it so e2es only run when a PR is R4R
---
> Only run e2e on R4R

- .github/workflows/e2e-fork.yml
We had inadvertently broken the fork e2e workflow with #3260
Previously we were depending on the fact that CHAIN_B_TAG would default to CHAIN_A_TAG, but now as we create a default config file, we are explicitly setting `main` as the tag for CHAIN_B_TAG. If we explicitly set it to `latest` the problem should be resolved.
Running fork workflow from this branch [here](https://github.com/cosmos/ibc-go/actions/runs/4498910744)
---
> Fix fork e2e workflows

- modules/core/04-channel/types/msgs.go
- modules/core/04-channel/types/msgs_test.go
Removing proof height validation to align with adaptations made to other 04-channel msgs.
Enables support for localhost and solomachine clients
closes: #3340
---
> chore: remove proof height validation in channel upgrades msgs

- .github/workflows/e2e.yaml
As far as I understand, this should be enough to trigger the e2e tests. This pr also serves as a test for that.
closes: #3347
```bash
```
---
> fix: allow e2e tests to execute when directly opening as R4R

- modules/core/04-channel/keeper/upgrade.go
- modules/core/04-channel/keeper/upgrade_test.go
follow up nits from #3331 
---
> chore: chanUpgradeInit follow up nits

- modules/core/04-channel/keeper/grpc_query.go
- modules/core/04-channel/keeper/grpc_query_test.go
closes: #1783 
```bash
fix: handle unordered channels in `NextSequenceReceive` query
```
---
> Handle NextSequenceReceive for unordered channels.

- cmd/build_test_matrix/main.go
- e2e/tests/interchain_accounts/incentivized_test.go
Removes `RegisterCounterPartyPayee` which was duplicated on `E2ETestSuite` and makes the generation of the github matrix ordered.
closes: #XXXX
```bash
nit: Create ordered matrix output, remove duplicate suite method `RegisterCounterPartyPayee`
```
---
> nit: Create ordered matrix output, remove duplicate suite method.

- modules/core/04-channel/keeper/handshake.go
closes: #3335
```bash
nit: Use enums in channel handshake log
```
---
> Use enums in channel handshake log

- e2e/go.mod
- e2e/go.sum
- go.mod
- go.sum
The `capability/release/v1.0.x` release branch was created, and tagged with `modules/capability/v1.0.0-rc1`
The go.mod and go.sum of ibc-go/e2e are being updated to point at this rc.
Note: I needed to make [these changes](https://github.com/cosmos/ibc-go/commit/3b2773d93c581d1f1aafbad4b24e0b2d9cb84621) which can be reverted once we update to an sdk version that does not contain the capability module.
---
> Update to rc tag for capability module

- modules/light-clients/07-tendermint/consensus_state.go
> 07-tendermint: add missing interface check for `ConsensusState`

- modules/apps/transfer/types/transfer_authorization.go
This PR fixes 2 out of the 3 Improvements suggested by @fedekunze [here](https://github.com/cosmos/ibc-go/pull/3079#discussion_r1165371727).
closes: #XXXX
```bash
N/A
```
---
> transfer: small improvements to authz

- modules/core/04-channel/keeper/keeper.go
- modules/core/04-channel/keeper/upgrade.go
- modules/core/04-channel/types/channel.go
- modules/core/04-channel/types/channel_test.go
> chore: adapt the ordering subset of method to add clarity

- modules/apps/transfer/keeper/genesis_test.go
- modules/apps/transfer/keeper/keeper.go
- modules/apps/transfer/keeper/migrations_test.go
- modules/apps/transfer/keeper/relay_test.go
Addressing some more review comments
closes: #XXXX
```bash
N/A
```
---
> transfer (total escrow): some more review comments

- modules/apps/transfer/keeper/invariants.go
- modules/apps/transfer/keeper/invariants_test.go
- modules/apps/transfer/keeper/keeper.go
- modules/apps/transfer/module.go
ref: #3368  
```bash
N/A
```
---
> transfer (total escrow): add invariant for total escrow

- modules/apps/transfer/types/transfer_authorization.go
- modules/apps/transfer/types/transfer_authorization_test.go
https://github.com/cosmos/ibc-go/pull/3454#discussion_r1194876541
- Use `nil` to consume less gas and avoid potential pitfalls
- Import separation
closes: #XXXX
---
> chore: transfer authz nits

- modules/apps/transfer/keeper/keeper.go
- modules/apps/transfer/keeper/keeper_test.go
closes: #3549
```bash
N/A
```
---
> imp: do not store total escrow when amount is zero

- modules/core/04-channel/keeper/packet.go
ref: #3568 
```bash
fix(statemachine)!: 04-channel SendPacket now correctly returns `ErrClientNotFound` in favour of `ErrConsensusStateNotFound`
```
---
> fix(statemachine)!: update error returned in 04-channel SendPacket

- go.mod
- testing/simapp/simd/cmd/root.go
Remote the `tools/rosetta` dependency as it is not needed in the lib.
closes: #XXXX
```bash
deps: remove tools/rosetta from the lib
```
---
> deps: remove rosetta from the lib

- e2e/testconfig/testconfig.go
- e2e/tests/transfer/base_test.go
- e2e/tests/upgrades/upgrade_test.go
- e2e/testsuite/tx.go
- e2e/testvalues/values.go
> e2e: conditionally querying total escrow based on release version

- CHANGELOG.md
- modules/apps/29-fee/keeper/keeper.go
This reverts commit dd2c03e089cd5bf0e65a26a948b5d2fa8fca45bb.
The saving gas commit was backported to the v4.1.x line, but changing gas usage is state machine breaking as `GasUsed` is included in a transaction response hash which is in consensus. This commit reverts that change. v4.1.2 should then be retracted and replaced with v4.1.3
```bash
```
---
> Revert "Save gas on IsFeeEnabled (backport #2786) (#2814)"

- CHANGELOG.md
- modules/apps/29-fee/keeper/keeper.go
The saving gas commit was backported to the v4.2.x line, but changing gas usage is state machine breaking as `GasUsed` is included in a transaction response hash which is in consensus. This commit reverts that change. v4.2.1 should then be retracted and replaced with v4.2.2
closes: #XXXX
```bash
```
---
> Revert "Save gas on IsFeeEnabled (backport #2786) (#2815)" 

- CHANGELOG.md
- go.mod
- go.sum
> chore: add retract for v4.1.2 and v4.2.1

- modules/core/04-channel/keeper/upgrade.go
- modules/core/04-channel/keeper/upgrade_test.go
- modules/core/keeper/msg_server.go
Tweaks `WriteUpgradeInitChannel` to get the channel before updating its state.
closes: #3678 
```bash
nit: get channel before updating its state in WriteUpgradeInitChannel
```
---
> Get channel before updating its state in WriteUpgradeInitChannel

- modules/core/24-host/channel_keys.go
Adds `KeyUpgratePrefix` to the `ChannelUpgradePath` as per the [spec](https://github.com/cosmos/ibc/pull/967/files#r1183795814)
closes: #3676 
```bash
chore: align upgrade key to spec.
```
---
> Align upgrade key to spec.

- modules/core/03-connection/types/version.go
Partially addresses #3677
closes: #XXXX
```bash
chore: split orderings supported into own variable.
```
---
> chore: split orderings supported into own variable.

- testing/endpoint.go
Adds `QueryChannelUpgradeProof` to the `Endpoint` struct similar to `QueryConnectionHandshakeProof` for connections.
closes: #3722
```bash
Add QueryChannelUpgradeProof to Endpoint
```
---
> Add QueryChannelUpgradeProof.

- testing/endpoint.go
Adds `ChanUpgradeTimeout` test helper method to `Endpoint` struct
closes: #3748 
---
> chore: adding `ChanUpgradeTimeout` func to testing Endpoint

- e2e/tests/transfer/base_test.go
- e2e/tests/upgrades/upgrade_test.go
- modules/apps/27-interchain-accounts/simulation/genesis_test.go
- modules/apps/transfer/keeper/genesis_test.go
- modules/apps/transfer/keeper/grpc_query_test.go
- modules/apps/transfer/keeper/invariants_test.go
- modules/apps/transfer/keeper/keeper_test.go
- modules/apps/transfer/keeper/mbt_relay_test.go
- modules/apps/transfer/keeper/migrations_test.go
- modules/apps/transfer/keeper/relay_test.go
- modules/apps/transfer/simulation/genesis_test.go
- modules/apps/transfer/types/coin.go
- modules/core/simulation/genesis_test.go
- testing/app.go
- testing/simapp/state.go
closes: #3720 
```bash
chore: use sdkmath alias for cosmossdk.io/math
```
---
> chore: use sdkmath alias for cosmossdk.io/math

- .github/compatibility-test-matrices/main/client-chain-a.json
- .github/compatibility-test-matrices/main/client-chain-b.json
- e2e/tests/core/02-client/client_test.go
closes: #2120
```bash
e2e: add e2e test for modifying client params
```
---
> Add e2e test for modifying clientparams

- modules/apps/transfer/keeper/migrations.go
> add logging in total escrow migration

- modules/apps/transfer/module.go
A small one... Just noticed that error message did not follow the convention.
closes: #XXXX
```bash
```
---
> change error text of total escrow migration

- e2e/tests/transfer/authz_test.go
- e2e/testvalues/values.go
> e2e: fix authz invalid transfer authorisations test

- modules/core/03-connection/keeper/verify.go
- modules/core/03-connection/keeper/verify_test.go
- modules/core/04-channel/keeper/upgrade.go
- modules/core/04-channel/types/expected_keepers.go
in the process of working on https://github.com/cosmos/ibc-go/issues/3747, i noticed that the param ordering of the verify functions could be updated for readability while moving these functions to the `expected_keeper` of `04-channel`.
there are still left a few method signatures left to update, see https://github.com/cosmos/ibc-go/issues/3801.
```bash
```
---
> update 04-channel expected keepers, update method signature for verify functions

- testing/mock/ibc_app.go
- testing/mock/ibc_module.go
- testing/simapp/app.go
Adds the upgrade callback overrideable functions to mock IBCApp
ref: #3791 
---
> chore: add upgrade callback overrides for mock ibc app

- modules/apps/transfer/types/msgs.go
- modules/core/02-client/types/msgs.go
- modules/core/03-connection/types/msgs.go
- modules/core/04-channel/types/msgs.go
interfacer has been [deprecated](https://github.com/mvdan/interfacer) for a good while now and it isn't even included in the list
of linters enabled.
Removes the directives which are not needed.
closes: #XXXX
```bash
chore: Remove nolint directives for interfacer.
```
---
> chore: Remove nolint directives for interfacer.

- Dockerfile
Never has a change so tiny caused such a headache. Bumping go to use `golang:1.20` apparently caused `simd` to be compiled with a dependency on `libc` that had to be `>= 2.32`, hence the [error logs for all e2e runs](https://github.com/cosmos/ibc-go/actions/runs/5271840143/jobs/9533378201?pr=3796#step:4:98). Pretty sure the PR for bumping this didn't blow up because it was from a forked repo (running e2e from forks works okay since simd is [built from the workflow and uses ubuntu 22.04](https://github.com/cosmos/ibc-go/blob/4af67c682d9230df03047f7fdcf6a6aafbb436d3/.github/workflows/e2e-fork.yml#L45) itself)
Bumping the Dockerfile image to 22.04 solves the issue since it seems it comes with a newer version of libc. Alternatively, I'm sure an `apt-get` would also do the trick.
Note, might …
> Fix e2e libc complaints

- modules/apps/27-interchain-accounts/controller/ibc_middleware.go
- modules/apps/27-interchain-accounts/host/ibc_module.go
- modules/apps/29-fee/ibc_middleware.go
- modules/apps/transfer/ibc_module.go
- modules/core/04-channel/keeper/keeper.go
- modules/core/04-channel/keeper/upgrade.go
- modules/core/05-port/types/module.go
- testing/mock/ibc_app.go
- testing/mock/ibc_module.go
part of the work needed for #3855 
note that this PR does not actually implement the functionality of the app callbacks, it only sets up the blocker
---
> update app, middleware and 05-port modules with `ChanUpgradeTimeout` function

- modules/apps/27-interchain-accounts/controller/ibc_middleware.go
- modules/apps/27-interchain-accounts/host/ibc_module.go
- modules/apps/29-fee/ibc_middleware.go
- modules/apps/transfer/ibc_module.go
- modules/core/05-port/types/module.go
- testing/mock/ibc_app.go
- testing/mock/ibc_module.go
Similar to #3899 as pointed out in https://github.com/cosmos/ibc-go/pull/3899#pullrequestreview-1486046846
closes: #XXXX
```bash
chore: Remove error return from OnChanUpgradeRestore.
```
---
> Remove error return from OnChanUpgradeRestore.

- modules/core/04-channel/keeper/upgrade.go
- modules/core/04-channel/keeper/upgrade_test.go
see https://github.com/cosmos/ibc-go/pull/3829#discussion_r1234135797
---
> update upgrade seq comparison in `ChanUpgradeTimeout`

- go.work.example
Updates go.work.example
Assists: #3883
Assists: #3874
(let's please backport to the v50 branch)
```bash
fix: update go.work.example
```
---
[CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#pull-request-targeting)).
> add modules/capability and use go 1.20 in go.work.example

- modules/core/keeper/msg_server.go
Follow up from #3742 
closes: #XXXX
```bash
```
---
> chore: make error wrapping and logging consistent for upgrade try msg server

- e2e/tests/interchain_accounts/base_test.go
- e2e/tests/interchain_accounts/gov_test.go
- e2e/tests/interchain_accounts/groups_test.go
- e2e/tests/interchain_accounts/incentivized_test.go
- e2e/tests/interchain_accounts/localhost_test.go
- e2e/tests/upgrades/upgrade_test.go
- modules/apps/27-interchain-accounts/controller/keeper/msg_server_test.go
- modules/apps/27-interchain-accounts/controller/keeper/relay_test.go
- modules/apps/27-interchain-accounts/controller/types/msgs_test.go
- modules/apps/27-interchain-accounts/host/client/cli/tx.go
- modules/apps/27-interchain-accounts/host/client/cli/tx_test.go
- modules/apps/27-interchain-accounts/host/ibc_module_test.go
- modules/apps/27-interchain-accounts/host/keeper/keeper.go
- modules/apps/27-interchain-accounts/host/keeper/relay.go
- modules/apps/27-interchain-accounts/host/keeper/relay_test.go
- modules/apps/27-interchain-accounts/types/codec.go
- modules/apps/27-interchain-accounts/types/codec_test.go
- modules/apps/29-fee/ica_test.go
This pulls API breaking changes from #3796 to merge in a separate pr. This will reduce review diffs (no logical changes made here) and reduce conflicts when backporting #3796 as the API breaking changes cannot be backported. 
In addition, this change will be relevant for #3375 
ref #3246
```bash
imp!: Add encoding type as argument to `SerializeCosmosTx` and `DeserializeCosmosTx`
```
---
> imp!: add encoding type as argument to ICA encoding/decoding functions

- modules/core/04-channel/keeper/upgrade.go
Saw this was not currently checked in `ChanUpgradeAck`.
closes: #XXXX
```bash
chore: Add a check for connection state in ChanUpgradeAck
```
---
> Add a check for connection state in ChanUpgradeAck

- modules/core/04-channel/keeper/upgrade.go
- modules/core/04-channel/keeper/upgrade_test.go
- modules/core/04-channel/types/errors.go
closes: #3745
```bash
feat: Add ChanUpgradeOpen core handler
```
---
> Add ChanUpgradeOpen core handler.

- modules/core/04-channel/keeper/handshake.go
- modules/core/04-channel/keeper/timeout.go
- modules/core/04-channel/keeper/upgrade_test.go
- modules/core/04-channel/types/channel.go
- modules/core/04-channel/types/channel_test.go
- modules/light-clients/09-localhost/client_state_test.go
closes: #3987
Since we close the channel in several places, I created a helper function for this behaviour. There are a few other ways that we could do it that might be nicer.
```go
// don't mutate the channel, but instead return a new one
func (c Channel) Close() Channel {
c.State = CLOSED
c.FlushStatus = NOTINFLUSH
return c
}
// no modification
func CloseChannel(channel Channel) Channel {
channel.State = CLOSED
channel.FlushStatus = NOTINFLUSH
return channel
}
```
If people think this is overkill, we can just keep the re-assignments directly in-line. My concern is that it is now no longer sufficient to just modify the channel state to "close" the channel so it seems beneficial to create a function for this.
see the …
> Set channel state to NOTINFLUSH when Closing

- modules/core/04-channel/keeper/upgrade.go
- modules/core/04-channel/keeper/upgrade_test.go
- modules/core/keeper/msg_server.go
Note: in the spec this happens in the startFlushHandshake function, but since our channel writes happen separately, it needs to be added in all places that write the channel. This is a potential gotcha.
closes: #4001
---
> Set Counterparty Last Sequence Send

- modules/core/04-channel/keeper/upgrade.go
- modules/core/04-channel/keeper/upgrade_test.go
- modules/core/keeper/msg_server.go
closes: #3903
This PR replaces the AbortUpgrade function with a `MustAbortUpgrade` function which panics if an error occurs during the upgrade process.
---
> Make AbortUpgrade panic on failure

- modules/core/04-channel/keeper/packet.go
- modules/core/04-channel/keeper/packet_test.go
closes: #3878 and #3877
pending spec merge.
```bash
chore: amend AcknowledgePacket to allow flushing of pre-upgrade packets
```
---
> Amend AcknowledgePacket to handle flushing

- docs/.vuepress/config.js
Updates are to vuepress's config file to change links in footer of the [docs site](https://ibc.cosmos.network/):
- Updated footer links to add in CometBFT docs, and label Tendermint Core docs as archived (should probably still be linked to for a while still)
- Changed youtube link to https://www.youtube.com/@interchain_io/featured. Cosmos youtube channel is no longer maintained
- Removed link to interchain.berlin. Added link to interchain.io
> Update footer links on Docs site

- modules/apps/29-fee/ica_test.go
`buildInterchainAccountsPacket` has an unused `seq` parameter. This PR implements the use of this parameter in the intended manner.
```bash
nit(fee.test): fix unused parameter in 'buildInterchainAccountsPacket'
```
---
> nit(fee.test): fix unused parameter in 'buildInterchainAccountsPacket'

- modules/core/keeper/msg_server.go
> chore: adding callback for OnChanUpgradeRestore in abort scenarios

- modules/core/04-channel/keeper/upgrade.go
- modules/core/04-channel/keeper/upgrade_test.go
Fixes a bug raised by Luca Joss in the shared ibc-go-rs channel.
Rename to `proofCounterpartyChannel` to align with the rest.
closes: #XXXX
```bash
fix: pass counterparty portid, channelid.
```
---
> Pass in counterparty portID, channelID when verifying channel in ChanUpgradeOpen.

- e2e/tests/transfer/authz_test.go
- modules/core/04-channel/types/acknowledgement_test.go
- modules/light-clients/08-wasm/keeper/grpc_query.go
- modules/light-clients/08-wasm/keeper/keeper.go
- modules/light-clients/08-wasm/keeper/msg_server.go
- modules/light-clients/08-wasm/types/client_state.go
- modules/light-clients/08-wasm/types/consensus_state.go
- modules/light-clients/08-wasm/types/errors.go
- modules/light-clients/08-wasm/types/gas_register.go
- modules/light-clients/08-wasm/types/header.go
- modules/light-clients/08-wasm/types/misbehaviour.go
- modules/light-clients/08-wasm/types/proposal_handle.go
- modules/light-clients/08-wasm/types/store.go
- modules/light-clients/08-wasm/types/upgrade.go
closes: #4041 
```bash
```
---
>  Migrated the errors to new package

- modules/core/04-channel/keeper/upgrade_test.go
:broom: 
closes: #XXXX
```bash
chore: remove manual setting of flush status
```
---
> Remove manual setting of flush status in ChanUpgradeOpen

- .github/workflows/test.yml
> Amend CI testing to not build on arm, correctly cross compile on arm64.

- Dockerfile
- Makefile
Mirrors the Dockerfile currently used for `wasmd`. Based on `alpine`, grabs the static library for libwasm and builds ibc-go with it. Ideally most of these can be plucked and used in `main` beforehand but opening this first.
closes: #XXXX
```bash
```
---
> Fix Dockerfile build issues.

- modules/core/04-channel/keeper/upgrade.go
- modules/core/04-channel/keeper/upgrade_test.go
Same as #4052, found after running all tests with distinct channel ids.
closes: #XXXX
```bash
bug: pass counterparty portID, channelID in UpgradeCancel.
```
---
> Pass counterparty portID, channelID in UpgradeCancel

- modules/light-clients/08-wasm/keeper/genesis.go
- modules/light-clients/08-wasm/keeper/keeper.go
- modules/light-clients/08-wasm/keeper/msg_server.go
closes: #3963 
```bash
```
---
> Merge `storeWasmCode` and `importWasmCode` functions

- modules/apps/29-fee/ibc_middleware.go
- modules/apps/29-fee/ibc_middleware_test.go
- modules/apps/29-fee/types/metadata.go
- modules/apps/29-fee/types/metadata_test.go
- testing/chain.go
- testing/simapp/test_helpers.go
- Adds the `OnChanUpgradeInit` handler to `29-fee`.
- Testing library changes are cherry-picked from #4018 
**NOTE**: this omits the allowance of the empty string which is used in the opening handshake to automatically select the version if none is provided by the client.
ref: #1900
---
> feat: adding `OnChanUpgradeInit` handler implementation to `29-fee`

- modules/light-clients/08-wasm/keeper/keeper.go
- modules/light-clients/08-wasm/types/errors.go
Pins the code after upload for the 08-wasm client. If it fails to pin, returns a new type `ErrPinContractFailed` error with the message "pinning contract failed"
closes: #4087
```bash
```
---
> Pin code to the wasm VM cache

- modules/core/04-channel/keeper/upgrade.go
- modules/core/04-channel/keeper/upgrade_test.go
> Use counterparty connection hops when verifying channel state

- modules/core/04-channel/keeper/upgrade_test.go
Testing some (still) untested functions.
closes: #XXXX
```bash
chore: add tests for writeupgradecancel.
```
---
> Add tests for WriteUpgradeCancel.

- modules/core/04-channel/keeper/packet_test.go
- modules/core/04-channel/keeper/upgrade_test.go
- modules/core/keeper/msg_server.go
- modules/core/keeper/msg_server_test.go
closes: #4030 
```bash
chore: move channel to open if all in-flight packets have been flushed in UpgradeAck.
```
---
> Move channel to OPEN if all in-flight packets have been flushed in UpgradeAck.

- modules/apps/27-interchain-accounts/controller/keeper/handshake.go
- modules/apps/27-interchain-accounts/controller/keeper/keeper.go
- modules/apps/27-interchain-accounts/host/keeper/handshake.go
- modules/apps/27-interchain-accounts/host/keeper/keeper.go
- modules/core/04-channel/keeper/handshake.go
- modules/core/04-channel/keeper/timeout.go
- modules/core/04-channel/types/channel.go
Add IsOpen and IsClosed methods to Channel. 
closes: #4152
```bash
imp: adding `IsOpen` and `IsClosed` methods to Channel type (#4152)
```
---
> imp: adding `IsOpen` and `IsClosed` methods to Channel type (#4152)

- modules/apps/transfer/ibc_module.go
- modules/apps/transfer/ibc_module_test.go
Adds the checks needed in `transfer` for upgrading channels.
ref: #4127
---
> feat: adding `OnChanUpgradeInit` implementation to transfer

- modules/core/keeper/msg_server.go
closes: #4125 
```bash
chore: call application callback after writing state in Cancel and Timeout
```
---
> Call application callback after writting state in Cancel and Timeout.

- modules/core/04-channel/keeper/upgrade.go
> add helper function to clear state stored during an upgrade

- modules/core/04-channel/types/upgrade.go
- modules/core/04-channel/types/upgrade_test.go
- modules/core/keeper/msg_server.go
> add `IsUpgradError` func for readability

- modules/apps/transfer/ibc_module.go
Error formatting comments were raised in #4126 for channel upgrades callbacks.
This PR addresses error formatting of the channel opening handshake on `main`.
---
> chore: standardise error formatting in transfer handshake callbacks

- modules/apps/27-interchain-accounts/host/keeper/relay_test.go
- modules/apps/transfer/ibc_module_test.go
- modules/apps/transfer/keeper/invariants_test.go
- modules/apps/transfer/keeper/keeper_test.go
- modules/apps/transfer/keeper/mbt_relay_test.go
- modules/apps/transfer/keeper/migrations_test.go
- modules/apps/transfer/keeper/msg_server_test.go
- modules/apps/transfer/keeper/relay_test.go
- modules/apps/transfer/transfer_test.go
- testing/path.go
closes: #4162 
```bash
test: create a NewTransferPath function in path and remove duplicate definitions
```
---
> Add NewTransferPath in testing.

- modules/light-clients/08-wasm/keeper/keeper.go
wonder why the linter is catching this.
closes: #XXXX
```bash
chore: fix wrapf warning after pinning
```
---
> Fix wrapf warning after Pinning

- modules/core/04-channel/keeper/events.go
- testing/events.go
removed `//nolint:staticcheck` from deprecated tags
closes: #4143
```bash
```
---
> refactor: removed //nolint:staticcheck from deprecated tags

- modules/core/04-channel/keeper/upgrade.go
> make connection lookup calls consistent in 04-channel

- modules/light-clients/08-wasm/types/client_state.go
- modules/light-clients/08-wasm/types/store.go
- modules/light-clients/08-wasm/types/upgrade.go
closes: #4010
```bash
chore: replace GetConsensusState with HasConsensusState
```
---
> Use hasConsensusState instead of GetConsensusState

- modules/apps/27-interchain-accounts/genesis/types/genesis_test.go
They weren't executing.
closes: #XXXX
```bash
nit: Run ica genesis/types tests.
```
---
> Run ica genesis/types tests.

- modules/core/02-client/types/params.go
> use collections contains when checking client type is in allow list

- modules/light-clients/08-wasm/types/client_state.go
- modules/light-clients/08-wasm/types/misbehaviour_handle.go
- modules/light-clients/08-wasm/types/update.go
Switches the relevant ClientState functions that query to use wasmQuery.
closes: #4105 
```bash
chore: use wasmQuery with querying functions of ClientState.
```
---
> Use wasmQuery for the rest of the query functions.

- modules/apps/27-interchain-accounts/types/metadata.go
- modules/core/03-connection/types/version.go
closes: #XXXX
```bash
nit: use collections.Contains when checking for supported encoding, tx and feature.
```
---
> Use collections.Contains in metadata, version.

- .github/compatibility-test-matrices/main/client-chain-a.json
- .github/compatibility-test-matrices/main/client-chain-b.json
- .github/compatibility-test-matrices/main/ica-chain-a.json
- .github/compatibility-test-matrices/main/ica-chain-b.json
- .github/compatibility-test-matrices/release-v6.1.x/client-chain-a.json
- .github/compatibility-test-matrices/release-v6.1.x/client-chain-b.json
- .github/compatibility-test-matrices/release-v6.1.x/ica-chain-a.json
- .github/compatibility-test-matrices/release-v6.1.x/ica-chain-b.json
- .github/compatibility-test-matrices/release-v6.2.x/client-chain-a.json
- .github/compatibility-test-matrices/release-v6.2.x/client-chain-b.json
- .github/compatibility-test-matrices/release-v6.2.x/ica-chain-a.json
- .github/compatibility-test-matrices/release-v6.2.x/ica-chain-b.json
- .github/compatibility-test-matrices/release-v7.2.x/client-chain-a.json
- .github/compatibility-test-matrices/release-v7.2.x/client-chain-b.json
- .github/compatibility-test-matrices/release-v7.2.x/ica-chain-a.json
- .github/compatibility-test-matrices/release-v7.2.x/ica-chain-b.json
- .github/compatibility-test-matrices/release-v7.3.x/client-chain-a.json
- .github/compatibility-test-matrices/release-v7.3.x/client-chain-b.json
- .github/compatibility-test-matrices/release-v7.3.x/ica-chain-a.json
- .github/compatibility-test-matrices/release-v7.3.x/ica-chain-b.json
- .github/compatibility-test-matrices/unreleased/client.json
- .github/compatibility-test-matrices/unreleased/ica.json
> e2e: add missing params tests to CI

- modules/apps/transfer/ibc_module.go
- modules/apps/transfer/ibc_module_test.go
- Adding `OnChanUpgradeAck` implementation to transfer.
This should complete the below issue, I will add additional tests for no-op methods (restore, open) in a follow-up PR.
ref: #4127 
---
> feat: implement `OnChanUpgradeAck` for transfer

- .golangci.yml
Remove the dogsled feature as discussed in linter call, also remove some unnecessary setting for linters we don't use anymore.
closes: #XXXX
```bash
chore: remove dogled, settings for linters not used.
```
---
> Remove dogsled, clean up .golangci unused settings.

- modules/light-clients/08-wasm/keeper/keeper.go
Disallowing the re-assignment breaks testing since we create many testing chains ([ref](https://github.com/cosmos/ibc-go/actions/runs/5737304988/job/15548678710?pr=4222#step:4:154)). Changed to allow a different but deeply equal VM to be assigned. 
Opened #4235 to eventually discuss this.
```bash
chore: allow re-assignment of vm if new vm is equal.
```
---
> Allow same VM to be assigned to the global vm.

- modules/light-clients/08-wasm/types/client_state.go
- modules/light-clients/08-wasm/types/errors.go
As it done with SubMessages. This is an inital restriction that can easily be relaxed in a non-api-breaking way in the future.
closes: #4214 
```bash
chore: Disallow events, attributes to be returned from a contract
```
---
> Disallow events, attributes being returned from a contract.

- modules/core/04-channel/keeper/keeper.go
- modules/core/04-channel/keeper/upgrade.go
- modules/core/04-channel/keeper/upgrade_test.go
Additionally moves the function to the keeper (and amends the tests that were checking for this deletion)
closes: #4234 
```bash
chore: delete counterparty upgrade in deleteUpgradeInfo
```
---
> Delete counterparty upgrade in deleteUpgradeInfo

- .github/workflows/golangci.yml
As a chronic linter, I wasn't able to make commits because I had a newer version of golangci-lint on my laptop :). 
This PR updates the version of golangci-lint used in the IBC-go ci system, and therefore its pre-commit hook. 
```bash
deps: bump golangci
```
---
> deps: bump golangci

- modules/core/04-channel/keeper/upgrade.go
- modules/core/04-channel/keeper/upgrade_test.go
Moves the verification into try, adds a test case that covers verification of counterparty channel.
closes: #4253 
```bash
chore: call verification functions in chanupgradetry.
```
---
> call verification of counterparty channel, upgrade in upgradetry.

- modules/core/04-channel/keeper/upgrade.go
- modules/core/04-channel/keeper/upgrade_test.go
clone of #4310 but for Ack + tests that hit the verification failure case.
closes: #4254 
```bash
chore: Add verification calls for Upgrade, Channel in ChanUpgradeAck.
```
---
> Add verification calls for Upgrade, Channel in ChanUpgradeAck.

- testing/endpoint.go
I wonder how long that's been there :smile: 
closes: #4318 
```bash
```
---
> testing: fix usage on TimeoutPacket to use counterparty portID/channel ID on nextSeqRecv query

- testing/endpoint.go
closes: #4308 
```bash
chore: Add ChanUpgradeConfirm to testing endpoint.
```
---
> Add ChanUpgradeConfirm to endpoint.

- modules/core/04-channel/keeper/upgrade.go
- modules/core/04-channel/keeper/upgrade_test.go
closes: #4255 
Pending the merging of PRs that add them in Try/Ack
```bash
chore: remove verification calls in startFlushUpgradeHandshake
```
---
> Remove verification calls in startFlushUpgradeHandshake

- modules/light-clients/08-wasm/types/client_state.go
- modules/light-clients/08-wasm/types/proposal_handle.go
- modules/light-clients/08-wasm/types/update.go
- modules/light-clients/08-wasm/types/upgrade.go
- modules/light-clients/08-wasm/types/vm.go
Does a couple of things that seemed sensible to me:
- Move `wasmQuery` and `wasmCall` into `vm`, these are shared across files and them being in `client_state` mostly served to making me struggle to remember where they were.
- `any` -> Concrete type.
- Add `wasmInit` in a similar vein. Now all `wasm*` functions take the concrete msg, marshal it, call into their own respective functions and then handle the error.
closes: #XXXX
```bash
chore: normalize internal api for calling/querying contracts.
```
---
checked off. If any of the checklist items …
> Clean up vm entry points

- modules/apps/callbacks/callbacks_test.go
- modules/apps/callbacks/fee_transfer_test.go
- modules/apps/callbacks/ibc_middleware_test.go
- modules/apps/callbacks/ica_test.go
- modules/apps/callbacks/testing/simapp/ante_handler.go
- modules/apps/callbacks/testing/simapp/app.go
- modules/apps/callbacks/testing/simapp/contract_keeper.go
- modules/apps/callbacks/testing/simapp/encoding.go
- modules/apps/callbacks/testing/simapp/export.go
- modules/apps/callbacks/testing/simapp/genesis.go
- modules/apps/callbacks/testing/simapp/genesis_account.go
- modules/apps/callbacks/testing/simapp/params/amino.go
- modules/apps/callbacks/testing/simapp/params/doc.go
- modules/apps/callbacks/testing/simapp/params/encoding.go
- modules/apps/callbacks/testing/simapp/params/proto.go
- modules/apps/callbacks/transfer_test.go
> Duplicate SimApp into callbacks directory

- modules/apps/callbacks/callbacks_test.go
- modules/apps/callbacks/export_test.go
- modules/apps/callbacks/fee_transfer_test.go
- modules/apps/callbacks/ibc_middleware.go
- modules/apps/callbacks/ibc_middleware_test.go
- modules/apps/callbacks/ica_test.go
- modules/apps/callbacks/testing/simapp/app.go
- modules/apps/callbacks/types/callbacks.go
- modules/apps/callbacks/types/callbacks_test.go
- modules/apps/callbacks/types/events.go
- modules/apps/callbacks/types/events_test.go
- modules/apps/callbacks/types/export_test.go
This PR:
closes: https://github.com/cosmos/ibc-go/issues/4295
```text
imp(callbacks): remove reconstructed packet logic from 'SendPacket'
```
---
> imp(callbacks): remove reconstructed packet logic from 'SendPacket'

- modules/core/04-channel/keeper/upgrade.go
- modules/core/04-channel/keeper/upgrade_test.go
Adds the check that the counterparty timeout hasn't elapsed on Ack + tests.
closes: #4259 
```bash
chore: check counterparty timeout hasn't elapsed on ChanUpgradeAck
```
---
> Check counterparty timeout hasn't elapsed in ChanUpgradeAck.

- modules/core/04-channel/keeper/export_test.go
- modules/core/04-channel/keeper/upgrade.go
- modules/core/04-channel/keeper/upgrade_test.go
closes: #4250
closes: #4252
This PR removes `checkUpgradeForCompatibility` from `startFlushUpgradeHandshake` as well as moving the upgrade sequence fast forwarding logic to its own function. This logic is also executed in the ACK keeper function as it was missed in #4285
The tests which are being removed tested the now removed logic from `startFlushUpgradeHandshake`
---
> Add functions checkForUpgradeCompatibility and syncUpgradeSequence

- modules/core/04-channel/keeper/events.go
- modules/core/04-channel/keeper/upgrade.go
- modules/core/04-channel/types/events.go
The relevant writes [in the spec](https://github.com/cosmos/ibc/blob/main/spec/core/ics-004-channel-and-packet-semantics/UPGRADES.md):
```typescript
// if there are no in-flight packets on our end, we can automatically go to FLUSHCOMPLETE
if pendingInflightPackets(portIdentifier, channelIdentifier) == nil {
channel.state = FLUSHCOMPLETE
provableStore.set(channelPath(portIdentifier, channelIdentifier), channel)
} else {
privateStore.set(counterpartyUpgradeTimeout(portIdentifier, channelIdentifier), timeout)
}
```
closes: #4245 
```bash
chore: add WriteUpgradeConfirm function.
```
---
Before we can merge this PR, please make sure …
> Add WriteUpgradeConfirm function.

- modules/light-clients/08-wasm/client/cli/tx.go
- modules/light-clients/08-wasm/keeper/keeper_test.go
- modules/light-clients/08-wasm/module.go
- modules/light-clients/08-wasm/types/client_message.go
- modules/light-clients/08-wasm/types/client_state.go
- modules/light-clients/08-wasm/types/consensus_state.go
- modules/light-clients/08-wasm/types/proposal_handle.go
- modules/light-clients/08-wasm/types/types_test.go
- modules/light-clients/08-wasm/types/validation_test.go
pleases the linter
closes: #XXXX
```bash
chore: if anything, this PR was definitely a chore
```
---
> Make linter happy for 08-wasm

- modules/apps/callbacks/testing/simapp/app.go
- testing/simapp/app.go
This PR fixes the inline docs on;
closes: #XXXX (I'll create the issue in a bit)
```bash
docs(simapp): fixed inline middleware wiring comments
```
---
> docs(simapp): fixed inline middleware wiring comments

- modules/core/04-channel/keeper/packet.go
- modules/core/04-channel/keeper/packet_test.go
closes: #4383 
```bash
chore: amend sendpacket to remove flush status check.
```
---
> Remove check on flush status for send packet.

- modules/apps/27-interchain-accounts/module.go
- modules/apps/29-fee/module.go
- modules/apps/transfer/module.go
- modules/core/module.go
- testing/simapp/simd/cmd/root.go
closes: #4217
This PR implements `appmodule.AppModule` interface for ibc-go modules (except `capability`, it was already implemented). 
Also introduces some cleanups related to basic manager.
> Implement appmodule.AppModule interface for ibc-go packages' modules

- modules/apps/callbacks/ibc_middleware_test.go
This PR modifies `TestProcessCallback` so that it checks whether or not `processCallback` consumes the correct amount of gas in each test case.
closes: #4331 
```text
test(callbacks): checking that processCallback consumes gas
```
---
> test(callbacks): checking that processCallback consumes gas

- .github/workflows/golangci.yml
- Makefile
- modules/apps/transfer/simulation/genesis_test.go
This PR bumps:
* proto builder image
* golangci-lint
```bash
deps: bump proto builder image and golangci-lint
```
---
> deps: proto image builder and golangci-lint

- modules/core/04-channel/keeper/events.go
- modules/core/04-channel/keeper/packet.go
- modules/core/04-channel/keeper/packet_test.go
- modules/core/04-channel/keeper/upgrade.go
- modules/core/04-channel/keeper/upgrade_test.go
- modules/core/keeper/msg_server.go
- testing/endpoint.go
> refactor: acknowledgePacket handling flushing / flush complete state 

- modules/core/04-channel/keeper/events.go
- modules/core/04-channel/keeper/upgrade_test.go
- modules/core/04-channel/types/events.go
~Don't review until: #4438 is merged as it is changing fields that are emitted in the events.~
closes: #4422
---
> Update error receipt event emission to use correct event type

- docs/middleware/callbacks/gas.md
- docs/middleware/callbacks/integration.md
- modules/apps/27-interchain-accounts/controller/ibc_middleware_test.go
- modules/apps/29-fee/ibc_middleware_test.go
- modules/apps/callbacks/ibc_middleware_test.go
- modules/apps/callbacks/testing/simapp/app.go
See [comment](https://github.com/cosmos/ibc-go/pull/4370/files#r1298283377).
closes: #XXXX
```bash
```
---
> chore: cast to `ICS4Wrapper`

- modules/apps/callbacks/fee_transfer_test.go
- modules/apps/callbacks/ica_test.go
- modules/apps/callbacks/transfer_test.go
There were unused params in test functions.
closes: #XXXX
```bash
nit(callbacks): removed unused parameters in testing functions
```
---
> nit(callbacks): removed unused parameters in testing functions

- modules/core/04-channel/keeper/packet_test.go
Using `expError` since `expResult` didn't make as much sense here considering we don't have as much post state to check for, diffs are a mess.
closes: #4448 
```bash
chore: refactor RecvPacket tests to check for the expected error.
```
---
> Refactor recvPacket tests to use expError.

- modules/core/04-channel/keeper/keeper.go
- modules/core/04-channel/keeper/upgrade_test.go
- modules/core/24-host/channel_keys.go
> refactor: remove counterparty last sequence send state entry

- modules/core/04-channel/keeper/upgrade.go
Noticed while looking through the code, we can omit writing in the case where the channel state doesn't change.
```bash
nit: don't write channel to state when it isn't modified.
```
---
> Don't write channel to state when not modified.

- modules/core/04-channel/keeper/packet.go
- modules/core/04-channel/keeper/packet_test.go
closes: #4447
```bash
chore: Allow receiving of packets if the counterparty latest sequence send has not been set 
```
---
> Allow receiving of packets if the counterparty latest sequence send has not been set

- docs/.vuepress/config.js
- docs/migrations/v7_1-to-v7_3.md
- docs/migrations/v7_2-to-v7_3.md
> docs: migration docs for v7.3

- .github/mergify.yml
I've decided that the backport should be from `main` instead of `v7.3.x` as we contemplated since you don't need to follow a trail of PRs to see where a given PR was backported to. This is more clean and consistent with our other backport tags imo.
closes: #XXXX
```text
chore: adding callbacks/release/v0.1.x+ibc-go-v7.3.x backport action to mergify
```
---
> chore: adding callbacks/release/v0.1.x+ibc-go-v7.3.x backport action to mergify

- modules/apps/29-fee/ibc_middleware.go
- modules/apps/29-fee/ibc_middleware_test.go
> refactor: implementation for onChanUpgradeAck ics29

- docs/middleware/callbacks/interfaces.md
- modules/apps/callbacks/types/expected_keepers.go
closes: #4509 
```text
docs(callbacks): improved godocs for ContractKeeper state reversion
```
---
> docs(callbacks): improved godocs for ContractKeeper state reversion

- modules/core/keeper/msg_server.go
- modules/core/keeper/msg_server_test.go
closes: #4500 
requires #4499 
```bash
```
---
> Add implementation for recover client on message server.

- docs/.vuepress/config.js
- docs/ibc/capability-module.md
closes: #4025 
```bash
```
---
> docs: move capability modules's readme to docs

- e2e/relayer/relayer.go
- e2e/sample.config.yaml
- e2e/testsuite/testconfig.go
- e2e/testsuite/testsuite.go
Ref: #4485
Not being able to configure the relayer image was a pain, so this change should allow it!
---
> Allow specifying of relayer image

- .github/PULL_REQUEST_TEMPLATE.md
- docs/apps/transfer/metrics.md
- docs/dev/project-structure.md
- docs/ibc/apps.md
- docs/ibc/apps/apps.md
- docs/ibc/integration.md
- docs/ibc/overview.md
- docs/ibc/relayer.md
- docs/middleware/ics29-fee/fee-distribution.md
The SDK refactored their docs: https://github.com/cosmos/cosmos-sdk/pull/17459
closes: #XXXX
```bash
docs: fixed broken links from cosmos-sdk
```
---
> docs: fixed broken links from cosmos-sdk

- modules/core/02-client/types/msgs.go
- modules/core/02-client/types/msgs_test.go
> feat: add unpack inerfaces message assertion to ibc software upgrade msg

- docs/architecture/adr-026-ibc-client-recovery-mechanisms.md
- docs/ibc/proposals.md
ref: #3672 
closes #4584 
```bash
```
---
> docs: use MsgRecoverClient in docs

- modules/apps/29-fee/keeper/msg_server.go
`PayPacketFeeAsync` was incorrectly called `PayPacketFee`
closes: #XXXX
```bash
docs(fee): fixed 'PayPacketFeeAsync' godocs
```
---
> docs(fee): fixed 'PayPacketFeeAsync' godocs

- modules/light-clients/08-wasm/module.go
> chore: implement `appmodule.AppModule` interface

- docs/migrations/v7-to-v8.md
ref: #4544
The code changes (adding `authority` field) are already in the docs, so this PR just adds a note about Params now being self managed.
---
> Aadding note about Params being self managed

- docs/apps/transfer/messages.md
closes: #3008 
```text
docs: added documentation on ICS-20 memo field
```
---
> docs: added documentation on ICS-20 memo field

- e2e/scripts/run-e2e.sh
closes: #4600
Quick fix for the e2e script. The existing logic had good intentions but did work 😓 
---
> Fix run-e2e.sh

- modules/capability/CHANGELOG.md
Adds a basic changelog to mod/capability
---
> chore: adding changelog to mod/capability

- e2e/go.mod
- e2e/go.sum
- go.mod
- go.sum
- modules/apps/callbacks/go.mod
- modules/apps/callbacks/go.sum
- modules/capability/go.mod
- modules/capability/go.sum
This PR updates cosmos-sdk to the latest commit of v0.50.x
```bash
deps: bump cosmos-sdk
```
---
> deps: bump cosmos-sdk

- modules/apps/callbacks/testing/simapp/app.go
`NewClientProposalHandler` was removed as part of https://github.com/cosmos/ibc-go/pull/4620/
closes: #XXXX
```bash
fix(callbacks/simapp): removed 'NewClientProposalHandler'
```
---
> fix(callbacks/simapp): removed 'NewClientProposalHandler'

- docs/ibc/apps.md
- docs/ibc/apps/apps.md
Intro is now 00-intro.md
```bash
docs: fix link to building modules docs
```
---
> docs: fix dead links

- .github/workflows/check-docs.yml
- .github/workflows/deploy-docs.yml
**This PR targets `feat/migrate-fully-to-docusaurus` branch.**
This is the final step needed in the feature branch before opening a PR to main.
closes: #XXXX
```text
ci: switched to docusaurus check and deploy workflows
```
---
> ci: switched to docusaurus check and deploy workflows

- .github/PULL_REQUEST_TEMPLATE.md
- docs/apps/transfer/metrics.md
- docs/dev/project-structure.md
- docs/ibc/apps.md
- docs/ibc/apps/apps.md
- docs/ibc/integration.md
- docs/ibc/overview.md
- docs/ibc/relayer.md
- docs/middleware/ics29-fee/fee-distribution.md
> docs: fix broken sdk links

- modules/core/02-client/types/codec.go
- modules/core/02-client/types/codec_test.go
Register the legacy gov proposal content types against the interface
---
> fix: register impls against govtypes.Content interface

- modules/core/03-connection/types/codec_test.go
- modules/core/04-channel/types/codec_test.go
- modules/core/23-commitment/types/codec_test.go
- modules/light-clients/06-solomachine/codec_test.go
- modules/light-clients/07-tendermint/codec_test.go
- modules/light-clients/09-localhost/codec_test.go
> test: implement codec registration tests for ibc core and lightclients

- e2e/tests/core/02-client/client_test.go
- e2e/testsuite/testconfig.go
closes: #XXXX
```text
chore: fix linting issues in e2e module
```
---
> Fix e2e linting issues.

- modules/light-clients/08-wasm/types/client_state.go
- modules/light-clients/08-wasm/types/contract_api.go
- modules/light-clients/08-wasm/types/proposal_handle.go
- modules/light-clients/08-wasm/types/update.go
- modules/light-clients/08-wasm/types/upgrade.go
Point raised in walkthrough of 08-wasm. Uses a type constraint for the generic argument to wasmCall/wasmQuery.
closes: #XXXX
```text
```
---
> Use a type constraint instead of any for wasmCall/wasmQuery.

- docs/docs/01-ibc/02-integration.md
- docs/docs/01-ibc/03-apps/01-apps.md
- docs/docs/01-ibc/03-apps/02-ibcmodule.md
- docs/docs/01-ibc/09-roadmap.md
- docs/docs/02-apps/01-transfer/07-params.md
- docs/docs/03-light-clients/02-localhost/03-client-state.md
> fix: typos

- .github/workflows/e2e-fork.yml
Recently we added support for specifying relayer configuration, but omitted the setting when running forks. This should correct the error.
---
> Fix E2Es running on forks.

- modules/light-clients/08-wasm/types/types_test.go
mistakenly commented out this init() function to set up the correct simapp testing the 08-wasm client. for some reason our ci tests didn't catch this, although a local test run of ie: `TestInitializeGrandpa` will fail with ```panic: chain is not a simapp.SimApp [recovered]
panic: chain is not a simapp.SimApp```
---
> fix: init function

- modules/light-clients/08-wasm/go.mod
- modules/light-clients/08-wasm/go.sum
Closes #4841, thanks so much pointing this out @webmaster128
```text
chore: bump wasmvm to 1.4.1
```
---
> Bump wasmvm to 1.4.1

- modules/light-clients/08-wasm/testing/wasm_endpoint.go
- modules/light-clients/08-wasm/types/client_state_test.go
- modules/light-clients/08-wasm/types/export_test.go
- modules/light-clients/08-wasm/types/mock_engine_test.go
- modules/light-clients/08-wasm/types/types_test.go
closes: #4873
The implementation wasn't as straightforward as I was expecting.
It seems it is not possible to use type constraints as keys to a map, because of this I opted to use the type name and pre-populate the map with all allowed types so it is only possible to register types for the expected values.
I needed to move the mock vm to the same package as the types to be able to actually do this.
I'm not too happy about that, and I think we can actually revert that if we just opt to use a set of string constants instead of types. Open to suggestions!
I also looked into the possibility of using an `internal` directory, but types aren't importable from types_test from a separate package.
---
checked off. …
> Improve mock wasmvm query implementation

- modules/apps/27-interchain-accounts/controller/types/msgs.go
- modules/apps/27-interchain-accounts/controller/types/msgs_test.go
> fix(statemachine)!: add check for length of owner in `MsgRegisterInterchainAccount`

- modules/light-clients/08-wasm/types/client_state.go
- modules/light-clients/08-wasm/types/contract_api.go
- modules/light-clients/08-wasm/types/upgrade.go
Removes usage of `exported` interface types in the contract api types to allow clean codec usage with native Go implementations. 
We should run an e2e regression with this but encoding should be fine. 
closes: #4908 
---
> fix(08-wasm)!: use concrete types for json serialization

- modules/light-clients/08-wasm/types/client_state_test.go
- modules/light-clients/08-wasm/types/types_test.go
[this pr](https://github.com/cosmos/ibc-go/pull/4909) removed usage of exported types in contract api types, which broke these tests.
---
> fix: handle export type values correctly

- e2e/tests/wasm/grandpa_test.go
Fixes an issue when running `make test` would attempt to run the grandpa e2e test spinning up docker containers.
---
> fix: add build flag directives to ignore e2e test

- e2e/README.md
closes: #XXXX
```text
chore: document the build constraint for new e2e test files.
```
---
> Add note for adding a build tag in new e2e files.

- .github/workflows/wasm-client.yml
Bumping this to 10m (as for ibc-go linting) since linter appears to experience more timeouts than a misbehaving toddler. 
```text
chore: bump linter timeout to 10m
```
---
> Bump linter timeout to 10m

- modules/light-clients/08-wasm/types/export_test.go
- modules/light-clients/08-wasm/types/update_test.go
closes: #4831 
```text
test(08-wasm): added 'TestUpdateState' using mockVM
```
---
> test(08-wasm): added 'TestUpdateState' using mockVM

- testing/endpoint.go
- testing/events.go
closes: #4809 
```text
imp: add ParseProposalIDFromEvents helper function
```
---
> Add ParseProposalIDFromEvents helper function

- modules/light-clients/08-wasm/types/client_state_test.go
some unchecked cases for this test
closes: #XXXX
```text
chore: increase cov for TestInitialize
```
---
> Add additional coverage for test initialize.

- modules/apps/27-interchain-accounts/controller/types/codec.go
Register the ICA msgs to the interface registry allowing any BaseAccount (externally owned account) to interact with the ICA module from offchain without the necessity to be through the CLI. 
Not registering module Msgs can be an issue when using the LCD to submit signed messages due the following error:
```
data: {
code: 2,
message: 'unable to resolve type URL /ibc.applications.interchain_accounts.controller.v1.MsgRegisterInterchainAccountResponse',
details: []
}
```
> reproduced here https://github.com/terra-money/core/pull/196
```text
fix(msg): register proto interface
```
Credits to @javiersuweijie !
> fix(msg): register proto interface

- modules/light-clients/08-wasm/types/client_state.go
- modules/light-clients/08-wasm/types/client_state_test.go
- testing/mock/mock.go
closes: #XXXX
```text
chore: add tests for mismatched height types.
```
---
> Add mock height and check for it in membership tests

- modules/light-clients/08-wasm/types/client_state_test.go
- modules/light-clients/08-wasm/types/misbehaviour_handle_test.go
see small discussion we had here https://github.com/cosmos/ibc-go/pull/4894/files#r1365157212
closes: #XXXX
```text
chore: remove panic checks for non-panicking methods
```
---
> Remove panic handling testing code for non-panicking methods.

- e2e/README.md
- e2e/sample.config.yaml
- e2e/testsuite/testconfig.go
> deps: update hermes tag to v1.7.0

- docs/tutorials/01-fee/01-intro.md
- docs/tutorials/01-fee/02-setup-env.md
- docs/tutorials/01-fee/04-wire-feeibc-mod.md
- docs/tutorials/01-fee/07-test-app.md
closes: #4854
```text
docs: fee middleware tutorial improvements
```
---
> docs: fee middleware tutorial improvements

- modules/apps/transfer/types/errors.go
- modules/apps/transfer/types/msgs.go
- modules/apps/transfer/types/msgs_test.go
> fix(statemachine)!: add check for length of memo field in `MsgTransfer`

- modules/light-clients/08-wasm/types/export_test.go
- modules/light-clients/08-wasm/types/proposal_handle.go
- modules/light-clients/08-wasm/types/proposal_handle_test.go
- modules/light-clients/08-wasm/types/store.go
- modules/light-clients/08-wasm/types/store_test.go
ref for changes here https://github.com/cosmos/ibc-go/issues/4547#issuecomment-1785701346
closes: #4547
```text
```
---
> Modify wrappedStore to allow reads from both substitute and subject, writes only to subject

- docs/docs/00-intro.md
- docs/docs/01-ibc/01-overview.md
- docs/sidebars.js
- docs/versioned_sidebars/version-v4.4.x-sidebars.json
- docs/versioned_sidebars/version-v5.3.x-sidebars.json
- docs/versioned_sidebars/version-v6.2.x-sidebars.json
- docs/versioned_sidebars/version-v7.3.x-sidebars.json
Fixed typos related to the name of the protocol and clarified introductory language on the opening pages of the documentation.
closes: #XXXX
```text
```
---
> fix: docs typos

- testing/events.go
- testing/events_test.go
Returns all the packets found in the events. Comes in addition with ParsePacketFromEvents (singular version), which only returns the first packet found in the events.
closes: #4287
```text
```
---
> test: add ParsePacketsFromEvents

- modules/core/02-client/keeper/client.go
- modules/core/02-client/keeper/client_test.go
- modules/light-clients/07-tendermint/upgrade.go
- modules/light-clients/08-wasm/types/upgrade.go
closes: #4212, ~~removing this check in the 08-wasm module is additionally required.~~ (Removed check in 08-wasm module)
```bash
chore: move check for upgraded client state height in 02-client layer.
```
---
> Move check for upgraded client state height to 02-client layer.

- docs/docs/01-ibc/01-overview.md
- docs/docs/01-ibc/03-apps/02-ibcmodule.md
- docs/docs/02-apps/01-transfer/01-overview.md
- docs/docs/02-apps/02-interchain-accounts/01-overview.md
closes: #5164 
```text
docs: improved channel closure docs
```
---
> docs: improved channel closure docs

- modules/core/04-channel/keeper/upgrade_test.go
- modules/core/keeper/msg_server_test.go
- testing/endpoint.go
Updates testing `Endpoint` to query `chainA` when using: `path.EndpointA.QueryChannelUpgradeProof()`.
Previously, this would query the counterparty endpoint.
closes: #5147 
---
> refactor: adapt testing endpoint query for channel upgrade proofs

- docs/client/swagger-ui/swagger.yaml
> chore: update swagger

- modules/capability/module.go
- modules/core/04-channel/keeper/upgrade_test.go
I didn't opt for table tests for this PR as this is more of a one off situation.
closes: #4267
---
> Verify channel upgrade can be completed after cancellation is successful

- modules/core/04-channel/keeper/upgrade.go
- modules/core/04-channel/keeper/upgrade_test.go
- modules/core/04-channel/types/msgs.go
- modules/core/04-channel/types/msgs_test.go
> Allow empty error receipt proof if sender is authorized

- modules/core/04-channel/keeper/upgrade.go
- modules/core/keeper/msg_server.go
Panic in WriteErrorReceipt [instead of returning an error](https://github.com/cosmos/ibc-go/blob/39df8d2b579fc623a1e748b4330738ff40adb682/modules/core/04-channel/keeper/upgrade.go#L932), which is ignored.
closes: #5207
```text
```
---
> Use panic in WriteErrorReceipt

- modules/core/04-channel/keeper/upgrade.go
> Add  to docstring with explanation about channel state

- .github/workflows/release-wasm.yml
Workflow can be run from main to build the wasm simapp from the specified branch with the specified docker tag.
In the future we can make this automatically build for wasm tags.
> Add workflow to build wasm simapp

- .github/workflows/e2e-manual-wasm-simd.yaml
- .github/workflows/release-wasm.yml
> Workflow to trigger wasm E2Es with a specific tag

- modules/core/04-channel/keeper/packet.go
- modules/core/04-channel/keeper/packet_test.go
- modules/core/04-channel/keeper/timeout.go
- modules/core/04-channel/keeper/timeout_test.go
- modules/core/04-channel/keeper/upgrade.go
- modules/core/04-channel/keeper/upgrade_test.go
- modules/core/keeper/msg_server.go
closes: #5227
closes: #5223
If we don't set the counterparty upgrade in TRY, it means we can still be in a situation in which the counterparty upgrade is not set. We can wrap the existing logic in an `if found {}` block to handle for this situation.
The new code assumes a valid upgrade timeout is stored in state if one is present.
---
> Remove setting counterparty upgrade info in upgrade try

- modules/core/04-channel/keeper/upgrade.go
- modules/core/04-channel/keeper/upgrade_test.go
- modules/core/04-channel/types/msgs.go
- modules/core/04-channel/types/msgs_test.go
closes: #5260 
```text
```
---
> fix: allow error receipt to be nil in case of the msg sender is the authority

- docs/docs/01-ibc/04-middleware/02-develop.md
Remove redundant code from code examples.
closes: #XXXX
```text
```
---
> docs: remove redundant code from code examples

- e2e/tests/wasm/grandpa_test.go
- modules/core/02-client/types/params.go
- modules/core/exported/client.go
- modules/light-clients/08-wasm/keeper/keeper_test.go
- modules/light-clients/08-wasm/testing/wasm_endpoint.go
- modules/light-clients/08-wasm/types/client_message.go
- modules/light-clients/08-wasm/types/client_message_test.go
- modules/light-clients/08-wasm/types/client_state.go
- modules/light-clients/08-wasm/types/consensus_state.go
- modules/light-clients/08-wasm/types/consensus_state_test.go
- modules/light-clients/08-wasm/types/keys.go
- modules/light-clients/08-wasm/types/types_test.go
- modules/light-clients/08-wasm/types/validation.go
- modules/light-clients/08-wasm/types/validation_test.go
> fix: remove 08-wasm from 02-client exported

- modules/core/04-channel/keeper/upgrade.go
- modules/core/04-channel/keeper/upgrade_test.go
closes: #5319 
```text
```
---
> fix: require authority to pass proof if channel state is in FLUSHCOMPLETE for upgrade cancellation

- .github/workflows/e2e-fork.yml
- .github/workflows/e2e-upgrade.yaml
- .github/workflows/e2e.yaml
- e2e/tests/wasm/upgrade_test.go
- e2e/testsuite/grpc_query.go
> e2e: adding ibcwasm e2e upgrade test

- modules/apps/27-interchain-accounts/controller/ibc_middleware.go
- modules/apps/27-interchain-accounts/host/ibc_module.go
- modules/apps/29-fee/ibc_middleware.go
- modules/apps/transfer/ibc_module.go
- testing/mock/ibc_module.go
> chore: adding interface assertions for app upgrade interface

- .github/workflows/build-callbacks-simd-image-from-tag.yml
- .github/workflows/build-simd-image-from-tag.yml
- .github/workflows/build-wasm-simd-image-from-tag.yml
- .github/workflows/e2e-compatibility-unreleased.yaml
- .github/workflows/e2e-compatibility.yaml
This PR filters out all non alphanumeric and replaces them with `-`. 
---
> Ensure docker tags are valid

- e2e/testsuite/diagnostics/diagnostics.go
- e2e/testsuite/testsuite.go
This PR adds some additional debugging information by collecting the hermes config.toml file.
I removed some of the more verbose logging which I don't think added much value. (if anything it made things worse 😅 )
note: you must specify 
```yaml
debug:
dumpLogs: true
```
In the e2e config for the logs to be collected if the test passes.
---
> Collect hermes config.toml file in e2e diagnostics

- docs/docs/03-light-clients/04-wasm/03-integration.md
Fixes some differences from documentation & v7.3 chain integration (ref: https://github.com/CosmosContracts/juno/pull/921). It looks like documentation is only in main & not the v7.3 08-wasm branch? lmk if there is a better place to target this PR. 
- If using x/wasm, do we register both x/wasm NewWasmSnapshotter and the ibc WasmSnapshoter?
- Same question for [`InitializePinnedCodes`](https://github.com/CosmosContracts/juno/pull/921/commits/33e68444b0a2c5705b51c71e55ea65212a91a2a5) ^^
- Using `wasmtypes` import namespace is kind of a pain for x/wasm users, can `wasmlctypes` or `ibcwasmtypes` be used instead?
```text
```
see the [guidelines](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) for commit messages. (view raw markdown …
> chore: fix 08-wasm light client documentation

- modules/core/04-channel/types/codec.go
- modules/core/04-channel/types/codec_test.go
- Added missing codec registration.
- Added tests
---
> fix: add MsgPruneAcknowledgements to codec registration

- modules/core/04-channel/keeper/export_test.go
- modules/core/04-channel/keeper/upgrade.go
- modules/core/04-channel/keeper/upgrade_test.go
See https://github.com/cosmos/ibc-go/pull/1613#discussion_r1434159549
closes: #XXXX
```text
```
---
> chore: remove `syncUpgradeSequence`

- modules/apps/transfer/keeper/migrations.go
> fix migration log

- docs/architecture/README.md
- docs/architecture/adr-001-coin-source-tracing.md
- docs/architecture/adr-002-go-module-versioning.md
- docs/architecture/adr-025-ibc-passive-channels.md
- docs/architecture/adr-026-ibc-client-recovery-mechanisms.md
- docs/architecture/adr-027-ibc-wasm.md
- docs/dev/project-structure.md
- docs/dev/release-management.md
- docs/requirements/channel-upgradability-requirements.md
- e2e/README.md
This PR addresses minor typos and grammatical errors in various documentation files. These changes aim to enhance readability and ensure accuracy in the documentation.
- ADR 026: Fixed typo ('identitical' to 'identical').
- Channel Upgradability Requirements: Corrected grammatical errors ('has been flushed' to 'have been flushed', 'permissionlesly' to 'permissionlessly').
- ADR 025: Fixed typo ('chanenlID' to 'channelID').
- ADR 002: Grammatical corrections ('released during with the' to 'released during the', 'lets' to 'let's').
- ADR 001: Typo fix ('addressed' to 'addresses').
- Release Management: Corrected label name ('backport-to-v1.0x' to 'backport-to-v1.0.x').
- Project Structure: Verb agreement fix ('implement' to 'implements').
- ADR 027 (Cosmos SDK section): Typo correction …
> Documentation Corrections

- modules/core/keeper/msg_server_test.go
Added tests for `UpdateChannelParams` in [msg_server_test.go](https://github.com/cosmos/ibc-go/blob/28f757a52c1075e78aa16322f1adab35a6e94e7d/modules/core/keeper/msg_server_test.go).
closes: #5479
```text
test: added tests for `UpdateChannelParams`
```
---
> test: added tests for `UpdateChannelParams`

- docs/docs/01-ibc/06-channel-upgrades.md
> Document ibc app expectations and recommendations

- modules/core/04-channel/client/cli/tx.go
> chore: fix cmd example for PruneAcknowledgements

- modules/apps/27-interchain-accounts/host/ibc_module.go
- modules/apps/transfer/ibc_module.go
this bug was introduced in https://github.com/cosmos/ibc-go/commit/e93a467086d4b25f38632483ed6b2760867c0d2a
closes: #XXXX
```text
```
---
> fix: add packet seq in success log

- modules/apps/27-interchain-accounts/controller/keeper/handshake.go
- modules/apps/27-interchain-accounts/controller/keeper/handshake_test.go
- modules/apps/27-interchain-accounts/host/keeper/handshake.go
- modules/apps/27-interchain-accounts/host/keeper/handshake_test.go
> Remove order check for ICA host and controller upgrade callbacks

- modules/core/keeper/msg_server.go
> nit: remove stale comment

- modules/apps/27-interchain-accounts/controller/ibc_middleware_test.go
- modules/apps/27-interchain-accounts/controller/keeper/handshake.go
- modules/apps/27-interchain-accounts/controller/keeper/handshake_test.go
- modules/apps/27-interchain-accounts/host/ibc_module_test.go
- modules/apps/27-interchain-accounts/host/keeper/handshake.go
- modules/apps/27-interchain-accounts/host/keeper/handshake_test.go
closes: #5522 
```text
```
---
> imp: remove the channel type = ordered checks from both host and controller

- docs/docs/01-ibc/10-roadmap.md
- modules/light-clients/07-tendermint/tendermint.pb.go
- proto/ibc/lightclients/tendermint/v1/tendermint.proto
- testing/endpoint.go
Fixed one recurring typo "lastest". It also appears in the versioned_docs but I believe I shouldn't edit them.
Doesn't require testing or changelog entry.
Have a nice evening.
> chore: recurring typo

- modules/apps/27-interchain-accounts/controller/keeper/handshake.go
- modules/apps/27-interchain-accounts/controller/keeper/handshake_test.go
closes: #5580 
```text
chore: require active channel be CLOSED before re-opening.
```
---
> Require active channel be CLOSED before re-opening.

- docs/docs/02-apps/02-interchain-accounts/05-messages.md
- docs/docs/02-apps/02-interchain-accounts/09-active-channels.md
> Update ICA documentation with support for unordered channels

- modules/core/04-channel/keeper/events.go
- modules/core/04-channel/types/events.go
- modules/core/keeper/msg_server_test.go
After merged I will probably rename the attributes in #5603.
closes: #XXXX
```text
```
---
> imp: separate height and timestamp attribute in upgrade timeout event

- modules/apps/27-interchain-accounts/host/keeper/handshake.go
- modules/apps/27-interchain-accounts/host/keeper/handshake_test.go
> chore(ica/host): require active channel be CLOSED before re-opening

- testing/simapp/upgrades.go
- testing/simapp/upgrades/upgrades.go
Adds the default upgrade handler for v8.1.
ref: #5635
---
> chore: add default upgrade handler for v8.1

- modules/core/02-client/types/codec_test.go
- modules/core/03-connection/keeper/keeper_test.go
- modules/core/ante/ante_test.go
- modules/light-clients/07-tendermint/client_state_test.go
- modules/light-clients/07-tendermint/header_test.go
- testing/chain.go
- testing/endpoint.go
- testing/solomachine.go
> rename lastheader to latestcommittedheader

- modules/apps/27-interchain-accounts/controller/keeper/keeper.go
- modules/apps/27-interchain-accounts/host/keeper/keeper.go
- modules/core/04-channel/keeper/handshake.go
- modules/core/04-channel/keeper/upgrade.go
- modules/core/04-channel/types/channel.go
Removes `IsClosed` and `IsOpen` channel methods.
---
> chore: remove IsOpen and IsClosed channel methods

- modules/core/04-channel/types/channel.go
> revert: api breakage on release/v8.1.x

- modules/core/04-channel/keeper/packet.go
> imp: remove unexpected behaviour error string

- modules/core/04-channel/types/upgrade.go
- modules/core/04-channel/types/upgrade_test.go
This PR does a refactor to utilize the `errors.Is` and `errors.Unwrap`  functions.
@DimitrisJim pointed out we were using the `Unrwap` and `Cause` incorrectly. The implementations have been updated to reflect their intended use case.
---
> Refactor UpgradeError to use bullt in errors functions

- e2e/tests/core/02-client/client_test.go
Another fix for compatibility tests. Tests are passing [here](https://github.com/cosmos/ibc-go/actions/runs/7701273803) for `release/v7.2.x`.
closes: #XXXX
```text
```
---
> fix: set explicit allowed clients for versions < v8.1

- e2e/tests/interchain_accounts/upgrades_test.go
- e2e/tests/upgrades/upgrade_test.go
- e2e/testsuite/sanitize/messages.go
- modules/core/03-connection/types/connection.go
- modules/core/04-channel/keeper/handshake.go
- modules/core/04-channel/keeper/packet.go
- modules/core/04-channel/keeper/upgrade.go
- modules/core/exported/connection.go
A step towards removing the connection interface. As a nice side affect it removes a lot of unnecessary casting
closes: #XXXX
```text
```
---
> refactor!: remove GetState() on connection interface

- docs/docs/05-migrations/13-v8-to-v9.md
- modules/apps/27-interchain-accounts/controller/keeper/handshake.go
- modules/apps/27-interchain-accounts/types/metadata.go
- modules/core/03-connection/keeper/keeper.go
- modules/core/03-connection/keeper/verify.go
- modules/core/03-connection/types/connection.go
- modules/core/04-channel/keeper/handshake.go
- modules/core/04-channel/keeper/packet.go
- modules/core/04-channel/keeper/timeout.go
- modules/core/04-channel/keeper/upgrade.go
> refactor!: remove unnecessary getters on connection end

- modules/apps/transfer/keeper/relay.go
The only item of #65 that still applies for ibc-go:
> In [OnAcknowledgementPacket](https://github.com/cosmos/cosmos-sdk/blob/82f15f306e8a6a2e9ae3e122c348b579c43a3d92/x/ibc/applications/transfer/keeper/relay.go#L314), the default branch of a switch statement is used for success logic. This is bit risky to maintain if additional error codes get added in the future (in the ICS it simply says if (!ack.success)). Rather, all error and success cases for the ack.Response should be handled explicitly and the default should be an error.
closes: #65 
```text
```
---
Before we can merge this PR, please make sure that all …
> imp: return error on default branch of ack type switch statement

- e2e/testsuite/testsuite.go
- modules/core/02-client/keeper/keeper.go
- modules/core/02-client/types/store.go
- modules/core/exported/client.go
- modules/light-clients/06-solomachine/light_client_module.go
- modules/light-clients/08-wasm/light_client_module.go
- modules/light-clients/09-localhost/light_client_module.go
- modules/light-clients/09-localhost/light_client_module_test.go
- modules/light-clients/09-localhost/store.go
> 02-client routing: fix linter warnings

- e2e/testsuite/grpc_query.go
- modules/apps/27-interchain-accounts/host/ibc_module.go
- modules/apps/29-fee/keeper/escrow.go
- modules/apps/29-fee/types/keys.go
- modules/apps/29-fee/types/msgs.go
- modules/light-clients/08-wasm/testing/mock_engine.go
- modules/light-clients/08-wasm/types/contract_api.go
- modules/light-clients/08-wasm/types/msgs.go
- testing/solomachine.go
froce comments to start with exported element  (https://tip.golang.org/doc/comment)
```text
chore: fix comments so they start with exported element
```
---
> chore: fix wrong comment

- docs/docs/03-light-clients/01-developer-guide/02-client-state.md
- docs/docs/03-light-clients/01-developer-guide/05-upgrades.md
- docs/docs/05-migrations/13-v8-to-v9.md
- e2e/tests/core/02-client/client_test.go
- modules/core/02-client/keeper/client_test.go
- modules/core/02-client/keeper/keeper.go
- modules/core/02-client/keeper/keeper_test.go
- modules/core/02-client/migrations/v7/solomachine.go
- modules/core/02-client/types/legacy_proposal.go
- modules/core/exported/client.go
- modules/core/keeper/msg_server_test.go
- modules/light-clients/06-solomachine/client_state.go
- modules/light-clients/07-tendermint/client_state.go
- modules/light-clients/07-tendermint/upgrade.go
- modules/light-clients/07-tendermint/upgrade_test.go
- modules/light-clients/08-wasm/types/client_state.go
- modules/light-clients/09-localhost/client_state.go
- modules/light-clients/09-localhost/client_state_test.go
> refactor!: remove ZeroCustomFields from ClientState interface

- modules/core/02-client/types/legacy_proposal.go
> fix: move 02-client legacy v1beta gov types deprecation message to constructor functions

- docs/docs/05-migrations/13-v8-to-v9.md
- modules/light-clients/07-tendermint/misbehaviour_handle_test.go
- modules/light-clients/07-tendermint/update_test.go
- testing/chain.go
closes: #4484 
```text
```
---
> refactor: rename GetValsAtHeight to GetTrustedValidators

- modules/core/02-client/keeper/client.go
- modules/core/02-client/keeper/client_test.go
- modules/core/exported/client.go
- modules/light-clients/06-solomachine/light_client_module.go
- modules/light-clients/06-solomachine/light_client_module_test.go
- modules/light-clients/07-tendermint/light_client_module.go
- modules/light-clients/07-tendermint/light_client_module_test.go
- modules/light-clients/08-wasm/light_client_module.go
- modules/light-clients/08-wasm/light_client_module_test.go
- modules/light-clients/08-wasm/types/proposal_handle_test.go
- modules/light-clients/08-wasm/wasm_test.go
> 02-client routing: implement `RecoverClient` in light client modules

- modules/light-clients/08-wasm/types/querier_test.go
Register querier callbacks in mockVM against `TimestampAtHeightMsg` instead of `StatusMsg`.
This avoids recursive loops introduced by yours truly in https://github.com/cosmos/ibc-go/pull/5870, adding the client status check to the rpc handler of `VerifyMembership`.
If anyone would rather a different approach to fixing this issue, we could additional create an entirely separate test func for `success: verify membership query` and only use `TimestampAtHeightMsg` for that one, but it makes no difference to me.
---
> fix(08-wasm/test): register mockVm querier callbacks against TimestampAtHeightMsg to avoid recursive loops

- modules/light-clients/08-wasm/types/querier_test.go
Follow up from wasm testing fix for more fixes.
Co-authored-by: Cian Hatton <cian@interchain.io>
---
> fix: return correct types in wasm tests and add expected err

- modules/apps/27-interchain-accounts/controller/client/cli/tx.go
- modules/apps/27-interchain-accounts/types/packet.go
- modules/apps/transfer/client/cli/tx.go
- modules/apps/transfer/types/packet.go
- Refactors transfer CLI to use local clock time only for relative timeouts.
- Removes the stateful query on the node to client and consensus states.
- Disables relative timeout by block height.
closes: #3594 
---
> refactor: use local clock time only for transfer CLI relative timeouts

- docs/docs/03-light-clients/04-wasm/03-integration.md
- docs/versioned_docs/version-v7.3.x/03-light-clients/04-wasm/03-integration.md
- docs/versioned_docs/version-v8.0.x/03-light-clients/04-wasm/03-integration.md
- docs/versioned_docs/version-v8.1.x/03-light-clients/04-wasm/03-integration.md
Some docs fixes/improvements. 
---
> docs: fix imports and code snippets for x/wasm and ibcwasm app wiring

- modules/core/02-client/keeper/client_test.go
- modules/core/keeper/msg_server.go
- modules/light-clients/07-tendermint/light_client_module.go
- modules/light-clients/07-tendermint/light_client_module_test.go
- modules/light-clients/07-tendermint/upgrade.go
This PR removes the extra marshalling step encoding the `pb.Any` of client/consensus state to bytes in core IBC.
It's possible to simply pass along the bytes of the underlying concrete type to the light client module, and it can take responsibility to remarshal the `pb.Any` for proving counterparty state. 
This PR adjusts the tests to account for this change.
---
> fix: remove marshalling of anys to bytes for verify upgrade

- modules/apps/transfer/types/trace.go
- modules/apps/transfer/types/trace_test.go
> fix: allow base denom with trailing slash

- modules/apps/transfer/ibc_module.go
- modules/apps/transfer/ibc_module_test.go
- modules/apps/transfer/types/keys.go
> chore: implement version checking for channel handshake application callbacks

- CHANGELOG.md
- testing/app.go
- testing/chain.go
- testing/simapp/test_helpers.go
context: https://github.com/celestiaorg/celestia-app/issues/3137
---
> feat: add version to the header

- CHANGELOG.md
- modules/core/ante/ante.go
- modules/core/ante/ante_test.go
Ignore `Misbehaviour` types for solomachine and tendermint clients when calling `UpdateState`.
ref: #6232 
---
> refactor(v7.4.x): performance improvements for update client in ante

- CHANGELOG.md
- docs/docs/05-migrations/13-v8-to-v9.md
- e2e/tests/wasm/grandpa_test.go
- e2e/testsuite/testsuite.go
- modules/apps/transfer/types/keys.go
- modules/apps/transfer/types/token_test.go
> imp: self review comments for ics20-v2

- modules/apps/transfer/ibc_module_test.go
- testing/chain.go
- testing/values.go
Related to #6402
This adds a secondary denom to the test chains genesis generation in the ibc-testing package.
---
> test: add secondary test coin to test chains

- modules/apps/29-fee/transfer_test.go
- modules/apps/callbacks/ibc_middleware_test.go
- modules/apps/transfer/keeper/invariants_test.go
- modules/apps/transfer/transfer_test.go
Related to: #6402
Adds more test cases in multiple places where we currently only do a single-denom transfers.
Because I added test tables to some tests, the diff is unfortunately very ugly :/ 
---
> test: add more multi-denom test cases

- modules/apps/transfer/types/msgs.go
- modules/apps/transfer/types/msgs_test.go
closes: #6551 
Add the same checking logic that was already implemented for FungibleTokenPacketDataV2. The bulk of the test cases are covered by forwarding path `Validate`, but this also adds a couple of tests that hits the forwarding path's validate logic.
---
> feat(transfer): add validation for forwarding info in msg transfer validate basic

- modules/apps/transfer/types/transfer_authorization.go
- modules/apps/transfer/types/transfer_authorization_test.go
closes: #6588
Basically checks if the msg has pending hops and if so uses the memo in forwarding field to verify the memo rather than the root level memo (which should be empty in that case (validated in `ValidateBasic`).
---
> feat(transfer): validate forwarding memo in transfer authorization

- modules/apps/transfer/keeper/forwarding.go
- modules/apps/transfer/keeper/relay_forwarding_test.go
Replace the last uses of direct struct inits of `Forwarding`
---
> chore: use new forwarding instead of struct init

- modules/apps/transfer/keeper/forwarding.go
- modules/apps/transfer/keeper/relay_forwarding_test.go
closes: #6587
Changes forward ack to `channeltypes.NewResultAcknowledgement([]byte{byte(1)})` (same as the synchronous transfer ack).
I also changed the existing `TestSimplifiedHappyPathForwarding()` test to use three chains (`A -> B -> C`) instead of two. If we want to have an `A -> B -> A` test I can put up that as well. And confirm the acks in the test, of course.
---
> feat(transfer): use single byte ack for successful forward

- e2e/tests/core/03-connection/connection_test.go
- e2e/tests/transfer/authz_test.go
- e2e/tests/transfer/base_test.go
- e2e/tests/transfer/forwarding_test.go
- e2e/tests/transfer/incentivized_test.go
- e2e/tests/transfer/upgradesv1_test.go
- e2e/tests/transfer/upgradesv2_test.go
- e2e/tests/upgrades/upgrade_test.go
- e2e/testsuite/testsuite.go
Renames `SetupPath` in the e2e test suite to be more precise. Also renames `CreateNewPath` to `CreatePath` (because it was named `CreateNewPath` to not be too similar to the old `SetupPath`).
---
> refactor: rename SetupPath to SetupPaths in e2e testsuite

- modules/apps/transfer/client/cli/tx.go
- Add flag `unwind` in transfer cli.
closes: #6657 
---
> chore: add flag for unwind in transfer cli

- modules/core/02-client/keeper/client.go
- modules/core/02-client/keeper/keeper.go
- modules/light-clients/09-localhost/client_state.go
Start of #6019 
In order to keep the PRs for this task a little more digestible, I wanted to do this small refactor first. 
And I wanted to ask if I should also use the helper method in other places where we currently do not do any `if !k.GetParams(ctx).IsAllowedClient(clientType)` checks. 
The places I have identified that currently gets the route, but does not run `IsAllowedClient`:
- https://github.com/cosmos/ibc-go/blob/dd23cf9da535d121ef51f4b79f569c025ea22c7a/modules/core/02-client/keeper/keeper.go#L307-L314
- https://github.com/cosmos/ibc-go/blob/dd23cf9da535d121ef51f4b79f569c025ea22c7a/modules/core/02-client/keeper/keeper.go#L395-L411
- https://github.com/cosmos/ibc-go/blob/dd23cf9da535d121ef51f4b79f569c025ea22c7a/modules/core/02-client/keeper/keeper.go#L415-L436
- …
> chore: pull out get light client module to helper methods

- .github/mergify.yml
> chore: mergify for new 08-wasm branches

- .github/workflows/e2e-fork.yml
We are temporarily disabling the wasm workflows. This one cannot be disabled via the UI as it is the same workflow that runs regular e2es.
closes: #XXXX
---
> Disable wasm fork workflows

- modules/light-clients/08-wasm/CHANGELOG.md
- modules/light-clients/08-wasm/internal/types/merkle_path.go
- modules/light-clients/08-wasm/types/client_state.go
- modules/light-clients/08-wasm/types/client_state_test.go
- modules/light-clients/08-wasm/types/contract_api.go
Adds forwards compatibility for ibc-go/v9 `commitment.v2.MerklePath`.
NOTE: This PR includes a breaking change for 08-wasm client contracts. For deployed contracts this requires a migration to correctly handle deserialisation of `VerifyMembershipMsg.Path.KeyPath` and `VerifyNonMembershipMsg.Path.KeyPath` as `[][]byte` rather than `[]string`.
See migration docs for more details.
ref: #6496 
---
> api!(08-wasm/v0.2.0-ibc-go-v7): update `VerifyMembershipMsg` and `VerifyNonMembershipMsg` contract api structs to support non-utf8 keys

- e2e/tests/transfer/forwarding_test.go
> (test) Add test for path forwarding with channel upgrade 

- e2e/sample.config.yaml
- e2e/testsuite/testconfig.go
- e2e/testsuite/testsuite.go
When running a full test suite, we need to keep the containers around after a test finishes so as to not interfere with other tests. For local development it can be handy to still clean up containers after a single test.
This PR adds a config value to enable this.
closes: #XXXX
---
> Make keep containers configurable

- modules/core/02-client/keeper/keeper.go
- modules/core/02-client/types/store.go
- modules/core/exported/client.go
- modules/light-clients/06-solomachine/light_client_module.go
- modules/light-clients/07-tendermint/light_client_module.go
- modules/light-clients/08-wasm/light_client_module.go
v9 alpha audit
Removes unnecessary interface `ClientStoreProvider` in favour of concrete type in 02-client.
---
> imp: remove ClientStoreProvider interface in favour of concrete type

- modules/apps/callbacks/forwarding_test.go
> (test) Add tests for callback execution when forwarding a packet

- e2e/tests/transfer/forwarding_test.go
- e2e/testsuite/testsuite.go
> (tests): e2e test for failed forwarding

- CHANGELOG.md
- docs/docs/05-migrations/13-v8-to-v9.md
> docs: polishing and adding more API breaking changes to changelog and v9 migration

- e2e/tests/transfer/base_test.go
Some conditionals to send the entire balance of just a single denom in v1 channels, so that we can test this functionality as well with `ics20-1` channels.
closes: #XXXX
---
> e2e: send entire balance of single denom in v1 channels

- modules/light-clients/08-wasm/CHANGELOG.md
- modules/light-clients/08-wasm/go.mod
- modules/light-clients/08-wasm/types/contract_api.go
Explicitly break the api of json encoded contract msgs
---
> api!: rename path to merkle path for contract api json msgs

- CHANGELOG.md
- docs/docs/05-migrations/13-v8-to-v9.md
Migration docs for #6960
closes: #XXXX
---
> docs: changelog and migration docs for #6960

- modules/core/02-client/keeper/keeper.go
- modules/core/02-client/keeper/keeper_test.go
- modules/core/03-connection/keeper/verify.go
Moving status checks one layer down so as to not worry about them when directly calling `Verify(Non)Membership` in impl of eureka logic for packet handling.
Can also target main if needed.
closes: #6980 
---
> chore: move status checks from connection verify_* functions to 02-client verify_* functions.

- modules/core/04-channel/keeper/events.go
- modules/core/04-channel/keeper/keeper.go
- modules/core/04-channel/keeper/packet.go
- modules/core/04-channel/keeper/timeout.go
- modules/core/packet-server/keeper/keeper.go
- modules/core/packet-server/keeper/keeper_test.go
- modules/core/packet-server/types/expected_keepers.go
> feat(core/eureka): add timeout handler

- modules/apps/27-interchain-accounts/controller/ibc_middleware.go
- modules/apps/27-interchain-accounts/controller/ibc_middleware_test.go
- modules/apps/29-fee/ibc_middleware.go
- modules/apps/29-fee/ibc_middleware_test.go
- modules/apps/callbacks/ibc_middleware.go
- modules/apps/callbacks/ibc_middleware_test.go
- modules/apps/callbacks/testing/simapp/app.go
- modules/core/05-port/types/ibc_legacy_module.go
- modules/core/05-port/types/module.go
- modules/core/05-port/types/router_v2.go
- modules/core/keeper/msg_server.go
- simapp/app.go
- testing/simapp/app.go
This PR adds the optional VersionWrapper interface and implementation for ics29.
This PR ended up also implementing OnChanOpenInit in the LegacyIBCModule and updating all implementations to perform the new logic.
closes #7017
closes #6954 
---
> Add Wrap/Unwrap Interfaces and implement OnChanOpenInit

- modules/apps/27-interchain-accounts/host/ibc_module_test.go
- modules/apps/29-fee/fee_test.go
- modules/apps/29-fee/ibc_middleware.go
- modules/apps/29-fee/ibc_middleware_test.go
- modules/apps/callbacks/ibc_middleware.go
- modules/apps/callbacks/ibc_middleware_test.go
- modules/apps/callbacks/testing/simapp/app.go
- modules/apps/transfer/ibc_module_test.go
- modules/core/05-port/types/ibc_legacy_module.go
- modules/core/keeper/msg_server.go
- testing/simapp/app.go
**Marking as R4R for E2Es**
closes: #7027
This PR refactors fee middleware, ICA and callbacks to use the new port router.
Some wiring changes in app.gos needed to be fixed also.
---
> Use new port router for onchanupgradetry

- modules/apps/27-interchain-accounts/controller/ibc_middleware.go
- modules/apps/27-interchain-accounts/controller/ibc_middleware_test.go
- modules/apps/29-fee/ibc_middleware.go
- modules/apps/29-fee/ibc_middleware_test.go
- modules/apps/callbacks/ibc_middleware.go
- modules/apps/transfer/ibc_module_test.go
- modules/core/05-port/types/ibc_legacy_module.go
- modules/core/keeper/msg_server.go
> Use new port router for OnChanOpenAck

- modules/apps/27-interchain-accounts/controller/ibc_middleware_test.go
- modules/apps/27-interchain-accounts/host/ibc_module_test.go
- modules/apps/29-fee/ibc_middleware.go
- modules/apps/callbacks/ibc_middleware.go
- modules/core/05-port/types/ibc_legacy_module.go
- modules/core/keeper/msg_server.go
> use new port router for OnChanOpenConfirm

- modules/apps/27-interchain-accounts/controller/ibc_middleware.go
- modules/apps/27-interchain-accounts/controller/ibc_middleware_test.go
- modules/apps/27-interchain-accounts/controller/keeper/events.go
- modules/apps/27-interchain-accounts/host/ibc_module.go
- modules/apps/27-interchain-accounts/host/ibc_module_test.go
- modules/apps/27-interchain-accounts/host/keeper/events.go
- modules/apps/29-fee/ibc_middleware.go
- modules/apps/29-fee/ibc_middleware_test.go
- modules/apps/29-fee/keeper/relay.go
- modules/apps/29-fee/keeper/relay_test.go
- modules/apps/callbacks/ibc_middleware.go
- modules/apps/callbacks/ibc_middleware_test.go
- modules/apps/callbacks/replay_test.go
- modules/apps/callbacks/testing/simapp/contract_keeper.go
- modules/apps/callbacks/types/expected_keepers.go
- modules/apps/transfer/ibc_module.go
- modules/apps/transfer/ibc_module_test.go
- modules/apps/transfer/keeper/forwarding.go
- modules/core/03-connection/keeper/verify_test.go
- modules/core/04-channel/keeper/packet.go
- modules/core/04-channel/keeper/packet_test.go
- modules/core/05-port/types/ibc_legacy_module.go
- modules/core/05-port/types/module.go
- modules/core/ante/ante_test.go
- modules/core/exported/packet.go
- modules/core/keeper/msg_server.go
- testing/endpoint.go
- testing/mock/ibc_app.go
- testing/mock/ibc_module.go
- testing/mock/middleware.go
Removes the `exported.Acknowledgement` interface and introduces a new concrete `RecvPacketResult` type.
closes: #7042 
---
> refactor: replace ack interface with result type for OnRecvPacket

- modules/apps/transfer/keeper/export_test.go
- modules/apps/transfer/keeper/msg_server.go
- modules/apps/transfer/keeper/msg_server_test.go
> imp (api)!: convert coins to token only once in MsgTransfer 

- modules/apps/27-interchain-accounts/controller/ibc_middleware.go
- modules/apps/27-interchain-accounts/controller/ibc_middleware_test.go
- modules/apps/27-interchain-accounts/host/ibc_module_test.go
- modules/apps/29-fee/ibc_middleware.go
- modules/apps/29-fee/ibc_middleware_test.go
- modules/apps/callbacks/ibc_middleware.go
- modules/apps/callbacks/ibc_middleware_test.go
- modules/core/05-port/types/ibc_legacy_module.go
- modules/core/05-port/types/module.go
- modules/core/keeper/msg_server.go
> use new port router with OnAcknowledgementPacket

- modules/core/02-client/keeper/keeper.go
- modules/core/02-client/types/client.go
- modules/core/02-client/types/errors.go
- modules/core/04-channel/types/packet.go
- modules/core/04-channel/types/packet_test.go
- modules/core/keeper/msg_server.go
- modules/core/packet-server/keeper/keeper.go
- Fix condition on `commitV2Packet` where timeout height should be hashed only if not empty.
- Reformat some error messages.
- Change some comments.
closes: #XXXX
---
> feat(eureka): fix condition in commit packet, added test for zero timeout height

- modules/core/05-port/types/router_v2.go
(feel free to merge for me after approving)
closes: #7064 
---
> chore: docs for HandshakeRoute/PacketRoute

- modules/core/04-channel/keeper/export_test.go
- modules/core/04-channel/keeper/timeout.go
- modules/core/04-channel/keeper/timeout_test.go
> imp: reduce channel lookup in timeout flow

- modules/apps/callbacks/ibc_middleware.go
- modules/core/05-port/types/ibc_legacy_module.go
closes: #7135
This PR adds a reversal function and refactors the callbacks to reduce the amount of index manipulation used through the implementations.
---
> Add convenience func to reverse callbacks and refactor other methods

- modules/core/keeper/msg_server.go
We missed updating the message server in the timeout packet implementation, (all the tests correctly queried the legacy stack which is why they passed)
closes: #XXXX
---
> Use app router in OnTimeoutPacket handler

- modules/core/04-channel/types/packet.go
- modules/core/04-channel/types/packet_test.go
> imp: require stricter usage of app version in packet

- modules/core/packet-server/keeper/keeper.go
> chore: remove unnecessary comments

- modules/core/packet-server/keeper/keeper.go
I also decided to remove comments which I felt provided no value
closes: #7148
---
> chore: add godoc to packet server handlers

- modules/apps/27-interchain-accounts/host/ibc_module_test.go
- modules/apps/27-interchain-accounts/host/keeper/genesis_test.go
- modules/apps/27-interchain-accounts/host/keeper/handshake_test.go
- modules/apps/27-interchain-accounts/host/keeper/keeper_test.go
- modules/apps/27-interchain-accounts/host/keeper/msg_server_test.go
- modules/apps/27-interchain-accounts/host/types/codec_test.go
- modules/apps/27-interchain-accounts/host/types/msgs_test.go
> chore: use expected errors in ica host test.

- .github/workflows/e2e-test-workflow-call.yml
- e2e/sample.config.extended.yaml
- e2e/testsuite/testconfig.go
This PR is fixing 2 issues with the E2Es.
1. Previously, we were not explicitly telling the tests to retain containers upon test failure, this meant that if one test fails, the chains would be removed and all tests still running would fail.
2. The chain IDs had been changed, but we were actually relying on them for parsing the revision when generating timeouts (causing test timeout failures). I added some validation that ensures the revision ID is the same for both chains. In the case of requiring different revision numbers in a test I figured we can re-visit this later. For now this just ensures a test doesn't run when a config will cause a test to fail at runtime. 
closes: #XXXX
---
checked off. If any …
> Fix failing transfer e2es

- modules/apps/27-interchain-accounts/controller/ibc_middleware_test.go
- modules/apps/27-interchain-accounts/controller/keeper/account_test.go
- modules/apps/27-interchain-accounts/controller/keeper/grpc_query_test.go
- modules/apps/27-interchain-accounts/controller/keeper/handshake_test.go
- modules/apps/27-interchain-accounts/controller/keeper/keeper_test.go
- modules/apps/27-interchain-accounts/controller/keeper/msg_server_test.go
- modules/apps/27-interchain-accounts/controller/keeper/relay_test.go
- modules/apps/27-interchain-accounts/controller/types/codec_test.go
- modules/apps/27-interchain-accounts/controller/types/msgs_test.go
> (chore) change tests in 27ica/controller to expect specific error

- modules/core/02-client/types/client.go
- modules/core/02-client/types/client_test.go
- modules/core/23-commitment/types/v2/merkle.go
- modules/core/23-commitment/types/v2/merkle_test.go
Add validation for merkle path prefix and path. Add tests
We can maybe go even further with validation but this is a good start for now
closes: #6989 
---
> Validate MerklePathPrefix and Path

- e2e/sample.config.extended.yaml
- modules/apps/transfer/ibc_module_test.go
- modules/apps/transfer/types/packet_test.go
- modules/apps/transfer/types/transfer_authorization_test.go
fix some comments
closes: #XXXX
---
> chore: fix some comments

- modules/apps/29-fee/ibc_middleware_test.go
- modules/apps/29-fee/keeper/grpc_query_test.go
- modules/apps/29-fee/keeper/msg_server_test.go
- modules/apps/29-fee/keeper/relay_test.go
- modules/apps/29-fee/types/codec_test.go
- modules/apps/29-fee/types/fee_test.go
- modules/apps/29-fee/types/genesis_test.go
- modules/apps/29-fee/types/keys_test.go
- modules/apps/29-fee/types/msgs_test.go
- testing/utils.go
> (chore): use expected errors in 29fee

- CHANGELOG.md
- docs/docs/05-migrations/14-v9-to-v10.md
- modules/apps/27-interchain-accounts/controller/ibc_middleware.go
- modules/apps/27-interchain-accounts/controller/keeper/relay.go
- modules/apps/29-fee/ibc_middleware.go
- modules/apps/29-fee/keeper/relay.go
- modules/apps/callbacks/ibc_middleware.go
- modules/apps/callbacks/ibc_middleware_test.go
- modules/apps/transfer/keeper/relay.go
- modules/apps/transfer/keeper/relay_test.go
- modules/core/04-channel/keeper/packet.go
- modules/core/04-channel/keeper/packet_test.go
- modules/core/05-port/types/module.go
- testing/endpoint.go
- testing/mock/middleware.go
> chore (api)!: remove capabilities from SendPacket

- CHANGELOG.md
- docs/docs/05-migrations/14-v9-to-v10.md
- modules/apps/27-interchain-accounts/controller/ibc_middleware.go
- modules/apps/29-fee/ibc_middleware.go
- modules/apps/29-fee/keeper/relay.go
- modules/apps/29-fee/keeper/relay_test.go
- modules/apps/callbacks/ibc_middleware.go
- modules/apps/callbacks/ibc_middleware_test.go
- modules/apps/transfer/keeper/forwarding.go
- modules/core/04-channel/keeper/packet.go
- modules/core/04-channel/keeper/packet_test.go
- modules/core/05-port/types/module.go
- modules/core/ante/ante.go
- modules/core/keeper/msg_server.go
- testing/endpoint.go
- testing/mock/middleware.go
> chore (api)!: remove capabilities from WriteAcknowledgement

- CHANGELOG.md
- modules/apps/27-interchain-accounts/host/keeper/keeper.go
Uses the cosmos/gogoproto registry as opposed to including the entire merged global files registry.
closes: #7259
---
> fix: attempt to fix panics for unresolvable imports by using GogoResolver

- modules/core/04-channel/keeper/events.go
- modules/core/04-channel/types/errors.go
- modules/core/04-channel/types/packet.go
- modules/core/04-channel/types/timeout.go
- modules/core/keeper/msg_server_test.go
- modules/core/packet-server/keeper/relay.go
- modules/core/packet-server/keeper/relay_test.go
Paired w/ @bznein on this one!
NOTE: `Packet` type is still being emitted in events to maintain full compatibility with relayers.
closes: #XXXX
---
> Update packet lifecycle handlers to use PacketV2 struct internally

- modules/core/04-channel/keeper/events.go
- modules/core/04-channel/types/events.go
- testing/events.go
- testing/events_test.go
> chore: add ProtocolVersion, Encoding and AppVersion to SendPacket and RecvPacket events.

- .github/dependabot.yml
- .github/mergify.yml
- .markdownlint-cli2.jsonc
- docs/dev/project-structure.md
- testing/README.md
I think all that is left is the main documentation. It will need to be combed through and various pieces removed and refactored/reworded to account for the removal of capabilities.
ref: #7273 
---
> chore: rm capabilities references in workflows, markdown files

- modules/core/04-channel/v2/keeper/keeper.go
- modules/core/24-host/v2/packet_keys.go
NOTE: explicitly not closing linked issue, as these fields are subject to change pending final spec.
With these we can continue with implementations of new handler functions.
ref: #7366
closes #7132
---
> Add new keys and getter / setter functions

- modules/core/04-channel/v2/types/errors.go
- modules/core/04-channel/v2/types/packet.go
- modules/core/04-channel/v2/types/packet_test.go
> chore: Add PacketV2 ValidateBasic() function

- modules/core/04-channel/v2/keeper/msg_server.go
- modules/core/04-channel/v2/keeper/relay.go
- modules/core/api/api_test.go
- modules/core/api/module.go
- modules/core/api/router.go
- modules/core/api/router_test.go
- modules/core/keeper/msg_server.go
- testing/mock/v2/ibc_module.go
Also adding barebones mock module to have an implementation of the interface to register.
closes: #7384
---
> Adding router v2

- modules/core/04-channel/v2/keeper/events.go
- modules/core/04-channel/v2/keeper/msg_server.go
- modules/core/04-channel/v2/keeper/relay.go
> chore: add RecvPacket to V2

- modules/core/api/module.go
- testing/mock/v2/ibc_app.go
- testing/mock/v2/ibc_module.go
> chore: add OnTimeoutPacket to IBCModule V2 interface

- modules/core/api/module.go
- testing/mock/v2/ibc_app.go
- testing/mock/v2/ibc_module.go
Somewhat forgot about this one!
closes: #7410
---
> chore: Add OnAcknowledgmentPacket to IBCModule V2 Interface

- .golangci.yml
Replace loopvar linter in the .golangci.yml.
closes: #7441 
Need to fix lint errors in another PR.
```shell
$ make lint
--> Running linter
linting module github.com/cosmos/ibc-go/v9 [2024-10-13T04:43:49]
modules/apps/27-interchain-accounts/controller/keeper/keeper_test.go:143:3: The copy of the 'for' variable "tc" can be deleted (Go 1.22+) (copyloopvar)
tc := tc
^
modules/apps/27-interchain-accounts/controller/keeper/keeper_test.go:320:3: The copy of the 'for' variable "tc" can be deleted (Go 1.22+) (copyloopvar)
tc := tc
^
modules/apps/27-interchain-accounts/controller/keeper/migrations_test.go:45:3: The copy of the 'for' variable "tc" can be deleted (Go 1.22+) (copyloopvar)
tc := tc
^
modules/apps/27-interchain-accounts/controller/keeper/msg_server_test.go:70:4: The copy of the 'for' …
```
> fix(lint): replace loopvar linter

- modules/core/04-channel/v2/keeper/msg_server.go
- modules/core/internal/errors/errors.go
- modules/core/keeper/events_test.go
- modules/core/keeper/export_test.go
- modules/core/keeper/msg_server.go
- modules/core/keeper/msg_server_test.go
closes: #7436
This PR moves the error conversion into the internal directory, and includes the code improvement suggested by @bznein 
---
> Remove duplication of ConvertToErrorEvents

- modules/core/04-channel/v2/types/errors.go
- modules/core/04-channel/v2/types/msgs.go
- modules/core/04-channel/v2/types/msgs_test.go
> chore: add ValidateBasic for MsgSendPacket

- modules/core/04-channel/v2/keeper/msg_server_test.go
- testing/endpoint_v2.go
ref: #7459
This PR adds helper functions for MsgSendPacket, MsgRecvPacket and MsgAcknowledgePacket and refactors the associated tests.
The referenced issue has additional items so it won't be closed until those are all checked off.
---
> Add helper functions for MsgSendPacket, MsgRecvPacket and MsgAcknowledgePacket

- modules/core/23-commitment/types/merkle.go
Pushing leaps and bounds. Revolutionary stuff here...
---
> nit: use CommitmentProof_Nonexist in expected type error

- modules/core/04-channel/v2/types/msgs.go
- modules/core/04-channel/v2/types/msgs_test.go
> chore: add ValidateBasic for MsgTimeout in ChannelKeeper V2

- modules/core/04-channel/v2/keeper/packet.go
> chore: remove fallback logic for GetChannel in timeout handler

- CHANGELOG.md
- modules/core/23-commitment/types/merkle.go
ref https://github.com/cosmos/ics23/issues/389
closes: #XXXX
---
> refactor: remove `Batch` proof fn's

- modules/core/04-channel/v2/keeper/msg_server.go
- modules/core/04-channel/v2/keeper/msg_server_test.go
- modules/core/04-channel/v2/types/errors.go
- modules/core/04-channel/v2/types/msgs.go
Add MaxTimeout condition in the SendPacket function as specified in [004](https://github.com/cosmos/ibc/blob/d234b5be813f412f8fb47e234ccb1d542f0995a6/spec/core/v2/ics-004-channel-and-packet-semantics/README.md#:~:text=//%20disallow%20packet%20with%20timeoutTimestamp%20less%20than%20currentTimestamp%20and%20timeoutTimestamp%20value%20bigger%20than%20currentTimestamp%20%2B%20MaxTimeoutDelta%20%0A%20%20%20%20assert(currentTimestamp()%20%3C%20timeoutTimestamp%20%3C%20currentTimestamp()%20%2B%20MAX_TIMEOUT_DELTA))
closes: https://github.com/cosmos/ibc-go/issues/7337
---
> Add MaxTimeout condition

- modules/core/04-channel/v2/keeper/msg_server.go
- modules/core/04-channel/v2/keeper/msg_server_test.go
- modules/core/04-channel/v2/keeper/packet.go
- modules/core/04-channel/v2/keeper/packet_test.go
- modules/core/04-channel/v2/types/errors.go
- modules/core/04-channel/v2/types/msgs.go
- modules/core/04-channel/v2/types/msgs_test.go
Note: there are still some imports of channelv1 in v2:
```
> grep -rli "modules/core/04-channel/types"
types/tx.pb.go
keeper/keeper_test.go
keeper/keeper.go
keeper/msg_server.go
```
These are all related to using the `ResponseResultType` enum in V2. I think we should duplicate it to V2 too and get totally rid of v1 imports in v2. But I'd prefer doing so in a separate PR (assuming people agree)
closes: #7476
---
> chore: remove usage of v1 errors from v2

- modules/core/04-channel/v2/keeper/msg_server.go
- modules/core/04-channel/v2/keeper/msg_server_test.go
- modules/core/04-channel/v2/types/errors.go
Consolidate timeout errors. Remove redundant error types.
Align import aliasing.
closes: #XXXX
---
> chore: reduce number of timeout errors, cleanup

- modules/core/ante/ante.go
- modules/core/ante/ante_test.go
Notes: will merge after https://github.com/cosmos/ibc-go/pull/7464 to make sure the timeout case is not broken here.
I didn't add tests for ALL new code paths. I followed the current structure of tests and basically added V2 cases for equivalent tests. Happy to add more cases if people prefer
closes: #7491 
---
> chore: add redundancy checks for V2 Msgs

- cmd/build_test_matrix/main.go
- cmd/build_test_matrix/main_test.go
When the script that crawls test files to pick up test names encounters a file in a test directory that does not have any tests it explodes, instead we can just skip those files, and fail only if we have not found any files after crawling the entire directory.
---
> Ignore files with no tests when searching for test files

- modules/core/04-channel/v2/keeper/msg_server.go
- modules/core/04-channel/v2/keeper/msg_server_test.go
Noticed a bit of bad DX when I was sending in the wrong channel-id to register counterparty. Since it was checking the creator first, I got creator not found, when the real issue was that the channel id was not correct (channel not found). Moved the check up and adjusted the test to catch this.
---
> fix: channel must exist before channel creator check

- modules/core/04-channel/v2/keeper/keeper.go
- modules/core/04-channel/v2/types/commitment.go
> Match commitment to specification

- modules/core/04-channel/v2/keeper/events.go
- modules/core/04-channel/v2/keeper/msg_server.go
- modules/core/04-channel/v2/types/events.go
simply also emits the client identifier in the event currently emitted.
part-of: #7386
---
> chore: amend event emitted for create channel to include client identifier

- modules/apps/transfer/ibc_module.go
- modules/apps/transfer/types/packet.go
- modules/apps/transfer/types/packet_test.go
- modules/apps/transfer/v2/ibc_module.go
- modules/apps/transfer/v2/keeper/msg_server_test.go
- modules/core/04-channel/v2/types/msgs_test.go
- modules/core/04-channel/v2/types/packet_test.go
- testing/mock/v2/mock.go
> chore: use encoding fields for packet data unmarshaling

- modules/core/04-channel/v2/keeper/events.go
- modules/core/04-channel/v2/keeper/packet.go
- modules/core/04-channel/v2/types/events.go
part of: #7386
also unblocks #7459
---
> chore: add events for send packet

- testing/endpoint.go
- testing/endpoint_v2.go
> testing: add merkle path to endpoint struct.

- modules/core/04-channel/v2/keeper/events.go
- modules/core/04-channel/v2/keeper/packet.go
- modules/core/04-channel/v2/types/events.go
closes: #7607, #7608, #7386
---
> imp: added simpler events

- modules/core/04-channel/v2/keeper/events.go
- modules/core/04-channel/v2/types/events.go
closes: #7634 
Relevant for relayer work @srdtrk since I also changed the attribute strings.
---
> chore: 7634 rename attributekeypacketdatahex in 04 channel v2

- modules/core/04-channel/v2/keeper/msg_server_test.go
- modules/core/04-channel/v2/keeper/packet.go
test for this already existed, it passed because it too used the wrong channel identifier.
closes: #7643
---
> bug: fix packet commitment path used for timeout

- modules/core/04-channel/v2/types/packet.go
> fix: correct error message for payload validation in packet ValidateBasic

- modules/core/04-channel/v2/keeper/msg_server.go
- modules/core/04-channel/v2/keeper/msg_server_test.go
- modules/core/04-channel/v2/keeper/packet.go
- modules/core/04-channel/v2/keeper/packet_test.go
- modules/core/04-channel/v2/types/acknowledgement.go
- modules/core/04-channel/v2/types/acknowledgement_test.go
- modules/core/04-channel/v2/types/msgs.go
- modules/core/04-channel/v2/types/msgs_test.go
> chore: add validation for Ack and plug it in.

- modules/apps/transfer/keeper/keeper.go
> chore: uses errors.New

- modules/core/23-commitment/types/codec_test.go
- modules/core/23-commitment/types/utils_test.go
> (chore) change tests in 23-commitment/types to expect specific error

- cmd/build_test_matrix/main.go
- modules/core/24-host/parse_test.go
- modules/core/24-host/validate_test.go
> (chore) update tests in core/24-host to expect specific error

- modules/core/04-channel/v2/keeper/grpc_query.go
- modules/core/04-channel/v2/types/keys.go
- modules/core/24-host/v2/packet_keys.go
closes: #7632 
I also moved the packet commitment prefix functions to 24-host to not have multiple implementations floating around (and where they will be under unit tests).
---
> chore: document channel id requirements for packet commitment keys

- modules/core/04-channel/v2/keeper/msg_server.go
closes: #7636 
It was also mentioned during the audit that this should also be done for timeout, but I guess the moving the Route loop earlier would make trouble in the no-op case? If there are some other cases here I should cover, let me know and I will add it to the PR.
---
> chore: do validation checks before processing the packet in 04 channel v2

- modules/core/api/router.go
- modules/core/api/router_test.go
- modules/light-clients/08-wasm/testing/simapp/app.go
- testing/mock/v2/ibc_module.go
- testing/simapp/app.go
> chore: change v2 router mapping to use port id rather than module name

- e2e/testsuite/testsuite.go
> chores: fix function name

- modules/core/03-connection/types/connection_test.go
- modules/core/03-connection/types/genesis_test.go
> chores: fix more connection tests

- modules/core/04-channel/v2/keeper/msg_server.go
- modules/core/internal/v2/telemetry/packet.go
> chore: add telemetry reporting for packet methods

- modules/core/04-channel/v2/keeper/msg_server.go
- modules/core/04-channel/v2/keeper/packet.go
> chore: remove redundant calls to emit events in cached context.

- modules/apps/transfer/keeper/keeper.go
Forgot to push before merging
closes: #XXXX
---
> chore: update import alias to align

- CHANGELOG.md
- modules/apps/27-interchain-accounts/controller/keeper/genesis_test.go
- modules/apps/27-interchain-accounts/host/ibc_module_test.go
- modules/apps/27-interchain-accounts/host/keeper/account.go
- modules/apps/27-interchain-accounts/host/keeper/genesis_test.go
- modules/apps/27-interchain-accounts/host/keeper/handshake_test.go
- modules/apps/27-interchain-accounts/types/account.go
- modules/apps/27-interchain-accounts/types/account_test.go
- testing/chain.go
Removes `UnwrapSDKContext` for interchain accounts. 
Now uses block hash (merkle root of block) instead of dataHash for interchain accounts address generation.
The `ctx.BlockHeader` is deprecated and recommended to now use service based approach. The `HeaderService` provided by cosmos-sdk returns `header.Info` which only contains `appHash`, `hash` (merkle root of block), `height`, `time` and `chainID`.
It is recommended to use `cometservice` when anything else is needed.
---
> refactor: use header info for interchain accounts address generation

- modules/apps/29-fee/keeper/escrow.go
- modules/apps/29-fee/keeper/events.go
- modules/apps/29-fee/keeper/msg_server.go
> chore: refactor event service to 29-fee

- modules/core/02-client/types/params_test.go
> fix experror in param test

- e2e/testsuite/testconfig.go
- modules/light-clients/08-wasm/types/gas_register.go
fix struct field name in comment
---
> chore: fix struct field name in comment

- modules/core/04-channel/types/packet_test.go
> fixed exp error in modules/04-channel/types/packet-test.go

- modules/core/02-client/types/keys_test.go
> chore: use exp error in test TestParseClientIdentifier

- modules/apps/27-interchain-accounts/types/codec_test.go
> chore: fix test TestSerializeAndDeserializeCosmosTx, use expected errors

- docs/docs/05-migrations/07-v5-to-v6.md
Corrected `acccounts` to `accounts`
> fix: typos in documentation files

- e2e/tests/interchain_accounts/groups_test.go
- e2e/testsuite/diagnostics/diagnostics.go
- modules/apps/callbacks/callbacks_test.go
- modules/apps/callbacks/testing/simapp/export.go
- modules/apps/callbacks/testing/simapp/genesis.go
- modules/core/02-client/types/height.go
- modules/core/24-host/validate.go
- modules/light-clients/08-wasm/testing/simapp/export.go
- modules/light-clients/08-wasm/testing/simapp/genesis.go
- simapp/export.go
This pull request fixes several typographical errors in various Go files, enhancing the clarity and accuracy of code comments and documentation. These changes include correcting minor grammatical issues, such as redundant phrases and incorrect wording, across multiple modules and files.
1. Corrected typographical errors in code comments and documentation:
- Improved clarity in statements such as "check if there is a allowed address list" to "check if there is an allowed address list."
2. Updated function comments and documentation for better readability and consistency.
These updates help maintain the overall quality and readability of the codebase, ensuring that the comments are informative and free from errors.
Please ensure all checklist items have been reviewed and completed before …
> Fix Typographical Errors

- .github/workflows/callbacks.yml
- .github/workflows/e2emodule.yml
- .github/workflows/golangci-feature.yml
- .github/workflows/golangci.yml
- .github/workflows/wasm-client.yml
- modules/apps/29-fee/keeper/grpc_query.go
- modules/core/04-channel/keeper/keeper.go
- modules/core/24-host/validate.go
- modules/light-clients/07-tendermint/client_state.go
> chore: fix and update linter

- e2e/testsuite/tx.go
> perf: decode proposal id from tx resp

- modules/core/04-channel/v2/keeper/packet.go
- modules/core/04-channel/v2/types/packet.go
> Compare Timeout timestamps in seconds instead of nanoseconds

- e2e/go.mod
- e2e/testsuite/sanitize/messages.go
Closes #7844
I will run the compatibility tests with this branch before merging.
---
> fix: sanitize gov v1 proposal in e2e tests for compatibility with 0.52

- e2e/tests/transfer/base_test.go
- modules/apps/transfer/keeper/msg_server.go
- modules/apps/transfer/keeper/relay.go
- modules/apps/transfer/transfer_test.go
> fix: send entire balance not working as expected

- modules/apps/29-fee/ibc_middleware.go
- modules/apps/29-fee/keeper/escrow.go
- modules/apps/29-fee/keeper/keeper.go
- modules/apps/29-fee/keeper/migrations.go
- modules/apps/29-fee/keeper/msg_server.go
- modules/apps/callbacks/testing/simapp/app.go
- modules/core/keeper/keeper.go
- modules/core/keeper/keeper_test.go
- modules/core/keeper/msg_server.go
- modules/light-clients/08-wasm/testing/simapp/app.go
- simapp/app.go
- testing/simapp/app.go
removes sdk.AccAddressFromBech32 where possible. all keepers have an address codec field now to avoid using the aforementioned function.
closes: #7835
---
> chore: make all keepers use address codecs

- modules/apps/callbacks/testing/simapp/app.go
- modules/light-clients/08-wasm/testing/simapp/app.go
- simapp/app.go
- testing/simapp/app.go
> chore: change usage of deprecated module.NewManager in SimApps

- modules/apps/transfer/keeper/export_test.go
- modules/apps/transfer/keeper/msg_server.go
- modules/apps/transfer/keeper/relay.go
- modules/apps/transfer/v2/ibc_module_test.go
This is a basic framework for eureka transfer tests. I would like to merge this in if there aren't glaring issues, as this is meant to serve as a starting point for flushing out more eureka transfer tests.
---
> test: add initial eureka transfer tests

- modules/apps/transfer/v2/ibc_module.go
- modules/apps/transfer/v2/ibc_module_test.go
This PR rejects packets that could possibly trigger bugs in ICS20 v1 packet data being sent with the Eureka module
- The requirement that both portIDs are transfer prevents this [issue](https://github.com/cosmos/ibc/issues/1178) from being exploited in the initial release at the cost of preventing non-transfer port ICS20 implementations from being able to send tokens with Eureka
- The requirement that the base denom has no slashes prevents any misinterpretation of the trace and base denom with ICS20-1 now that the trace is no longer going to strictly contain channel identifiers in each hop.
---
> Harden ICS20 Eureka Module

- modules/core/04-channel/types/packet.go
- modules/core/04-channel/types/packet_test.go
- modules/core/04-channel/v2/types/packet.go
- modules/core/04-channel/v2/types/packet_test.go
closes: #7629
waiting on: #7932 (will rebase after it has been merged)
---
> imp: limit payload size for both v1 and v2 packet

- CHANGELOG.md
- modules/apps/27-interchain-accounts/controller/client/cli/tx.go
This slipped in at some point in the past to attempt to use absolute timeouts in the ica `sendTx` cli.
This is incorrect as the within the state machine an absolute timeout is calculated by adding the provided value to the current block time.
ref: https://github.com/cosmos/ibc-go/blob/main/modules/apps/27-interchain-accounts/controller/keeper/msg_server.go#L72-L75
cc. @yihuang 
---
> fix: only use relative timeout timestamps in ica cli

- modules/apps/transfer/types/packet.go
> fix: remove packet data remarshaling

- modules/core/04-channel/keeper/packet_test.go
https://celestia-team.slack.com/archives/C01BZ4XNGFK/p1741950351888399
cc: @gjermundgaraba 
[This PR](https://github.com/cosmos/ibc-go/commit/a5b5b929831859be62c5f7dc94970efa868cc84b) added a test case for the most recent security vulnerability but the test case doesn't verify that the error is of type `types.ErrInvalidAcknowledgement`
> test: set expError for fake acknowledgement test case

- docs/docs/04-middleware/01-callbacks/02-integration.md
- docs/docs/04-middleware/01-callbacks/06-gas.md
- docs/docs/04-middleware/01-callbacks/07-callbacks-IBCv2.md
- updates callbacks documentation for v2
closes: #XXXX
---
> docs: ibc v2 callbacks docs

- codecov.yml
Codecov is a bit annoying. It should not comment unless there is something that should be taken action _on_. With this PR it only comments if the coverage drops below the predifined setting, or if code in the PR is uncovered.
---
> chore: make codecov only comment on coverage drop or uncovered

- docs/dev/go-style-guide.md
This PR will be a discussion place to finalize our updated style guide. With the unleash the builder initiative, and new people joining the team, it's high time we solidify best practices so that the code remains in high standard. 
closes: #8372 
---
> chore: update style guide

- AGENTS.md
> chore: experiment with agents file

- Makefile
- docs/.markdownlint.jsonc
Glob in the `Makefile` was not expanding properly. All errors were of the same kind and I simply excluded them because I personally didn't see value in very expressive link names.
closes: #XXXX
---
> chore: use find for md discovery and relax link rules

- modules/light-clients/08-wasm/go.mod
- modules/light-clients/08-wasm/go.sum
Co-authored-by: Gjermund Garaba <gjermund@garaba.net>
closes: #XXXX
---
> chore: post-release replace for 08-wasm

- .github/workflows/build-simd-image-from-tag.yml
- .github/workflows/build-wasm-simd-image-from-tag.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/dependabot-tidy.yml
- .github/workflows/docker.yml
- .github/workflows/docs-check.yml
- .github/workflows/docs-deploy.yml
- .github/workflows/e2e-compatibility-workflow-call.yaml
- .github/workflows/e2e-compatibility.yaml
- .github/workflows/e2e-upgrade.yaml
- .github/workflows/e2e.yaml
- .github/workflows/golangci.yml
- .github/workflows/proto-breaking-check.yml
- .github/workflows/proto-registry.yml
- .github/workflows/test.yml
Update GitHub Actions workflows to use depot ubuntu 24.04 and checkout v5.
To use the latest version of checkout, we also needed to update our runners, which was due anyway...
> chore: bump ci deps

- CHANGELOG.md
- modules/apps/transfer/keeper/keeper.go
- modules/apps/transfer/keeper/msg_server.go
- modules/apps/transfer/keeper/msg_server_test.go
- modules/apps/transfer/keeper/relay.go
- modules/apps/transfer/keeper/relay_test.go
- modules/apps/transfer/types/msgs.go
- modules/apps/transfer/types/msgs_test.go
- modules/apps/transfer/v2/ibc_module.go
- testing/mock/address_codec.go
Backport #8573 without api breakage.
---
> imp(transfer)!: use AddressCodec instead of Bech32 (backport #8573)
